obj-$(CONFIG_ARCH_TCC) += vioc_rdma.o vioc_wdma.o vioc_wmix.o vioc_vin.o
obj-$(CONFIG_ARCH_TCC) += vioc_scaler.o vioc_viqe.o vioc_lut.o
obj-$(CONFIG_ARCH_TCC) += vioc_intr.o vioc_fifo.o vioc_ddicfg.o vioc_deintls.o
obj-$(CONFIG_ARCH_TCC) += vioc_config.o vioc_disp.o vioc_outcfg.o
obj-$(CONFIG_VIOC_DOLBY_VISION_EDR) += vioc_v_dv.o
obj-$(CONFIG_ARCH_TCC) += tccfb_address.o
obj-$(CONFIG_ARCH_TCC898X) += vioc_dtrc.o vioc_extra.o
obj-$(CONFIG_ARCH_TCC803X) += vioc_pxdemux.o vioc_lvds.o
obj-$(CONFIG_ARCH_TCC897X) += vioc_lvds_t.o
#obj-$(CONFIG_ARCH_TCC898X) += vioc_power.o

obj-$(CONFIG_FB_TCC)			+= tca_lcdc.o

obj-$(CONFIG_FB_TCC_COMPOSITE) += tcc_composite.o
obj-$(CONFIG_FB_TCC_COMPOSITE_TVE) += vioc_tve.o
obj-$(CONFIG_FB_TCC_COMPOSITE_BVO) += vioc_bvo.o

obj-$(CONFIG_FB_TCC_COMPONENT) += tcc_component.o
obj-$(CONFIG_FB_TCC_COMPONENT_ADV7343) += tcc_component_adv7343.o
obj-$(CONFIG_FB_TCC_COMPONENT_THS8200) += tcc_component_ths8200.o

obj-$(CONFIG_VIOC_MAP_DECOMP)	+= vioc_mc.o tca_map_converter.o
obj-$(CONFIG_VIOC_DTRC_DECOMP)	+= tca_dtrc_converter.o
obj-$(CONFIG_VIOC_PIXEL_MAPPER) += vioc_pixel_mapper.o
obj-$(CONFIG_VIOC_2D_FILTER) += vioc_filter2D.o
obj-$(CONFIG_VIOC_CHROMA_INTERPOLATOR) += vioc_chromainterpolator.o
obj-$(CONFIG_VIOC_SAR) += vioc_sar.o

obj-$(CONFIG_TCC_VIQE_MADI)   += viqe_madi.o
obj-$(CONFIG_TCC_DV_IN)   += vioc_dv_in.o
obj-$(CONFIG_VIOC_AFBCDEC) += vioc_afbcdec.o
