# drivers/media/platform/videosource/videodecoder/Makefile
#
# Copyright (c) 2010 Telechips Co., Ltd.
#	http://www.telechips.com/
# Jay <B150095@telechips.com>
#
# Licensed under GPL

obj-y	+= adv7182.o
obj-y	+= dm5886.o
obj-y	+= isl79988.o

