# drivers/media/platform/videosource/videodecoder/Makefile
#
# Copyright (c) 2010-2011 Telechips Co., Ltd.
#	http://www.telechips.com/
# Jay <B150095@telechips.com>
#
# Licensed under GPL

obj-$(CONFIG_VIDEO_VIDEOSOURCE_VIDEODECODER_DM5886)	+= dm5886.o
obj-$(CONFIG_VIDEO_VIDEOSOURCE_VIDEODECODER_ISL79988) 	+= isl79988.o
obj-$(CONFIG_VIDEO_VIDEOSOURCE_VIDEODECODER_DS90UB964) 	+= ds90ub964.o
obj-$(CONFIG_VIDEO_VIDEOSOURCE_VIDEODECODER_MAX9286) 	+= max9286.o
