ifeq ($(filter y,$(CONFIG_ARCH_TCC897X) $(CONFIG_ARCH_TCC802X)\
	$(CONFIG_ARCH_TCC899X) $(CONFIG_ARCH_TCC803X) $(CONFIG_ARCH_TCC901X)),)
obj-$(CONFIG_TCC_THERMAL)	+= thermal_common.o
endif
obj-$(CONFIG_ARCH_TCC805X)	+= tcc805x_thermal.o
obj-$(CONFIG_ARCH_TCC803X)	+= tcc_thermal.o
obj-$(CONFIG_ARCH_TCC897X)	+= tcc_thermal.o
obj-$(CONFIG_ARCH_TCC899X)	+= tcc_thermal.o
obj-$(CONFIG_ARCH_TCC802X)	+= tcc_thermal.o
obj-$(CONFIG_ARCH_TCC901X)	+= tcc_thermal.o
