# drivers/media/platform/videosource/mipi-csi2/Makefile
#
# Copyright (c) 2010 Telechips Co., Ltd.
#	http://www.telechips.com/
# Jay <B150095@telechips.com>
#
# Licensed under GPL

obj-y 	+= mipi-csi2.o

