# drivers/media/platform/tccvin/Makefile
#
# Copyright (c) 2010-2011 Telechips Co., Ltd.
#	http://www.telechips.com/
# Jay <B150095@telechips.com>
#
# Licensed under GPL

obj-y						+= tccvin_core.o tccvin_dev.o
obj-$(CONFIG_VIDEO_TCCVIN_SWITCHMANAGER)	+= tccvin_switchmanager.o

