# SPDX-License-Identifier: GPL-2.0
# Generic MAILBOX API

obj-$(CONFIG_TCC_MULTI_MAILBOX) += tcc_multi_mbox_dev.o

tcc_multi_mbox_dev-y := tcc_multi_mbox.o

obj-$(CONFIG_TCC_MULTI_MAILBOX_TEST) += tcc_multi_mbox_test.o
