obj-$(CONFIG_TCC_GMAC)	+= tcc_gmac.o
obj-$(CONFIG_ARCH_TCC898X) += tca_gmac.o
obj-$(CONFIG_ARCH_TCC899X) += tca_gmac.o
obj-$(CONFIG_ARCH_TCC802X) += tca_gmac.o
obj-$(CONFIG_ARCH_TCC803X) += tca_gmac.o
obj-$(CONFIG_ARCH_TCC901X) += tca_gmac.o
tcc_gmac-objs := tcc_gmac_drv.o tcc_gmac_ctrl.o tcc_gmac_ethtool.o
obj-$(CONFIG_TCC_GMAC_PTP)	+= tcc_gmac_ptp.o
