#ifndef USB_VENDOR_ID_ILITEK
	#define USB_VENDOR_ID_ILITEK	0x222A
#endif
#ifndef USB_DEVICE_ID_ILITEK_MT
	#define USB_DEVICE_ID_ILITEK_MT	0x0088
#endif
#define TOUCH_PROTOCOL_B
//#define SINGLE_TOUCH
//#define ROTATE_FLAG_90
//#define ROTATE_FLAG_180
//#define ROTATE_FLAG_270