obj-y += pinctrl-tcc.o
obj-$(CONFIG_ARCH_TCC897X)	+= pinctrl-tcc897x.o
obj-$(CONFIG_ARCH_TCC898X)	+= pinctrl-tcc898x.o
obj-$(CONFIG_ARCH_TCC899X)	+= pinctrl-tcc899x.o
obj-$(CONFIG_ARCH_TCC802X)	+= pinctrl-tcc802x.o
obj-$(CONFIG_ARCH_TCC803X)	+= pinctrl-tcc803x.o
obj-$(CONFIG_ARCH_TCC901X)	+= pinctrl-tcc901x.o
