#ifndef __SILABS_H__
#define __SILABS_H__

typedef enum tag_silabs_fe_type_e
{
	SILABS_FE_TYPE_SINGLE, 
	SILABS_FE_TYPE_DUAL, 
	SILABS_FE_TYPE_TRIPLE, 
	SILABS_FE_TYPE_QUAD, 
	SILABS_FE_TYPE_MAX
} silabs_fe_type_e;

typedef enum tag_silabs_standard_e
{
	SILABS_STANDARD_ANALOG 	= 4, 
	SILABS_STANDARD_DVB_T 	= 0, 
	SILABS_STANDARD_DVB_C 	= 1, 
	SILABS_STANDARD_DVB_S 	= 2, 
	SILABS_STANDARD_DVB_S2 	= 3, 
	SILABS_STANDARD_DVB_T2 	= 5, 
	SILABS_STANDARD_DSS 	= 6, 
	SILABS_STANDARD_MCNS 	= 7, 
	SILABS_STANDARD_DVB_C2 	= 8, 
	SILABS_STANDARD_ISDB_T 	= 9, 
	SILABS_STANDARD_SLEEP 	= 100, 
	SILABS_STANDARD_OFF 	= 200
} silabs_standard_e;

typedef enum tag_silabs_stream_e
{
	SILABS_STREAM_HP, 
	SILABS_STREAM_LP
} silabs_stream_e;

typedef enum tag_silbas_constel_e
{
	SILABS_CONSTEL_QAMAUTO 	= 100,
	SILABS_CONSTEL_QAM16 	=  0,
	SILABS_CONSTEL_QAM32 	=  1,
	SILABS_CONSTEL_QAM64 	=  2,
	SILABS_CONSTEL_QAM128 	=  3,
	SILABS_CONSTEL_QAM256 	=  4,
	SILABS_CONSTEL_QPSK 	=  5,
	SILABS_CONSTEL_8PSK 	=  6,
	SILABS_CONSTEL_QAM1024 	=  7,
	SILABS_CONSTEL_QAM4096 	=  8,
	SILABS_CONSTEL_8APSK_L 	= 10,
	SILABS_CONSTEL_16APSK 	= 11,
	SILABS_CONSTEL_16APSK_L = 12,
	SILABS_CONSTEL_32APSK_1 = 13,
	SILABS_CONSTEL_32APSK_2 = 14,
	SILABS_CONSTEL_32APSK_L = 15,
	SILABS_CONSTEL_DQPSK 	= 16
} silbas_constel_e;

typedef enum tag_silabs_polar_e
{
	SILABS_POLAR_HORIZONTAL, 
	SILABS_POLAR_VERTICAL, 
	SILABS_POLAR_DO_NOT_CHANGE
} silabs_polar_e;

typedef enum tag_silabs_band_type_e
{
	SILABS_BAND_TYPE_LOW, 
	SILABS_BAND_TYPE_HIGH, 
	SILABS_BAND_TYPE_DO_NOT_CHANGE
} silabs_band_type_e;

#endif	// __SILABS_H__
