# drivers/media/platform/videosource/mipi-deserializer/Makefile
#
# Copyright (c) 2010-2011 Telechips Co., Ltd.
#	http://www.telechips.com/
# Jay <B150095@telechips.com>
#
# Licensed under GPL

obj-y	+= ds90ub964.o
obj-y	+= max9276.o
obj-y	+= max9286.o

