# drivers/char/switch/Makefile
#
# Copyright (c) 2010-2011 Telechips Co., Ltd.
#	http://www.telechips.com/
# Jay <B150095@telechips.com>
#
# Licensed under GPL

obj-$(CONFIG_SWITCH_REVERSE)	+= switch_reverse.o
obj-$(CONFIG_MAILBOX)		+= switch_reverse_ipc.o

