// SPDX-License-Identifier: (GPL-2.0+ OR MIT)
/*
 * Copyright (C) 2020 Telechips Inc.
 */
#ifndef DT_BINDINGS_PMAP_TCC805X_LINUX_IVI_SUBCORE_A53Q_H
#define DT_BINDINGS_PMAP_TCC805X_LINUX_IVI_SUBCORE_A53Q_H

#include <dt-bindings/pmap/pmap-tcc805x-linux-ivi-subcore-a53q-display.h>

#define RESERVED_MEM_BASE		( 0x4A800000 )
#define RESERVED_MEM_SIZE		( 0x15800000  - PMAP_SIZE_REARCAMERAS - PMAP_SIZE_ION_CARVEOUT_CAM )

#define REARCAMERA_MEM_BASE		( RESERVED_MEM_BASE + RESERVED_MEM_SIZE )
#define REARCAMERA_MEM_SIZE		( PMAP_SIZE_REARCAMERAS )
#define ION_CARVEOUT_CAM_MEM_BASE	( REARCAMERA_MEM_BASE + REARCAMERA_MEM_SIZE )
#define ION_CARVEOUT_CAM_MEM_SIZE	( PMAP_SIZE_ION_CARVEOUT_CAM )

#endif//DT_BINDINGS_PMAP_TCC805X_IVI_SUBCORE_A53Q_H
