// SPDX-License-Identifier: (GPL-2.0+ OR MIT)
/*
 * Copyright (C) 2020 Telechips Inc.
 */
#ifndef DT_BINDINGS_PMAP_TCC803X_LINUX_IVI_VIDEO_H
#define DT_BINDINGS_PMAP_TCC803X_LINUX_IVI_VIDEO_H

#endif//DT_BINDINGS_PMAP_TCC803X_LINUX_IVI_VIDEO_H
