// SPDX-License-Identifier: (GPL-2.0+ OR MIT)
/*
 * Copyright (C) 2020 Telechips Inc.
 */
#ifndef DT_BINDINGS_PMAP_TCC803X_LINUX_IVI_SUBCORE_A7S_DISPLAY_H
#define DT_BINDINGS_PMAP_TCC803X_LINUX_IVI_SUBCORE_A7S_DISPLAY_H

//***************************** DISPLAY ******************************/
#define PRIMARY_FRAMEBUFFER_WIDTH	1920
#define PRIMARY_FRAMEBUFFER_HEIGHT	720
#define SECONDARY_FRAMEBUFFER_WIDTH	0
#define SECONDARY_FRAMEBUFFER_HEIGHT	0

//****************************** Camera ******************************/
#define CAMERA_INPUT_WIDTH		720
#define CAMERA_INPUT_HEIGHT		480
#define CAMERA_OUTPUT_WIDTH		1920
#define CAMERA_OUTPUT_HEIGHT		720

#define FRAMES_CAMERA_VIQE		4	// 4: 3D Mode
#define FRAMES_CAMERA_PREVIEW		4
#define FRAMES_CAMERA_CAPTURE		0
#define FRAMES_CAMERA_PGL		1

#define FRAMES_REARCAMERA_VIQE		(FRAMES_CAMERA_VIQE)
#define FRAMES_REARCAMERA		(FRAMES_CAMERA_PREVIEW + \
					 FRAMES_CAMERA_CAPTURE)
#define FRAMES_REARCAMERA1		(FRAMES_CAMERA_PREVIEW)
#define FRAMES_REARCAMERA2		(FRAMES_CAMERA_PREVIEW)
#define FRAMES_REARCAMERA3		(FRAMES_CAMERA_PREVIEW)
#define FRAMES_REARCAMERA4		(0)
#define FRAMES_REARCAMERA5		(0)
#define FRAMES_REARCAMERA6		(0)
#define FRAMES_PARKING_GUI		(FRAMES_CAMERA_PGL)
#define FRAMES_OVERLAY_ROT		(0)

#endif//DT_BINDINGS_TCC803X_PMAP_IVI_DISPLAY_SUBCORE_A7S_H
