// SPDX-License-Identifier: (GPL-2.0+ OR MIT)
/*
 * Copyright (C) 2020 Telechips Inc.
 */
#ifndef DT_BINDINGS_PMAP_TCC803X_IVI_COMMON_H
#define DT_BINDINGS_PMAP_TCC803X_IVI_COMMON_H

#include <dt-bindings/pmap/pmap-tcc803x-android-ivi-display.h>
#include <dt-bindings/pmap/pmap-tcc803x-android-ivi-video.h>

#undef SZ_1MB
#define SZ_1MB				(1024*1024)
#define ARRAY_16MBYTE(x)		((((x) + ((16*SZ_1MB)-1))>> 24) << 24)
#define ARRAY_MBYTE(x)			((((x) + (SZ_1MB-1))>> 20) << 20)
#define ARRAY_256KBYTE(x)		((((x) + ((SZ_1MB/4)-1))>> 18) << 18)

#define PMAP_SIZE_FB_VIDEO		\
	ARRAY_MBYTE(PRIMARY_FRAMEBUFFER_WIDTH * \
		PRIMARY_FRAMEBUFFER_HEIGHT * 4 * 3)
#define PMAP_SIZE_FB1_VIDEO		\
	ARRAY_MBYTE(SECONDARY_FRAMEBUFFER_WIDTH * \
		SECONDARY_FRAMEBUFFER_HEIGHT * 4 * 3)
#define PMAP_SIZE_FB2_VIDEO		\
	ARRAY_MBYTE(TERTIARY_FRAMEBUFFER_WIDTH * \
		TERTIARY_FRAMEBUFFER_HEIGHT * 4 * 3)
#define PMAP_SIZE_OVERLAY_ROT		\
	ARRAY_MBYTE(PRIMARY_FRAMEBUFFER_WIDTH * \
		PRIMARY_FRAMEBUFFER_HEIGHT * 4 * FRAMES_OVERLAY_ROT)
#define PMAP_SIZE_UMP_RESERVED		\
	ARRAY_MBYTE((PRIMARY_FRAMEBUFFER_WIDTH * 4) * \
		PRIMARY_FRAMEBUFFER_HEIGHT * 4 * 4)
#define PMAP_SIZE_REARCAMERA_VIQE	\
	ARRAY_MBYTE((CAMERA_INPUT_WIDTH * (CAMERA_INPUT_HEIGHT / 2 ) * 4 * \
		FRAMES_REARCAMERA_VIQE) * 3 / 2)
#define PMAP_SIZE_REARCAMERA		\
	ARRAY_MBYTE(CAMERA_OUTPUT_WIDTH * CAMERA_OUTPUT_HEIGHT * 4 * \
		FRAMES_REARCAMERA)
#define PMAP_SIZE_REARCAMERA1		\
	ARRAY_MBYTE(CAMERA_OUTPUT_WIDTH * CAMERA_OUTPUT_HEIGHT * 4 * \
		FRAMES_REARCAMERA)
#define PMAP_SIZE_REARCAMERA2		\
	ARRAY_MBYTE(CAMERA_OUTPUT_WIDTH * CAMERA_OUTPUT_HEIGHT * 4 * \
		FRAMES_REARCAMERA)
#define PMAP_SIZE_REARCAMERA3		\
	ARRAY_MBYTE(CAMERA_OUTPUT_WIDTH * CAMERA_OUTPUT_HEIGHT * 4 * \
		FRAMES_REARCAMERA)
#define PMAP_SIZE_REARCAMERA4		\
	ARRAY_MBYTE(CAMERA_OUTPUT_WIDTH * CAMERA_OUTPUT_HEIGHT * 4 * \
		FRAMES_REARCAMERA)
#define PMAP_SIZE_REARCAMERA5		\
	ARRAY_MBYTE(CAMERA_OUTPUT_WIDTH * CAMERA_OUTPUT_HEIGHT * 4 * \
		FRAMES_REARCAMERA)
#define PMAP_SIZE_REARCAMERA6		\
	ARRAY_MBYTE(CAMERA_OUTPUT_WIDTH * CAMERA_OUTPUT_HEIGHT * 4 * \
		FRAMES_REARCAMERA)
#define PMAP_SIZE_PARKING_GUI		\
	ARRAY_MBYTE(CAMERA_OUTPUT_WIDTH * CAMERA_OUTPUT_HEIGHT * 4 * \
		FRAMES_PARKING_GUI)

#define PMAP_SIZE_EARLY_REARCAM		(\
	PMAP_SIZE_REARCAMERA_VIQE + \
	PMAP_SIZE_REARCAMERA + \
	PMAP_SIZE_REARCAMERA1 + \
	PMAP_SIZE_REARCAMERA2 + \
	PMAP_SIZE_REARCAMERA3 + \
	PMAP_SIZE_REARCAMERA4 + \
	PMAP_SIZE_REARCAMERA5 + \
	PMAP_SIZE_REARCAMERA6 + \
	PMAP_SIZE_PARKING_GUI)

#endif//DT_BINDINGS_PMAP_TCC803X_ANDROID_IVI_COMMON_H
