ccflags-y += -I$(src)			# needed for trace events

#obj-y					+= ion/
obj-$(CONFIG_ION_4_14)  		+= ion/
obj-$(CONFIG_ION_4_9)  			+= ion_4.9/
obj-$(CONFIG_FIQ_DEBUGGER)		+= fiq_debugger/

obj-$(CONFIG_ASHMEM)			+= ashmem.o
obj-$(CONFIG_ANDROID_VSOC)		+= vsoc.o
