EXTRA_CFLAGS += -I$(srctree)/drivers/char/hdmi_v1_4/include \
		-I$(srctree)/drivers/char/hdmi_v1_4/hdmi \
		-I$(srctree)/drivers/clk/tcc \
		-I$(srctree)/include/dt-bindings/clock

obj-y := hdmi_detailed_timing.o \
	 hdmi_pixelclocks.o \
	 hdmi_api.o \
	 audio.o \
	 hdmi.o \
	 hdmi_proc.o

