/****************************************************************************
Copyright (C) 2018 Telechips Inc.
Copyright (C) 2018 Synopsys Inc.

This program is free software; you can redistribute it and/or modify it under the terms
of the GNU General Public License as published by the Free Software Foundation;
either version 2 of the License, or (at your option) any later version.

This program is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY;
without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR
PURPOSE. See the GNU General Public License for more details.

You should have received a copy of the GNU General Public License along with
this program; if not, write to the Free Software Foundation, Inc., 59 Temple Place,
Suite 330, Boston, MA 02111-1307 USA
****************************************************************************/
#ifndef INCLUDE_CORE_AUDIO_AUDIO_PACKETIZER_H_
#define INCLUDE_CORE_AUDIO_AUDIO_PACKETIZER_H_

/*****************************************************************************
 *                                                                           *
 *                         Audio Packetizer Registers                        *
 *                                                                           *
 *****************************************************************************/

//Audio Clock Regenerator N Value Register 1 For N expected values, refer to the HDMI 1
#define AUD_N1  0x0000C800
#define AUD_N1_AUDN_MASK  0x000000FF //HDMI Audio Clock Regenerator N value

//Audio Clock Regenerator N Value Register 2 For N expected values, refer to the HDMI 1
#define AUD_N2  0x0000C804
#define AUD_N2_AUDN_MASK  0x000000FF //HDMI Audio Clock Regenerator N value

//Audio Clock Regenerator N Value Register 3 For N expected values, refer to the HDMI 1
#define AUD_N3  0x0000C808
#define AUD_N3_AUDN_MASK  0x0000000F //HDMI Audio Clock Regenerator N value
#define AUD_N3_NCTS_ATOMIC_WRITE_MASK  0x00000080 //When set, the new N and CTS values are only used when aud_n1 register is written

//Audio Clock Regenerator CTS Value Register 1 For CTS expected values, refer to the HDMI 1
#define AUD_CTS1  0x0000C80C
#define AUD_CTS1_AUDCTS_MASK  0x000000FF //HDMI Audio Clock Regenerator CTS calculated value

//Audio Clock Regenerator CTS Register 2 For CTS expected values, refer to the HDMI 1
#define AUD_CTS2  0x0000C810
#define AUD_CTS2_AUDCTS_MASK  0x000000FF //HDMI Audio Clock Regenerator CTS calculated value

//Audio Clock Regenerator CTS value Register 3
#define AUD_CTS3  0x0000C814
#define AUD_CTS3_AUDCTS_MASK  0x0000000F //HDMI Audio Clock Regenerator CTS calculated value
#define AUD_CTS3_CTS_MANUAL_MASK  0x00000010 //If the CTS_manual bit equals 0b, this registers contains audCTS[19:0] generated by the Cycle time counter according to the specified timing
#define AUD_CTS3_N_SHIFT_MASK  0x000000E0 //N_shift factor configuration: N_shift | Shift Factor | Action 0 | 1 | This is the N shift factor used for the case that N' ="audN[19:0]"

//Audio Input Clock FS Factor Register
#define AUD_INPUTCLKFS  0x0000C818
#define AUD_INPUTCLKFS_IFSFACTOR_MASK  0x00000007 //Fs factor configuration: ifsfactor[2:0] | Audio Clock | Action 0 | 128xFs | If you select the Bypass SPDIF DRU unit in coreConsultant, the input audio clock (either I2S or SPDIF according to configuration) is used at the audio packetizer to calculate the CTS value and ACR packet insertion rate

#endif /* INCLUDE_CORE_AUDIO_AUDIO_PACKETIZER_H_ */
