# SPDX-License-Identifier: GPL-2.0
# Generic MAILBOX API

obj-$(CONFIG_MAILBOX)		+= mailbox.o

obj-$(CONFIG_MAILBOX_TEST)	+= mailbox-test.o

obj-$(CONFIG_ARM_MHU)	+= arm_mhu.o

obj-$(CONFIG_PLATFORM_MHU)	+= platform_mhu.o

obj-$(CONFIG_PL320_MBOX)	+= pl320-ipc.o

obj-$(CONFIG_OMAP2PLUS_MBOX)	+= omap-mailbox.o

obj-$(CONFIG_ROCKCHIP_MBOX)	+= rockchip-mailbox.o

obj-$(CONFIG_PCC)		+= pcc.o

obj-$(CONFIG_ALTERA_MBOX)	+= mailbox-altera.o

obj-$(CONFIG_BCM2835_MBOX)	+= bcm2835-mailbox.o

obj-$(CONFIG_STI_MBOX)		+= mailbox-sti.o

obj-$(CONFIG_TI_MESSAGE_MANAGER) += ti-msgmgr.o

obj-$(CONFIG_XGENE_SLIMPRO_MBOX) += mailbox-xgene-slimpro.o

obj-$(CONFIG_HI6220_MBOX)	+= hi6220-mailbox.o

obj-$(CONFIG_BCM_PDC_MBOX)	+= bcm-pdc-mailbox.o

obj-$(CONFIG_BCM_FLEXRM_MBOX)	+= bcm-flexrm-mailbox.o

obj-$(CONFIG_QCOM_APCS_IPC)	+= qcom-apcs-ipc-mailbox.o

obj-$(CONFIG_TEGRA_HSP_MBOX)	+= tegra-hsp.o

obj-$(CONFIG_TCC_MAILBOX)	+= mailbox-tcc.o

obj-$(CONFIG_TCC_MAILBOX_TEST)	+= mailbox-tcc_test.o

obj-$(CONFIG_TCC_MAILBOX_AUDIO) += tcc_mailbox_audio/

obj-$(CONFIG_TCC_SECURE_PROCESSOR)	+= tcc_sp_ipc.o

obj-$(CONFIG_TCC_MULTI_MAILBOX) += tcc_multi_mbox_dev.o

obj-$(CONFIG_TCC_MULTI_MAILBOX_AUDIO) += tcc_multi_mailbox_audio/

tcc_multi_mbox_dev-y := tcc_multi_mbox.o
