# atemsys.ko: Provides usermode access to:
#
#   - PCI configuration space
#   - Device IO memory
#   - Contiguous DMA memory
#   - Single device interrupt
#
# Copyright (c) 2009 - 2018 acontis technologies GmbH, Weingarten, Germany <info@acontis.com>
# All rights reserved.
#
# Author: K. Olbrich <k.olbrich@acontis.com>
#
# To compile and load the atemsys driver
#

obj-$(CONFIG_NET_ACONTIS_ETHCAT) += atemsys.o
