// SPDX-License-Identifier: (GPL-2.0+ OR MIT)
/*
 * Copyright (C) 2020 Telechips Inc.
 */

#ifndef __DT_TCC805X_CLKS_H__
#define __DT_TCC805X_CLKS_H__

#include "telechips,clk-common.h"

/* CLKCTRL channel index */
#define FBUS_CPU0		0	// Cortex-A72
#define FBUS_CPU1		1	// Cortex-A53
#define FBUS_CBUS		2	// CLKCTRL2
#define FBUS_CMBUS		3	// CLKCTRL3 (Cortex-M4)
#define FBUS_HSIO		6	// CLKCTRL6
#define FBUS_SMU		7	// CLKCTRL7
#define FBUS_GPU		8	// CLKCTRL8
#define FBUS_DDI		9	// CLKCTRL9
#define FBUS_G2D		10	// CLKCTRL10
#define FBUS_IO			11	// CLKCTRL11
#define FBUS_HSM		16
#define	FBUS_PCIe0		17
#define	FBUS_PCIe1		18

#define	FBUS_VBUS		19	// Dedicated Video Bus Clock
#define	FBUS_CODA		20	// Video CODA CCLK clock
#define FBUS_CHEVCDEC		21	// Video CHEVC Clock(WAVE512 CCLK)
#define FBUS_BHEVCDEC		22	// Video BHEVC Clock(WAVE512 BCLK)
#define	FBUS_CHEVCENC		23	// Video CHEVC Clock(WAVE420L CCLK)
#define	FBUS_BHEVCENC		24	// Video BHEVC Clock(WAVE420L BCLK)
#define	FBUS_MEM		25	// Dedicated Memory Bus core clock
#define	FBUS_MEM_SUB		26	// Memory Bus sub-system clock
#define	FBUS_MEM_PHY_USER	27	// LPDDR4X User clock
#define	FBUS_MEM_PHY_PERI	28	// LPDDR4X Peripheral clock
#define FBUS_MAX		29

#define CKC_REG_OFFSET(A)	((A)/4)


/* Peripheral Clocks */
/* PCLK***CTRL register : starts from 0x14000000 + 0x400*/
#define	PERI_SMU_BASE_OFFSET	0x0
#define	PERI_DDIB_BASE_OFFSET	0x100
#define	PERI_HSIOB_BASE_OFFSET	0x200
#define	PERI_IOB_BASE_OFFSET	0x300
#define	PERI_CMB_BASE_OFFSET	0x400
#define	PERI_CPUB_BASE_OFFSET	0x500
#define	PERI_EXT_BASE_OFFSET	0x600
#define PERI_HSMB_BASE_OFFSET	0x700

/* SMU Peri. */
#define	PERI_TCX		0
#define	PERI_TCT		1
#define	PERI_TCZ		2

/* DDIB Peri. */
#define	PERI_LCDTIMER		CKC_REG_OFFSET(PERI_DDIB_BASE_OFFSET)
#define	PERI_LCD0		(CKC_REG_OFFSET(PERI_DDIB_BASE_OFFSET) + 1)
#define	PERI_LCD1		(CKC_REG_OFFSET(PERI_DDIB_BASE_OFFSET) + 2)
#define	PERI_LCD2		(CKC_REG_OFFSET(PERI_DDIB_BASE_OFFSET) + 3)
#define	PERI_CPUINTERFACE0	(CKC_REG_OFFSET(PERI_DDIB_BASE_OFFSET) + 4)
#define	PERI_CPUINTERFACE1	(CKC_REG_OFFSET(PERI_DDIB_BASE_OFFSET) + 5)
#define	PERI_LCD3		(CKC_REG_OFFSET(PERI_DDIB_BASE_OFFSET) + 6)

/* HSB Peri. */
#define	PERI_GMAC		CKC_REG_OFFSET(PERI_HSIOB_BASE_OFFSET)
#define	PERI_GMAC_PTP		(CKC_REG_OFFSET(PERI_HSIOB_BASE_OFFSET) + 1)
#define	PERI_PCIE0_AUX		(CKC_REG_OFFSET(PERI_HSIOB_BASE_OFFSET) + 2)
#define	PERI_PCIE0_REF_EXT	(CKC_REG_OFFSET(PERI_HSIOB_BASE_OFFSET) + 3)
#define	PERI_PCIE0_PHY_CR_CLK	(CKC_REG_OFFSET(PERI_HSIOB_BASE_OFFSET) + 4)
#define	PERI_PCIE1_AUX		(CKC_REG_OFFSET(PERI_HSIOB_BASE_OFFSET) + 5)
#define	PERI_PCIE1_REF_EXT	(CKC_REG_OFFSET(PERI_HSIOB_BASE_OFFSET) + 6)
#define	PERI_PCIE1_PHY_CR_CLK	(CKC_REG_OFFSET(PERI_HSIOB_BASE_OFFSET) + 7)

/* IOB Peri. */
#define	PERI_RMT		CKC_REG_OFFSET(PERI_IOB_BASE_OFFSET)
#define	PERI_GPSB3		(CKC_REG_OFFSET(PERI_IOB_BASE_OFFSET) + 1)
#define	PERI_SDMMC1		(CKC_REG_OFFSET(PERI_IOB_BASE_OFFSET) + 2)
#define	PERI_SDMMC2		(CKC_REG_OFFSET(PERI_IOB_BASE_OFFSET) + 3)
#define	PERI_CEC1_CORE		(CKC_REG_OFFSET(PERI_IOB_BASE_OFFSET) + 4)
#define	PERI_MDAI0		(CKC_REG_OFFSET(PERI_IOB_BASE_OFFSET) + 5)
#define	PERI_MFLT0_DAI		(CKC_REG_OFFSET(PERI_IOB_BASE_OFFSET) + 6)
#define	PERI_MSPDIF0		(CKC_REG_OFFSET(PERI_IOB_BASE_OFFSET) + 7)
#define	PERI_SRCH0_CORE		(CKC_REG_OFFSET(PERI_IOB_BASE_OFFSET) + 8)
#define	PERI_SRCH0_FILTER	(CKC_REG_OFFSET(PERI_IOB_BASE_OFFSET) + 9)
#define	PERI_SRCH0_SPDIF	(CKC_REG_OFFSET(PERI_IOB_BASE_OFFSET) + 10)
#define	PERI_PDM		(CKC_REG_OFFSET(PERI_IOB_BASE_OFFSET) + 11)
#define	PERI_CEC1_SFR		(CKC_REG_OFFSET(PERI_IOB_BASE_OFFSET) + 12)
#define	PERI_TSADC		(CKC_REG_OFFSET(PERI_IOB_BASE_OFFSET) + 13)
#define	PERI_I2C0		(CKC_REG_OFFSET(PERI_IOB_BASE_OFFSET) + 14)
#define	PERI_I2C1		(CKC_REG_OFFSET(PERI_IOB_BASE_OFFSET) + 15)
#define	PERI_I2C2		(CKC_REG_OFFSET(PERI_IOB_BASE_OFFSET) + 16)
#define	PERI_I2C3		(CKC_REG_OFFSET(PERI_IOB_BASE_OFFSET) + 17)
#define	PERI_UART0		(CKC_REG_OFFSET(PERI_IOB_BASE_OFFSET) + 18)
#define	PERI_UART1		(CKC_REG_OFFSET(PERI_IOB_BASE_OFFSET) + 19)
#define	PERI_UART2		(CKC_REG_OFFSET(PERI_IOB_BASE_OFFSET) + 20)
#define	PERI_UART3		(CKC_REG_OFFSET(PERI_IOB_BASE_OFFSET) + 21)
#define	PERI_MDAI1		(CKC_REG_OFFSET(PERI_IOB_BASE_OFFSET) + 22)
#define	PERI_MFLT1_DAI		(CKC_REG_OFFSET(PERI_IOB_BASE_OFFSET) + 23)
#define	PERI_MSPDIF1		(CKC_REG_OFFSET(PERI_IOB_BASE_OFFSET) + 24)
#define	PERI_MDAI2		(CKC_REG_OFFSET(PERI_IOB_BASE_OFFSET) + 25)
#define	PERI_GPSB0		(CKC_REG_OFFSET(PERI_IOB_BASE_OFFSET) + 26)
#define	PERI_GPSB1		(CKC_REG_OFFSET(PERI_IOB_BASE_OFFSET) + 27)
#define	PERI_GPSB2		(CKC_REG_OFFSET(PERI_IOB_BASE_OFFSET) + 28)
#define	PERI_GPSBMS0		(CKC_REG_OFFSET(PERI_IOB_BASE_OFFSET) + 29)
#define	PERI_GPSBMS1		(CKC_REG_OFFSET(PERI_IOB_BASE_OFFSET) + 30)
#define	PERI_GPSBMS2		(CKC_REG_OFFSET(PERI_IOB_BASE_OFFSET) + 31)
#define	PERI_UART4		(CKC_REG_OFFSET(PERI_IOB_BASE_OFFSET) + 32)
#define	PERI_AUX0_INPUT		(CKC_REG_OFFSET(PERI_IOB_BASE_OFFSET) + 33)
#define	PERI_AUX1_INPUT		(CKC_REG_OFFSET(PERI_IOB_BASE_OFFSET) + 34)
#define	PERI_MFLT2_DAI		(CKC_REG_OFFSET(PERI_IOB_BASE_OFFSET) + 36)
#define	PERI_AUX0_OUTPUT	(CKC_REG_OFFSET(PERI_IOB_BASE_OFFSET) + 37)
#define	PERI_AUX1_OUTPUT	(CKC_REG_OFFSET(PERI_IOB_BASE_OFFSET) + 38)
#define	PERI_MSPDIF2		(CKC_REG_OFFSET(PERI_IOB_BASE_OFFSET) + 39)
#define	PERI_IC_TC		(CKC_REG_OFFSET(PERI_IOB_BASE_OFFSET) + 40)
#define	PERI_SRCH1_CORE		(CKC_REG_OFFSET(PERI_IOB_BASE_OFFSET) + 41)
#define	PERI_SRCH1_FILTER	(CKC_REG_OFFSET(PERI_IOB_BASE_OFFSET) + 42)
#define	PERI_SRCH1_SPDIF	(CKC_REG_OFFSET(PERI_IOB_BASE_OFFSET) + 43)
#define	PERI_SRCH2_CORE		(CKC_REG_OFFSET(PERI_IOB_BASE_OFFSET) + 44)
#define	PERI_SRCH2_FILTER	(CKC_REG_OFFSET(PERI_IOB_BASE_OFFSET) + 45)
#define	PERI_SRCH2_SPDIF	(CKC_REG_OFFSET(PERI_IOB_BASE_OFFSET) + 46)
#define	PERI_SRCH3_CORE		(CKC_REG_OFFSET(PERI_IOB_BASE_OFFSET) + 47)
#define	PERI_SRCH3_FILTER	(CKC_REG_OFFSET(PERI_IOB_BASE_OFFSET) + 48)
#define	PERI_SRCH3_SPDIF	(CKC_REG_OFFSET(PERI_IOB_BASE_OFFSET) + 49)
#define	PERI_UART5		(CKC_REG_OFFSET(PERI_IOB_BASE_OFFSET) + 50)
#define	PERI_UART6		(CKC_REG_OFFSET(PERI_IOB_BASE_OFFSET) + 51)
#define	PERI_UART7		(CKC_REG_OFFSET(PERI_IOB_BASE_OFFSET) + 52)
#define	PERI_UART8		(CKC_REG_OFFSET(PERI_IOB_BASE_OFFSET) + 53)
#define	PERI_MDAI3		(CKC_REG_OFFSET(PERI_IOB_BASE_OFFSET) + 54)
#define	PERI_MFLT3_DAI		(CKC_REG_OFFSET(PERI_IOB_BASE_OFFSET) + 55)
#define	PERI_MSPDIF3		(CKC_REG_OFFSET(PERI_IOB_BASE_OFFSET) + 56)

/* CMB Peri. */
#define	PERI_TSRX0		CKC_REG_OFFSET(PERI_CMB_BASE_OFFSET)
#define	PERI_TSRX1		(CKC_REG_OFFSET(PERI_CMB_BASE_OFFSET) + 1)
#define	PERI_TSRX2		(CKC_REG_OFFSET(PERI_CMB_BASE_OFFSET) + 2)
#define	PERI_TSRX3		(CKC_REG_OFFSET(PERI_CMB_BASE_OFFSET) + 3)
#define	PERI_TSRX4		(CKC_REG_OFFSET(PERI_CMB_BASE_OFFSET) + 4)
#define	PERI_TSRX5		(CKC_REG_OFFSET(PERI_CMB_BASE_OFFSET) + 5)
#define	PERI_TSRX6		(CKC_REG_OFFSET(PERI_CMB_BASE_OFFSET) + 6)
#define	PERI_TSRX7		(CKC_REG_OFFSET(PERI_CMB_BASE_OFFSET) + 7)
#define	PERI_TSRX8		(CKC_REG_OFFSET(PERI_CMB_BASE_OFFSET) + 8)

/* CB Peri. */
#define	PERI_CB_WDT		CKC_REG_OFFSET(PERI_CPUB_BASE_OFFSET)
#define	PERI_CB_RESERVED	(CKC_REG_OFFSET(PERI_CPUB_BASE_OFFSET) + 1)

/* External Peri. */
#define	PERI_OUT0		CKC_REG_OFFSET(PERI_EXT_BASE_OFFSET)
#define	PERI_OUT1		(CKC_REG_OFFSET(PERI_EXT_BASE_OFFSET) + 1)
#define	PERI_OUT2		(CKC_REG_OFFSET(PERI_EXT_BASE_OFFSET) + 2)
#define	PERI_OUT3		(CKC_REG_OFFSET(PERI_EXT_BASE_OFFSET) + 3)
#define	PERI_OUT4		(CKC_REG_OFFSET(PERI_EXT_BASE_OFFSET) + 4)
#define	PERI_OUT5		(CKC_REG_OFFSET(PERI_EXT_BASE_OFFSET) + 5)

/* HSMB Peri. */
#define PERI_HSMB		CKC_REG_OFFSET(PERI_HSMB_BASE_OFFSET)

// need to fix : used on 'clock_test()'
#define	PERI_MAX		114

/* I/O Bus pwdn/swreset */
#define	IOBUS_IC_TC		0
#define	IOBUS_RESERVED01	1
#define	IOBUS_GPSB6		2
#define	IOBUS_RESERVED03	3
#define	IOBUS_RESERVED04	4
#define	IOBUS_PL080		5
#define	IOBUS_ASRC		6
#define	IOBUS_DMA0		7
#define	IOBUS_DMA1		8
#define	IOBUS_DMA2		9
#define	IOBUS_DMA		10
#define	IOBUS_RESERVED11	11
#define	IOBUS_PWM		12
#define	IOBUS_RESERVED13	13
#define	IOBUS_I2C_S2		14
#define	IOBUS_RESERVED15	15
#define	IOBUS_REMOCON		16
#define	IOBUS_RESERVED17	17
#define	IOBUS_RESERVED18	18
#define	IOBUS_RESERVED19	19
#define	IOBUS_PRT		20
#define	IOBUS_ADMA0		21
#define	IOBUS_DAI0		22
#define	IOBUS_SPDIF0		23
#define	IOBUS_AUDIO0		24
#define	IOBUS_ADMA3		25
#define	IOBUS_DAI3		26
#define	IOBUS_SPDIF3		27
#define	IOBUS_AUDIO3		28
#define	IOBUS_I2C_M0		29
#define	IOBUS_I2C_M1		30
#define	IOBUS_I2C_M2		31

#define	IOBUS_I2C_M3		32	// 0
#define	IOBUS_I2C_S0		33	// 1
#define	IOBUS_I2C_S1		34	// 2
#define	IOBUS_I2C0		35	// 3
#define	IOBUS_I2C1		36	// 4
#define	IOBUS_RESERVED37	37	// 5
#define	IOBUS_RESERVED38	38	// 6
#define	IOBUS_RESERVED39	39	// 7
#define	IOBUS_RESERVED40	40	// 8
#define	IOBUS_RESERVED41	41	// 9
#define	IOBUS_RESERVED42	42	// 10
#define	IOBUS_RESERVED43	43	// 11
#define	IOBUS_RESERVED44	44	// 12
#define	IOBUS_RESERVED45	45	// 13
#define	IOBUS_RESERVED46	46	// 14
#define	IOBUS_RESERVED47	47	// 15
#define	IOBUS_RESERVED48	48	// 16
#define	IOBUS_GPSB_2		49	// 17
#define	IOBUS_RESERVED50	50	// 18
#define	IOBUS_GPSB0		51	// 19
#define	IOBUS_GPSB1		52	// 20
#define	IOBUS_GPSB2		53	// 21
#define	IOBUS_GPSB3		54	// 22
#define	IOBUS_GPSB4		55	// 23
#define	IOBUS_GPSB5		56	// 24
#define	IOBUS_GPSB		57	// 25
#define	IOBUS_RESERVED58	58	// 26
#define	IOBUS_I2C_S3		59	// 27
#define	IOBUS_I2C_M4		60	// 28
#define	IOBUS_I2C_M5		61	// 29
#define	IOBUS_I2C_M6		62	// 30
#define	IOBUS_I2C_M7		63	// 31

#define	IOBUS_UART0		64	// 0
#define	IOBUS_UART1		65	// 1
#define	IOBUS_UART2		66	// 2
#define	IOBUS_UART3		67	// 3
#define	IOBUS_UART4		68	// 4
#define	IOBUS_UART5		69	// 5
#define	IOBUS_UART6		70	// 6
#define	IOBUS_UART7		71	// 7
#define	IOBUS_UART8		72	// 8
#define	IOBUS_RESERVED73	73	// 9
#define	IOBUS_RESERVED74	74	// 10
#define	IOBUS_RESERVED75	75	// 11
#define	IOBUS_SMARTCARD4	76	// 12
#define	IOBUS_RESERVED77	77	// 13
#define	IOBUS_RESERVED78	78	// 14
#define	IOBUS_RESERVED79	79	// 15
#define	IOBUS_UDMA0		80	// 16
#define	IOBUS_UDMA1		81	// 17
#define	IOBUS_UDMA2		82	// 18
#define	IOBUS_UDMA3		83	// 19
#define	IOBUS_UART_SMARTCARD0	84	// 20
#define	IOBUS_UART_SMARTCARD1	85	// 21
#define	IOBUS_UDMA4		86	// 22
#define	IOBUS_UDMA5		87	// 23
#define	IOBUS_UDMA6		88	// 24
#define	IOBUS_UDMA7		89	// 25
#define	IOBUS_UDMA8		90	// 26
#define	IOBUS_RESERVED91	91	// 27
#define	IOBUS_RESERVED92	92	// 28
#define	IOBUS_RESERVED93	93	// 29
#define	IOBUS_RESERVED94	94	// 30
#define	IOBUS_RESERVED95	95	// 31

#define	IOBUS_ADMA1		96	// 0
#define	IOBUS_DAI1		97	// 1
#define	IOBUS_SPDIF1		98	// 2
#define	IOBUS_AUDIO1		99	// 3
#define	IOBUS_ADMA2		100	// 4
#define	IOBUS_DAI2		101	// 5
#define	IOBUS_SPDIF2		102	// 6
#define	IOBUS_AUDIO2		103	// 7
#define	IOBUS_ADMA4		104	// 8
#define	IOBUS_DAI4		105	// 9
#define	IOBUS_SPDIF4		106	// 10
#define	IOBUS_AUDIO4		107	// 11
#define	IOBUS_ADMA5		108	// 12
#define	IOBUS_DAI5		109	// 13
#define	IOBUS_SPDIF5		110	// 14
#define	IOBUS_AUDIO5		111	// 15
#define	IOBUS_ADMA6		112	// 16
#define	IOBUS_DAI6		113	// 17
#define	IOBUS_SPDIF6		114	// 18
#define	IOBUS_AUDIO6		115	// 19
#define IOBUS_ADMA7		116	// 20
#define IOBUS_DAI7		117	// 21
#define IOBUS_RESERVED118	118	// 22
#define IOBUS_AUDIO7		119	// 23

#define IOBUS_GDMA1             128     //  0
#define IOBUS_RESERVED129       129     //  1
#define IOBUS_RESERVED130       130     //  2
#define IOBUS_SDMMC1            131     //  3
#define IOBUS_SDMMC2            132     //  4
#define IOBUS_SDMMC             133     //  5
#define IOBUS_SMC               134     //  6
#define IOBUS_NFC               135     //  7
#define IOBUS_EDICFG            136     //  8
#define IOBUS_EDI               137     //  9
#define IOBUS_RTC               138     // 10

#define	IOBUS_MAX		139

/* Display Bus pwdn/swreset */
#define DDIBUS_VIOC		0
#define DDIBUS_HDMI		2
#define DDIBUS_MIPI		4
#define DDIBUS_LVDS		5
#define DDIBUS_MAX		16

/* Video Bus pwdn/swreset */
#define VIDEOBUS_JPEG           0
#define VIDEOBUS_CODA_BUS       1
#define VIDEOBUS_CODA_CORE      2
#define VIDEOBUS_HEVC_BUS       3
#define VIDEOBUS_HEVC_CORE      4
#define VIDEOBUS_HEVC_ENCODER	5
#define VIDEOBUS_MAX            6

/* High-Speed I/O Bus pwdn/swreset */
#define HSIOBUS_USB30		0
#define HSIOBUS_RESERVED01	1
#define HSIOBUS_GMAC		2
#define HSIOBUS_RESERVED03	3
#define HSIOBUS_RESERVED04	4
#define HSIOBUS_RESERVED05	5
#define HSIOBUS_USB20H		6
#define HSIOBUS_RESERVED07	7
#define HSIOBUS_RESERVED08	8
#define HSIOBUS_RESERVED09	9
#define HSIOBUS_RESERVED10	10
#define HSIOBUS_RESERVED11	11
#define HSIOBUS_RESERVED12	12
#define HSIOBUS_RESERVED13	13
#define HSIOBUS_RESERVED14	14
#define HSIOBUS_RESERVED15	15
#define HSIOBUS_RESERVED16	16
#define HSIOBUS_RESERVED17	17
#define HSIOBUS_CIPHER		18
#define HSIOBUS_DWC_OTG		19
#define HSIOBUS_RESERVED20	20
#define HSIOBUS_SECURE_WRAP	21
#define HSIOBUS_TRNG		22
#define HSIOBUS_RESERVED23	23
#define HSIOBUS_RESERVED24	24
#define HSIOBUS_RESERVED25	25
#define HSIOBUS_RESERVED26	26
#define HSIOBUS_RESERVED27	27
#define HSIOBUS_RESERVED28	28
#define HSIOBUS_RESERVED29	29
#define HSIOBUS_RESERVED30	30
#define HSIOBUS_RESERVED31	31
#define HSIOBUS_MAX		32

/* CPU Bus pwdn/swreset */
#define CPUBUS_WDT0             0
#define CPUBUS_WDT1             1
#define CPUBUS_WDT2             2
#define CPUBUS_WDT3             3
#define CPUBUS_WDT4             4
#define CPUBUS_CBUSCFG          6
#define CPUBUS_MB2DAP           7
#define CPUBUS_DAP              8
#define CPUBUS_DAPCFG           9
#define CPUBUS_DAP2MB           10
#define CPUBUS_MB2CB            11
#define CPUBUS_AHBMUX           12
#define CPUBUS_APBIF            13
#define CPUBUS_CA72H2H          14
#define CPUBUS_CA53H2H          16
#define CPUBUS_GIC0_H2X         18
#define CPUBUS_GIC0             19
#define CPUBUS_MBOX             20
#define CPUBUS_WDT5             22
#define CPUBUS_WDT6             23
#define CPUBUS_WDT7             24
#define CPUBUS_DAPNIC           25
#define CPUBUS_SJTAG            26
#define CPUBUS_GIC1_H2X         27
#define CPUBUS_GIC1             28
#define CPUBUS_MAX              29

#endif
