# TCC Audio Mailbox for T-Sound
ccflags-y += -Isound/soc/tcc/amd/include \
				-Isound/soc/tcc/amd/include/params \
				-Isound/soc/tcc/amd/include/utils

obj-$(CONFIG_TCC_MULTI_MAILBOX_AUDIO)	+= tcc_mbox_audio_utils.o tcc_multi_mailbox_audio.o
