#
# Synopsys DWC OTG Controller Drivers
#       for Telechips System-on-Chips
#

#obj-$(CONFIG_TCC_DWC_OTG_V281A) += v2.81a/
#obj-$(CONFIG_TCC_DWC_OTG_V320A) += v3.20a/
obj-$(CONFIG_TCC_DWC_OTG) += v3.20a/
