/****************************************************************************
 *
 * Copyright (C) 2018 Telechips Inc.
 *
 * This program is free software; you can redistribute it and/or modify it under the terms
 * of the GNU General Public License as published by the Free Software Foundation;
 * either version 2 of the License, or (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY;
 * without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR
 * PURPOSE. See the GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License along with
 * this program; if not, write to the Free Software Foundation, Inc., 59 Temple Place,
 * Suite 330, Boston, MA 02111-1307 USA
 ****************************************************************************/
#include <linux/module.h>
#include <sound/tcc/params/tcc_mbox_ak4601_codec_params.h>

/*****************************************************************************
 * string to int mapper for mbox transport
 * below variables are all declared at tcc_mbox_ak6401_codec_params.h to access other drivers or apps
 *****************************************************************************/
const struct codec_command_map codec_command_key_map [] = {
	CODEC_COMMAND_MAPPER(AK4601_VIRTUAL_001_MIC_INPUT_VOLUME_L, "MIC Input Volume L", AK4601_VIRTUAL_VALUE_TYPE_VOLUME),
	CODEC_COMMAND_MAPPER(AK4601_VIRTUAL_002_MIC_INPUT_VOLUME_R, "MIC Input Volume R", AK4601_VIRTUAL_VALUE_TYPE_VOLUME),
	
	CODEC_COMMAND_MAPPER(AK4601_VIRTUAL_003_ADC1_DIGITAL_VOLUME_L, "ADC1 Digital Volume L", AK4601_VIRTUAL_VALUE_TYPE_VOLUME),
	CODEC_COMMAND_MAPPER(AK4601_VIRTUAL_004_ADC1_DIGITAL_VOLUME_R, "ADC1 Digital Volume R", AK4601_VIRTUAL_VALUE_TYPE_VOLUME),
	CODEC_COMMAND_MAPPER(AK4601_VIRTUAL_005_ADC2_DIGITAL_VOLUME_L, "ADC2 Digital Volume L", AK4601_VIRTUAL_VALUE_TYPE_VOLUME),
	CODEC_COMMAND_MAPPER(AK4601_VIRTUAL_006_ADC2_DIGITAL_VOLUME_R, "ADC2 Digital Volume R", AK4601_VIRTUAL_VALUE_TYPE_VOLUME),
	CODEC_COMMAND_MAPPER(AK4601_VIRTUAL_007_ADCM_DIGITAL_VOLUME, "ADCM Digital", AK4601_VIRTUAL_VALUE_TYPE_VOLUME),
	
	CODEC_COMMAND_MAPPER(AK4601_VIRTUAL_008_DAC1_DIGITAL_VOLUME_L, "DAC1 Digital Volume L", AK4601_VIRTUAL_VALUE_TYPE_VOLUME),
	CODEC_COMMAND_MAPPER(AK4601_VIRTUAL_009_DAC1_DIGITAL_VOLUME_R, "DAC1 Digital Volume R", AK4601_VIRTUAL_VALUE_TYPE_VOLUME),
	CODEC_COMMAND_MAPPER(AK4601_VIRTUAL_010_DAC2_DIGITAL_VOLUME_L, "DAC2 Digital Volume L", AK4601_VIRTUAL_VALUE_TYPE_VOLUME),
	CODEC_COMMAND_MAPPER(AK4601_VIRTUAL_011_DAC2_DIGITAL_VOLUME_R, "DAC2 Digital Volume R", AK4601_VIRTUAL_VALUE_TYPE_VOLUME),
	CODEC_COMMAND_MAPPER(AK4601_VIRTUAL_012_DAC3_DIGITAL_VOLUME_L, "DAC3 Digital Volume L", AK4601_VIRTUAL_VALUE_TYPE_VOLUME),
	CODEC_COMMAND_MAPPER(AK4601_VIRTUAL_013_DAC3_DIGITAL_VOLUME_R, "DAC3 Digital Volume R", AK4601_VIRTUAL_VALUE_TYPE_VOLUME),
	
	CODEC_COMMAND_MAPPER(AK4601_VIRTUAL_014_ADC1_MUTE, "ADC1 Mute", AK4601_VIRTUAL_VALUE_TYPE_BOOL),
	CODEC_COMMAND_MAPPER(AK4601_VIRTUAL_015_ADC2_MUTE, "ADC2 Mute", AK4601_VIRTUAL_VALUE_TYPE_BOOL),
	CODEC_COMMAND_MAPPER(AK4601_VIRTUAL_016_ADCM_MUTE, "ADCM Mute", AK4601_VIRTUAL_VALUE_TYPE_BOOL),
	
	CODEC_COMMAND_MAPPER(AK4601_VIRTUAL_017_DAC1_MUTE, "DAC1 Mute", AK4601_VIRTUAL_VALUE_TYPE_BOOL),
	CODEC_COMMAND_MAPPER(AK4601_VIRTUAL_018_DAC2_MUTE, "DAC2 Mute", AK4601_VIRTUAL_VALUE_TYPE_BOOL),
	CODEC_COMMAND_MAPPER(AK4601_VIRTUAL_019_DAC3_MUTE, "DAC3 Mute", AK4601_VIRTUAL_VALUE_TYPE_BOOL),
	
	CODEC_COMMAND_MAPPER(AK4601_VIRTUAL_020_ADC1_INPUT_VOLTAGE_SETTING_L, "ADC1 Lch Input Voltage Setting", AK4601_VIRTUAL_VALUE_TYPE_ENUM_VOLTAGE),
	CODEC_COMMAND_MAPPER(AK4601_VIRTUAL_021_ADC1_INPUT_VOLTAGE_SETTING_R, "ADC1 Rch Input Voltage Setting", AK4601_VIRTUAL_VALUE_TYPE_ENUM_VOLTAGE),
	CODEC_COMMAND_MAPPER(AK4601_VIRTUAL_022_ADC2_INPUT_VOLTAGE_SETTING_L, "ADC2 Lch Input Voltage Setting", AK4601_VIRTUAL_VALUE_TYPE_ENUM_VOLTAGE),
	CODEC_COMMAND_MAPPER(AK4601_VIRTUAL_023_ADC2_INPUT_VOLTAGE_SETTING_R, "ADC2 Rch Input Voltage Setting", AK4601_VIRTUAL_VALUE_TYPE_ENUM_VOLTAGE),
	CODEC_COMMAND_MAPPER(AK4601_VIRTUAL_024_ADCM_INPUT_VOLTAGE_SETTING, "ADCM Input Voltage Setting", AK4601_VIRTUAL_VALUE_TYPE_ENUM_VOLTAGE),
	
	CODEC_COMMAND_MAPPER(AK4601_VIRTUAL_025_SDOUT1_OUTPUT_ENABLE, "SDOUT1 Output Enable", AK4601_VIRTUAL_VALUE_TYPE_BOOL),
	CODEC_COMMAND_MAPPER(AK4601_VIRTUAL_026_SDOUT2_OUTPUT_ENABLE, "SDOUT2 Output Enable", AK4601_VIRTUAL_VALUE_TYPE_BOOL),
	CODEC_COMMAND_MAPPER(AK4601_VIRTUAL_027_SDOUT3_OUTPUT_ENABLE, "SDOUT3 Output Enable", AK4601_VIRTUAL_VALUE_TYPE_BOOL),
	
	//a7 process belows with dapm
	CODEC_COMMAND_MAPPER(AK4601_VIRTUAL_028_SDOUT1_SOURCE_SELECTOR, "SDOUT1 Source Selector", AK4601_VIRTUAL_VALUE_TYPE_ENUM_SOURCE),
	CODEC_COMMAND_MAPPER(AK4601_VIRTUAL_029_MIXER_B_CH_1_SOURCE_SELECTOR, "MixerB Ch1 Source Selector", AK4601_VIRTUAL_VALUE_TYPE_ENUM_SOURCE),
	CODEC_COMMAND_MAPPER(AK4601_VIRTUAL_030_ADC2_MUX, "ADC2 MUX", AK4601_VIRTUAL_VALUE_TYPE_ENUM_MUX),
};
EXPORT_SYMBOL(codec_command_key_map);

//for ak4601 value key map
const struct codec_command_map codec_value_on_off_map [] = {
	CODEC_COMMAND_MAPPER(AK4601_VIRTUAL_OFF, "off", AK4601_VIRTUAL_VALUE_TYPE_BOOL),
	CODEC_COMMAND_MAPPER(AK4601_VIRTUAL_ON, "on", AK4601_VIRTUAL_VALUE_TYPE_BOOL),
};
EXPORT_SYMBOL(codec_value_on_off_map);

const struct codec_command_map codec_value_input_voltage_map [] = {
	CODEC_COMMAND_MAPPER(AK4601_VIRTUAL_2_3_Vpp, "2.3Vpp/plus or minus2.3Vpp", AK4601_VIRTUAL_VALUE_TYPE_ENUM_VOLTAGE),
	CODEC_COMMAND_MAPPER(AK4601_VIRTUAL_2_83_Vpp, "2.83Vpp/plus or minus2.83Vpp", AK4601_VIRTUAL_VALUE_TYPE_ENUM_VOLTAGE),
};
EXPORT_SYMBOL(codec_value_input_voltage_map);

const struct codec_command_map codec_value_adc_mux_map [] = {
	CODEC_COMMAND_MAPPER(AK4601_VIRTUAL_AIN2, "AIN2", AK4601_VIRTUAL_VALUE_TYPE_ENUM_MUX),
	CODEC_COMMAND_MAPPER(AK4601_VIRTUAL_AIN3, "AIN3", AK4601_VIRTUAL_VALUE_TYPE_ENUM_MUX),
	CODEC_COMMAND_MAPPER(AK4601_VIRTUAL_AIN4, "AIN4", AK4601_VIRTUAL_VALUE_TYPE_ENUM_MUX),
	CODEC_COMMAND_MAPPER(AK4601_VIRTUAL_AIN5, "AIN5", AK4601_VIRTUAL_VALUE_TYPE_ENUM_MUX),
};
EXPORT_SYMBOL(codec_value_adc_mux_map);

const struct codec_command_map codec_value_source_selector_map [] = {
	CODEC_COMMAND_MAPPER(AK4601_VIRTUAL_ALL0, "ALL0", AK4601_VIRTUAL_VALUE_TYPE_ENUM_SOURCE),
	CODEC_COMMAND_MAPPER(AK4601_VIRTUAL_SDIN1, "SDIN1", AK4601_VIRTUAL_VALUE_TYPE_ENUM_SOURCE),
	CODEC_COMMAND_MAPPER(AK4601_VIRTUAL_SDIN1B, "SDIN1B", AK4601_VIRTUAL_VALUE_TYPE_ENUM_SOURCE),
	CODEC_COMMAND_MAPPER(AK4601_VIRTUAL_SDIN1C, "SDIN1C", AK4601_VIRTUAL_VALUE_TYPE_ENUM_SOURCE),
	CODEC_COMMAND_MAPPER(AK4601_VIRTUAL_SDIN1D, "SDIN1D", AK4601_VIRTUAL_VALUE_TYPE_ENUM_SOURCE),
	CODEC_COMMAND_MAPPER(AK4601_VIRTUAL_SDIN1E, "SDIN1E", AK4601_VIRTUAL_VALUE_TYPE_ENUM_SOURCE),
	CODEC_COMMAND_MAPPER(AK4601_VIRTUAL_SDIN1F, "SDIN1F", AK4601_VIRTUAL_VALUE_TYPE_ENUM_SOURCE),
	CODEC_COMMAND_MAPPER(AK4601_VIRTUAL_SDIN1G, "SDIN1G", AK4601_VIRTUAL_VALUE_TYPE_ENUM_SOURCE),
	CODEC_COMMAND_MAPPER(AK4601_VIRTUAL_SDIN1H, "SDIN1H", AK4601_VIRTUAL_VALUE_TYPE_ENUM_SOURCE),
	CODEC_COMMAND_MAPPER(AK4601_VIRTUAL_SDIN2, "SDIN2", AK4601_VIRTUAL_VALUE_TYPE_ENUM_SOURCE),
	CODEC_COMMAND_MAPPER(AK4601_VIRTUAL_SDIN3, "SDIN3", AK4601_VIRTUAL_VALUE_TYPE_ENUM_SOURCE),
	CODEC_COMMAND_MAPPER(AK4601_VIRTUAL_VOL1, "VOL1", AK4601_VIRTUAL_VALUE_TYPE_ENUM_SOURCE),
	CODEC_COMMAND_MAPPER(AK4601_VIRTUAL_VOL2, "VOL2", AK4601_VIRTUAL_VALUE_TYPE_ENUM_SOURCE),
	CODEC_COMMAND_MAPPER(AK4601_VIRTUAL_VOL3, "VOL3", AK4601_VIRTUAL_VALUE_TYPE_ENUM_SOURCE),
	CODEC_COMMAND_MAPPER(AK4601_VIRTUAL_ADC1, "ADC1", AK4601_VIRTUAL_VALUE_TYPE_ENUM_SOURCE),
	CODEC_COMMAND_MAPPER(AK4601_VIRTUAL_ADC2, "ADC2", AK4601_VIRTUAL_VALUE_TYPE_ENUM_SOURCE),
	CODEC_COMMAND_MAPPER(AK4601_VIRTUAL_ADCM, "ADCM", AK4601_VIRTUAL_VALUE_TYPE_ENUM_SOURCE),
	CODEC_COMMAND_MAPPER(AK4601_VIRTUAL_MIXER_A, "MixerA", AK4601_VIRTUAL_VALUE_TYPE_ENUM_SOURCE),
	CODEC_COMMAND_MAPPER(AK4601_VIRTUAL_MIXER_B, "MixerB", AK4601_VIRTUAL_VALUE_TYPE_ENUM_SOURCE),
};
EXPORT_SYMBOL(codec_value_source_selector_map);

struct ak4601_codec_data g_ak4601_codec_data[] = {
	/* parameter									  value    */
    { AK4601_VIRTUAL_001_MIC_INPUT_VOLUME_L,               0                        },
    { AK4601_VIRTUAL_002_MIC_INPUT_VOLUME_R,               0                        },
    { AK4601_VIRTUAL_003_ADC1_DIGITAL_VOLUME_L,            255                      },
    { AK4601_VIRTUAL_004_ADC1_DIGITAL_VOLUME_R,            0                        },
    { AK4601_VIRTUAL_005_ADC2_DIGITAL_VOLUME_L,            207                      },
    { AK4601_VIRTUAL_006_ADC2_DIGITAL_VOLUME_R,            207                      },
    { AK4601_VIRTUAL_007_ADCM_DIGITAL_VOLUME,              207                      },
    { AK4601_VIRTUAL_008_DAC1_DIGITAL_VOLUME_L,            231                      },
    { AK4601_VIRTUAL_009_DAC1_DIGITAL_VOLUME_R,            231                      },
    { AK4601_VIRTUAL_010_DAC2_DIGITAL_VOLUME_L,            231                      },
    { AK4601_VIRTUAL_011_DAC2_DIGITAL_VOLUME_R,            231                      },
    { AK4601_VIRTUAL_012_DAC3_DIGITAL_VOLUME_L,            231                      },
    { AK4601_VIRTUAL_013_DAC3_DIGITAL_VOLUME_R,            231                      },
    { AK4601_VIRTUAL_014_ADC1_MUTE,                        AK4601_VIRTUAL_OFF       },
    { AK4601_VIRTUAL_015_ADC2_MUTE,                        AK4601_VIRTUAL_OFF       },
    { AK4601_VIRTUAL_016_ADCM_MUTE,                        AK4601_VIRTUAL_OFF       },
    { AK4601_VIRTUAL_017_DAC1_MUTE,                        AK4601_VIRTUAL_OFF       },
    { AK4601_VIRTUAL_018_DAC2_MUTE,                        AK4601_VIRTUAL_OFF       },
    { AK4601_VIRTUAL_019_DAC3_MUTE,                        AK4601_VIRTUAL_OFF       },
    { AK4601_VIRTUAL_020_ADC1_INPUT_VOLTAGE_SETTING_L,     AK4601_VIRTUAL_2_3_Vpp   },
    { AK4601_VIRTUAL_021_ADC1_INPUT_VOLTAGE_SETTING_R,     AK4601_VIRTUAL_2_3_Vpp   },
    { AK4601_VIRTUAL_022_ADC2_INPUT_VOLTAGE_SETTING_L,     AK4601_VIRTUAL_2_3_Vpp   },
    { AK4601_VIRTUAL_023_ADC2_INPUT_VOLTAGE_SETTING_R,     AK4601_VIRTUAL_2_3_Vpp   },
    { AK4601_VIRTUAL_024_ADCM_INPUT_VOLTAGE_SETTING,       AK4601_VIRTUAL_2_3_Vpp   },
    { AK4601_VIRTUAL_025_SDOUT1_OUTPUT_ENABLE,             AK4601_VIRTUAL_ON        },
    { AK4601_VIRTUAL_026_SDOUT2_OUTPUT_ENABLE,             AK4601_VIRTUAL_ON        },
    { AK4601_VIRTUAL_027_SDOUT3_OUTPUT_ENABLE,             AK4601_VIRTUAL_ON        },
    { AK4601_VIRTUAL_028_SDOUT1_SOURCE_SELECTOR,           AK4601_VIRTUAL_MIXER_B   },
    { AK4601_VIRTUAL_029_MIXER_B_CH_1_SOURCE_SELECTOR,     AK4601_VIRTUAL_ADC1      },
    { AK4601_VIRTUAL_030_ADC2_MUX,                         AK4601_VIRTUAL_AIN2      },
};
EXPORT_SYMBOL(g_ak4601_codec_data);
