/****************************************************************************
 *
 * Copyright (C) 2018 Telechips Inc.
 *
 * This program is free software; you can redistribute it and/or modify it under the terms
 * of the GNU General Public License as published by the Free Software Foundation;
 * either version 2 of the License, or (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY;
 * without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR
 * PURPOSE. See the GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License along with
 * this program; if not, write to the Free Software Foundation, Inc., 59 Temple Place,
 * Suite 330, Boston, MA 02111-1307 USA
 ****************************************************************************/
#include <linux/module.h>
#include <sound/tcc/params/tcc_mbox_am3d_effect_params.h>

/*****************************************************************************
 * am3d effect backup data structure and init value
 * below variables are all declared at tcc_mbox_am3d_effect_params.h to access other drivers or apps
 *****************************************************************************/
const struct effect_command_map effect_command_type_map [] = {
	EFFECT_COMMAND_MAPPER(ZIRENE_POWERBASS, AM3D_POWER_BASS_PARAMS_NUM, g_am3d_power_bass_data),
	EFFECT_COMMAND_MAPPER(ZIRENE_LEVELALIGNMENT, AM3D_LEVEL_ALIGNMENT_PARAMS_NUM, g_am3d_level_alignment_data),
	EFFECT_COMMAND_MAPPER(ZIRENE_TREBLEENHANCEMENT, AM3D_TREBLE_ENHANCEMENT_PARAMS_NUM, g_am3d_treble_enhancement_data),
	EFFECT_COMMAND_MAPPER(ZIRENE_SURROUND, AM3D_SURROUND_PARAMS_NUM, g_am3d_surround_data),
	EFFECT_COMMAND_MAPPER(ZIRENE_GRAPHICEQ, AM3D_GRAPHIC_EQ_PARAMS_NUM, g_am3d_graphic_eq_data),
	EFFECT_COMMAND_MAPPER(ZIRENE_TONECONTROL, AM3D_TONE_CONTROL_PARAMS_NUM, g_am3d_tone_control_data),
	EFFECT_COMMAND_MAPPER(ZIRENE_HIGHPASSFILTER, AM3D_HPF_PARAMS_NUM, g_am3d_hpf_data),
	EFFECT_COMMAND_MAPPER(ZIRENE_SWEETSPOT, AM3D_SWEET_SPOT_PARAMS_NUM, g_am3d_sweet_spot_data),
	EFFECT_COMMAND_MAPPER(ZIRENE_PARAMETRICEQ, AM3D_PARAMETRIC_EQ_PARAMS_NUM, g_am3d_parametric_eq_data),
	EFFECT_COMMAND_MAPPER(ZIRENE_PEQLOUDSPEAKER, AM3D_LOUD_PARAMETRIC_EQ_PARAMS_NUM, g_am3d_loud_parametric_eq_data),
	EFFECT_COMMAND_MAPPER(ZIRENE_LIMITER, AM3D_LIMITER_PARAMS_NUM, g_am3d_limiter_data),
	EFFECT_COMMAND_MAPPER(ZIRENE_INPUTMODULE, AM3D_INPUT_MODULE_PARAMS_NUM, g_am3d_input_module_data),
	EFFECT_COMMAND_MAPPER(ZIRENE_BALANCEFADE, AM3D_BALANCE_FADE_PARAMS_NUM, g_am3d_balance_fade_data),
};
EXPORT_SYMBOL(effect_command_type_map);

/*****************************************************************************
 * am3d effect backup data structure and init value
 * below variables are all declared at tcc_mbox_am3d_effect_params.h to access other drivers or apps
 *****************************************************************************/

struct am3d_effect_data g_am3d_power_bass_data[AM3D_POWER_BASS_PARAMS_NUM] = {
    /* parameter									  channel mask 		             value    */
	/* parameters for Front */
    {  ZIRENE_POWERBASS_ENABLE_IN_ONOFF,			  ZIRENE_PB_FRONT_LEFT_RIGHT,    AM3D_TRUE},		
    {  ZIRENE_POWERBASS_UPPER_CUTOFF_FREQUENCY_IN_HZ, ZIRENE_PB_FRONT_LEFT_RIGHT,    270}, 			    // Range: [50..300]  [Hz]
    {  ZIRENE_POWERBASS_HEADROOM_GAIN_IN_DB,		  ZIRENE_PB_FRONT_LEFT_RIGHT,    0},				// Range: [-12..0]	[dB]
    {  ZIRENE_POWERBASS_MAX_GAIN_IN_DB, 			  ZIRENE_PB_FRONT_LEFT_RIGHT,    16},				// Range: [0..24]  [dB]

    /* parameters for Rear */
    {  ZIRENE_POWERBASS_ENABLE_IN_ONOFF,			  ZIRENE_PB_BACK_LEFT_RIGHT,     AM3D_TRUE},
    {  ZIRENE_POWERBASS_UPPER_CUTOFF_FREQUENCY_IN_HZ, ZIRENE_PB_BACK_LEFT_RIGHT,     270},				// Range: [50..300]  [Hz]
    {  ZIRENE_POWERBASS_HEADROOM_GAIN_IN_DB,		  ZIRENE_PB_BACK_LEFT_RIGHT,     0},				// Range: [-12..0]	[dB]
    {  ZIRENE_POWERBASS_MAX_GAIN_IN_DB, 			  ZIRENE_PB_BACK_LEFT_RIGHT,     16},				// Range: [0..24]  [dB]

    /* parameters for Center */
    {  ZIRENE_POWERBASS_ENABLE_IN_ONOFF,			  ZIRENE_PB_FRONT_CENTER,        AM3D_TRUE},
    {  ZIRENE_POWERBASS_UPPER_CUTOFF_FREQUENCY_IN_HZ, ZIRENE_PB_FRONT_CENTER,        270},				// Range: [50..300]  [Hz]
    {  ZIRENE_POWERBASS_HEADROOM_GAIN_IN_DB,		  ZIRENE_PB_FRONT_CENTER,        0},				// Range: [-12..0]	[dB]
    {  ZIRENE_POWERBASS_MAX_GAIN_IN_DB, 			  ZIRENE_PB_FRONT_CENTER,        16},				// Range: [0..24]  [dB]
};
EXPORT_SYMBOL(g_am3d_power_bass_data);

struct am3d_effect_data g_am3d_level_alignment_data[AM3D_LEVEL_ALIGNMENT_PARAMS_NUM] = {
    /* parameter                                      channel mask               value    */
    {ZIRENE_LEVELALIGNMENT_ENABLE_IN_ONOFF,           ZIRENE_LA_ALL_CHANNELS,    AM3D_TRUE},
    {ZIRENE_LEVELALIGNMENT_MODE_IN_NA,                ZIRENE_LA_ALL_CHANNELS,    ZIRENE_LEVELALIGNMENT_MODE_MUSIC},	// Range: ZIRENE_LEVELALIGNMENT_MODE_MUSIC or ZIRENE_LEVELALIGNMENT_MODE_MOVIE
};
EXPORT_SYMBOL(g_am3d_level_alignment_data);

struct am3d_effect_data g_am3d_treble_enhancement_data[AM3D_TREBLE_ENHANCEMENT_PARAMS_NUM] = {
    /* parameter												  channel mask			      value	*/
    /* parameters for front */
    {	ZIRENE_TREBLEENHANCEMENT_ENABLE_IN_ONOFF,				  ZIRENE_TE_FRONT_LEFT_RIGHT, AM3D_TRUE},							 
    {	ZIRENE_TREBLEENHANCEMENT_HIGHPASS_CUTOFF_FREQUENCY_IN_HZ, ZIRENE_TE_FRONT_LEFT_RIGHT, 7000},								 // Range: [2000..20000]  [Hz]
    {	ZIRENE_TREBLEENHANCEMENT_SLOPE_IN_INDEX,				  ZIRENE_TE_FRONT_LEFT_RIGHT, ZIRENE_TREBLEENHANCEMENT_SLOPE_STEEP}, // Range: ZIRENE_TREBLEENHANCEMENT_SLOPE_MODERATE or ZIRENE_TREBLEENHANCEMENT_SLOPE_STEEP
    {	ZIRENE_TREBLEENHANCEMENT_HEADROOM_GAIN_IN_DB,			  ZIRENE_TE_FRONT_LEFT_RIGHT, 0},									 // Range: [-12..0]  [dB]
    {	ZIRENE_TREBLEENHANCEMENT_MAX_GAIN_IN_DB,				  ZIRENE_TE_FRONT_LEFT_RIGHT, 3},									 // Range: [0..30]	[dB]

    /* parameters for Rear */
    {	ZIRENE_TREBLEENHANCEMENT_ENABLE_IN_ONOFF,				  ZIRENE_TE_BACK_LEFT_RIGHT,  AM3D_TRUE},
    {	ZIRENE_TREBLEENHANCEMENT_HIGHPASS_CUTOFF_FREQUENCY_IN_HZ, ZIRENE_TE_BACK_LEFT_RIGHT,  6300}, 								 // Range: [2000..20000]  [Hz]
    {	ZIRENE_TREBLEENHANCEMENT_SLOPE_IN_INDEX,				  ZIRENE_TE_BACK_LEFT_RIGHT,  ZIRENE_TREBLEENHANCEMENT_SLOPE_STEEP},  // Range: ZIRENE_TREBLEENHANCEMENT_SLOPE_MODERATE or ZIRENE_TREBLEENHANCEMENT_SLOPE_STEEP
    {	ZIRENE_TREBLEENHANCEMENT_HEADROOM_GAIN_IN_DB,			  ZIRENE_TE_BACK_LEFT_RIGHT,  0},									 // Range: [-12..0]  [dB]
    {	ZIRENE_TREBLEENHANCEMENT_MAX_GAIN_IN_DB,				  ZIRENE_TE_BACK_LEFT_RIGHT,  3},									 // Range: [0..30]	[dB]

    /* parameters for Center */
    {	ZIRENE_TREBLEENHANCEMENT_ENABLE_IN_ONOFF,				  ZIRENE_TE_FRONT_CENTER,     AM3D_TRUE},
    {	ZIRENE_TREBLEENHANCEMENT_HIGHPASS_CUTOFF_FREQUENCY_IN_HZ, ZIRENE_TE_FRONT_CENTER,     6300}, 								 // Range: [2000..20000]  [Hz]
    {	ZIRENE_TREBLEENHANCEMENT_SLOPE_IN_INDEX,				  ZIRENE_TE_FRONT_CENTER,     ZIRENE_TREBLEENHANCEMENT_SLOPE_STEEP},  // Range: ZIRENE_TREBLEENHANCEMENT_SLOPE_MODERATE or ZIRENE_TREBLEENHANCEMENT_SLOPE_STEEP
    {	ZIRENE_TREBLEENHANCEMENT_HEADROOM_GAIN_IN_DB,			  ZIRENE_TE_FRONT_CENTER,     0},									 // Range: [-12..0]  [dB]
    {	ZIRENE_TREBLEENHANCEMENT_MAX_GAIN_IN_DB,				  ZIRENE_TE_FRONT_CENTER,     3},                                    // Range: [0..30]	[dB]
};
EXPORT_SYMBOL(g_am3d_treble_enhancement_data);

struct am3d_effect_data g_am3d_surround_data[AM3D_SURROUND_PARAMS_NUM] = {
    /* parameter									    channel mask 		       value    */
    {ZIRENE_SURROUND_ENABLE_IN_ONOFF,					ZIRENE_SS_ALL_CHANNELS,    AM3D_TRUE},
    {ZIRENE_SURROUND_REAR_DELAY_IN_MS,					ZIRENE_SS_ALL_CHANNELS,    26},	
};
EXPORT_SYMBOL(g_am3d_surround_data);

struct am3d_effect_data g_am3d_graphic_eq_data[AM3D_GRAPHIC_EQ_PARAMS_NUM] = {
    /* parameter									    channel mask 		       value    */
    {ZIRENE_GRAPHICEQ_ENABLE_IN_ONOFF,			       ZIRENE_GEQ_ALL_CHANNELS,    AM3D_TRUE},

    {ZIRENE_GRAPHICEQ_BAND1_GAIN_IN_DB, 	       ZIRENE_GEQ_ALL_CHANNELS,    0}, 	// Range: [-12..12]  [dB]
    {ZIRENE_GRAPHICEQ_BAND2_GAIN_IN_DB,            ZIRENE_GEQ_ALL_CHANNELS,    0}, // Range: [-12..12]  [dB]
    {ZIRENE_GRAPHICEQ_BAND3_GAIN_IN_DB,	           ZIRENE_GEQ_ALL_CHANNELS,    0}, // Range: [-12..12]  [dB]
    {ZIRENE_GRAPHICEQ_BAND4_GAIN_IN_DB,	           ZIRENE_GEQ_ALL_CHANNELS,    0}, // Range: [-12..12]  [dB]
    {ZIRENE_GRAPHICEQ_BAND5_GAIN_IN_DB,	           ZIRENE_GEQ_ALL_CHANNELS,    0},   // Range: [-12..12]  [dB]
    {ZIRENE_GRAPHICEQ_BAND6_GAIN_IN_DB,	           ZIRENE_GEQ_ALL_CHANNELS,    0},   // Range: [-12..12]  [dB]
    {ZIRENE_GRAPHICEQ_BAND7_GAIN_IN_DB,	           ZIRENE_GEQ_ALL_CHANNELS,    0},   // Range: [-12..12]  [dB]
    {ZIRENE_GRAPHICEQ_BAND8_GAIN_IN_DB,	           ZIRENE_GEQ_ALL_CHANNELS,	   0},   // Range: [-12..12]  [dB]
    {ZIRENE_GRAPHICEQ_BAND9_GAIN_IN_DB,            ZIRENE_GEQ_ALL_CHANNELS,    0},   // Range: [-12..12]  [dB]
    {ZIRENE_GRAPHICEQ_BAND10_GAIN_IN_DB,	       ZIRENE_GEQ_ALL_CHANNELS,	   0},   // Range: [-12..12]  [dB]
    {ZIRENE_GRAPHICEQ_BAND11_GAIN_IN_DB,           ZIRENE_GEQ_ALL_CHANNELS,    0},   // Range: [-12..12]  [dB]
    {ZIRENE_GRAPHICEQ_BAND12_GAIN_IN_DB,           ZIRENE_GEQ_ALL_CHANNELS,    0},   // Range: [-12..12]  [dB]
    {ZIRENE_GRAPHICEQ_BAND13_GAIN_IN_DB,           ZIRENE_GEQ_ALL_CHANNELS,	   0},    // Range: [-12..12]  [dB]

    /* headroom gain (7.33 new feature) */
    {ZIRENE_GRAPHICEQ_HEADROOM_GAIN_IN_DB, 		   ZIRENE_GEQ_ALL_CHANNELS,	   ZIRENE_GRAPHICEQ_HEADROOM_GAIN_IN_DB_DEFAULT},    // Range: [-12..0]  [dB]
};
EXPORT_SYMBOL(g_am3d_graphic_eq_data);

struct am3d_effect_data g_am3d_tone_control_data[AM3D_TONE_CONTROL_PARAMS_NUM] = {
    /* parameter									    channel mask 		       value    */
    {ZIRENE_TONECONTROL_ENABLE_IN_ONOFF, 				ZIRENE_TC_ALL_CHANNELS,	  AM3D_TRUE},

    /* bass */
    {ZIRENE_TONECONTROL_BASS_CENTER_FREQUENCY_IN_HZ,    ZIRENE_TC_ALL_CHANNELS,	  130},				// Range: [60..599]  [Hz]
    {ZIRENE_TONECONTROL_BASS_GAIN_IN_DB,                 ZIRENE_TC_ALL_CHANNELS,  0},				// Range: [-6..6]  [dB]
    {ZIRENE_TONECONTROL_BASS_QFACTOR,				    ZIRENE_TC_ALL_CHANNELS,	  724},				// Range: [410..4096]  [Q10]

    /* middle */
    {ZIRENE_TONECONTROL_MIDDLE_CENTER_FREQUENCY_IN_HZ,  ZIRENE_TC_ALL_CHANNELS,	  730},				// Range: [600..4999]  [Hz]
    {ZIRENE_TONECONTROL_MIDDLE_GAIN_IN_DB,				ZIRENE_TC_ALL_CHANNELS,	  0},				// Range: [-6..6]  [dB]
    {ZIRENE_TONECONTROL_MIDDLE_QFACTOR,					ZIRENE_TC_ALL_CHANNELS,	  678},				// Range: [410..4096]  [Q10]

	/* treble */
    {ZIRENE_TONECONTROL_TREBLE_CENTER_FREQUENCY_IN_HZ,  ZIRENE_TC_ALL_CHANNELS,	  5500},		    // Range: [5000..20000]  [Hz]
    {ZIRENE_TONECONTROL_TREBLE_GAIN_IN_DB,				ZIRENE_TC_ALL_CHANNELS,	  0},				// Range: [-6..6]  [dB]
    {ZIRENE_TONECONTROL_TREBLE_QFACTOR,					ZIRENE_TC_ALL_CHANNELS,	  724},            // Range: [410..4096]  [Q10]
};
EXPORT_SYMBOL(g_am3d_tone_control_data);

struct am3d_effect_data g_am3d_hpf_data[AM3D_HPF_PARAMS_NUM] = {
    /* parameter									        channel mask 		        value    */
    /* parameters for front */
    {  ZIRENE_HIGHPASSFILTER_ENABLE_IN_ONOFF,			   ZIRENE_HPF_FRONT_LEFT_RIGHT, AM3D_TRUE},
	{  ZIRENE_HIGHPASSFILTER_LOWER_CUTOFF_FREQUENCY_IN_HZ, ZIRENE_HPF_FRONT_LEFT_RIGHT, 50},			// Range: [15..1500]  [Hz]

	/* parameters for Rear */
	{  ZIRENE_HIGHPASSFILTER_ENABLE_IN_ONOFF,			   ZIRENE_HPF_BACK_LEFT_RIGHT, AM3D_TRUE},
	{  ZIRENE_HIGHPASSFILTER_LOWER_CUTOFF_FREQUENCY_IN_HZ, ZIRENE_HPF_BACK_LEFT_RIGHT, 50},				// Range: [15..1500]  [Hz]

	/* parameters for Center */
	{  ZIRENE_HIGHPASSFILTER_ENABLE_IN_ONOFF,			   ZIRENE_HPF_FRONT_CENTER, AM3D_TRUE},
	{  ZIRENE_HIGHPASSFILTER_LOWER_CUTOFF_FREQUENCY_IN_HZ, ZIRENE_HPF_FRONT_CENTER, 50},				// Range: [15..1500]  [Hz]
};
EXPORT_SYMBOL(g_am3d_hpf_data);

struct am3d_effect_data g_am3d_sweet_spot_data[AM3D_SWEET_SPOT_PARAMS_NUM] = {
	/* parameter									        channel mask 		        value    */
	{  ZIRENE_SWEETSPOT_ENABLE_IN_ONOFF,			   ZIRENE_SW_ALL_CHANNELS, AM3D_TRUE},

    /* front-left */
	{  ZIRENE_SWEETSPOT_DISTANCE_TO_LOUDSPEAKER_IN_CM, ZIRENE_SW_FRONT_LEFT, 100},				// Range: [1..500]  [Cm]
    {  ZIRENE_SWEETSPOT_GAIN_IN_DB,                    ZIRENE_SW_FRONT_LEFT,  0},				// Range: [-6..0]  [dB]

	/* front-right */
    {  ZIRENE_SWEETSPOT_DISTANCE_TO_LOUDSPEAKER_IN_CM, ZIRENE_SW_FRONT_RIGHT, 100},				// Range: [1..500]  [Cm]	
    {  ZIRENE_SWEETSPOT_GAIN_IN_DB,                    ZIRENE_SW_FRONT_RIGHT,  0},				// Range: [-6..0]  [dB]

	/* back-left */
    {  ZIRENE_SWEETSPOT_DISTANCE_TO_LOUDSPEAKER_IN_CM, ZIRENE_SW_BACK_LEFT, 100},				// Range: [1..500]  [Cm]
    {  ZIRENE_SWEETSPOT_GAIN_IN_DB,                    ZIRENE_SW_BACK_LEFT,  0},				// Range: [-6..0]  [dB]

	/* back-right */
    {  ZIRENE_SWEETSPOT_DISTANCE_TO_LOUDSPEAKER_IN_CM, ZIRENE_SW_BACK_RIGHT, 100},				// Range: [1..500]  [Cm]
    {  ZIRENE_SWEETSPOT_GAIN_IN_DB,                    ZIRENE_SW_BACK_RIGHT,  0},	            // Range: [-6..0]  [dB]

    /* front-center */
	{  ZIRENE_SWEETSPOT_DISTANCE_TO_LOUDSPEAKER_IN_CM, ZIRENE_SW_FRONT_CENTER, 100},			// Range: [1..500]  [Cm]
    {  ZIRENE_SWEETSPOT_GAIN_IN_DB,                    ZIRENE_SW_FRONT_CENTER,  0},				// Range: [-6..0]  [dB]

};
EXPORT_SYMBOL(g_am3d_sweet_spot_data);

struct am3d_effect_data g_am3d_parametric_eq_data[AM3D_PARAMETRIC_EQ_PARAMS_NUM] = {
    /* parameter									    channel mask 		         value    */
    {ZIRENE_PARAMETRICEQ_ENABLE_IN_ONOFF, 				ZIRENE_PEQ_ALL_CHANNELS,	   AM3D_TRUE},
    {ZIRENE_PARAMETRICEQ_HEADROOM_GAIN_IN_DB,			ZIRENE_PEQ_ALL_CHANNELS,	 -12},        // Range: [-12..0]  [dB]

    /* PARAMETRIC EQ, section #0[1ST]; type: peaking, cutoff freq: 80 Hz, gain: +3, Q: 1024 */
    {ZIRENE_PARAMETRICEQ_PARM_ID(0, ZIRENE_PARAMETRICEQ_SECTION_TYPE_IN_NA),		ZIRENE_PEQ_ALL_CHANNELS,	 ZIRENE_PARAMETRICEQ_SECTIONTYPE_PEAKING},
    {ZIRENE_PARAMETRICEQ_PARM_ID(0, ZIRENE_PARAMETRICEQ_FREQUENCY_IN_HZ),			ZIRENE_PEQ_ALL_CHANNELS,	 80},			// Range: [15..17000]  [Hz]
    {ZIRENE_PARAMETRICEQ_PARM_ID(0, ZIRENE_PARAMETRICEQ_GAIN_IN_DB),				ZIRENE_PEQ_ALL_CHANNELS,	 0},			// Range: [-12..12]  [dB]
    {ZIRENE_PARAMETRICEQ_PARM_ID(0, ZIRENE_PARAMETRICEQ_QFACTORQ10_IN_NA),			ZIRENE_PEQ_ALL_CHANNELS,	 1024},			// Range: [512..4096]  [Q10]
    {ZIRENE_PARAMETRICEQ_PARM_ID(0, ZIRENE_PARAMETRICEQ_SECTION_ENABLE_IN_ONOFF),	ZIRENE_PEQ_ALL_CHANNELS,	 AM3D_TRUE},		// Range: AM3D_TRUE OR AM3D_FALSE [ON OR OFF]

    /* PARAMETRIC EQ, section #1[2ND]; type: peaking, cutoff freq: 125 Hz, gain: +4, Q: 1024 */
    {ZIRENE_PARAMETRICEQ_PARM_ID(1, ZIRENE_PARAMETRICEQ_SECTION_TYPE_IN_NA),		ZIRENE_PEQ_ALL_CHANNELS,	 ZIRENE_PARAMETRICEQ_SECTIONTYPE_PEAKING},
    {ZIRENE_PARAMETRICEQ_PARM_ID(1, ZIRENE_PARAMETRICEQ_FREQUENCY_IN_HZ),			ZIRENE_PEQ_ALL_CHANNELS,	 125},			// Range: [15..17000]  [Hz]
    {ZIRENE_PARAMETRICEQ_PARM_ID(1, ZIRENE_PARAMETRICEQ_GAIN_IN_DB),				ZIRENE_PEQ_ALL_CHANNELS,	 0},			// Range: [-12..12]  [dB]
    {ZIRENE_PARAMETRICEQ_PARM_ID(1, ZIRENE_PARAMETRICEQ_QFACTORQ10_IN_NA),			ZIRENE_PEQ_ALL_CHANNELS,	 1024},			// Range: [512..4096]  [Q10]
    {ZIRENE_PARAMETRICEQ_PARM_ID(1, ZIRENE_PARAMETRICEQ_SECTION_ENABLE_IN_ONOFF),	ZIRENE_PEQ_ALL_CHANNELS,	 AM3D_TRUE},		// Range: AM3D_TRUE OR AM3D_FALSE [ON OR OFF]

    /* PARAMETRIC EQ, section #2[3RD]; type: peaking, cutoff freq: 200 Hz, gain: +1, Q: 1024 */
    {ZIRENE_PARAMETRICEQ_PARM_ID(2, ZIRENE_PARAMETRICEQ_SECTION_TYPE_IN_NA),		ZIRENE_PEQ_ALL_CHANNELS,	 ZIRENE_PARAMETRICEQ_SECTIONTYPE_PEAKING},
    {ZIRENE_PARAMETRICEQ_PARM_ID(2, ZIRENE_PARAMETRICEQ_FREQUENCY_IN_HZ),			ZIRENE_PEQ_ALL_CHANNELS,	 200},			// Range: [15..17000]  [Hz]
    {ZIRENE_PARAMETRICEQ_PARM_ID(2, ZIRENE_PARAMETRICEQ_GAIN_IN_DB),				ZIRENE_PEQ_ALL_CHANNELS,	 0},			// Range: [-12..12]  [dB]
    {ZIRENE_PARAMETRICEQ_PARM_ID(2, ZIRENE_PARAMETRICEQ_QFACTORQ10_IN_NA),			ZIRENE_PEQ_ALL_CHANNELS,	 1024},			// Range: [512..4096]  [Q10]
    {ZIRENE_PARAMETRICEQ_PARM_ID(2, ZIRENE_PARAMETRICEQ_SECTION_ENABLE_IN_ONOFF),	ZIRENE_PEQ_ALL_CHANNELS,	 AM3D_TRUE},		// Range: AM3D_TRUE OR AM3D_FALSE [ON OR OFF]

    /* PARAMETRIC EQ, section #3[4TH]; type: peaking, cutoff freq: 315 Hz, gain: +3, Q: 1024 */
    {ZIRENE_PARAMETRICEQ_PARM_ID(3, ZIRENE_PARAMETRICEQ_SECTION_TYPE_IN_NA),		ZIRENE_PEQ_ALL_CHANNELS,	 ZIRENE_PARAMETRICEQ_SECTIONTYPE_PEAKING},
    {ZIRENE_PARAMETRICEQ_PARM_ID(3, ZIRENE_PARAMETRICEQ_FREQUENCY_IN_HZ),			ZIRENE_PEQ_ALL_CHANNELS,	 315},			// Range: [15..17000]  [Hz]
    {ZIRENE_PARAMETRICEQ_PARM_ID(3, ZIRENE_PARAMETRICEQ_GAIN_IN_DB),				ZIRENE_PEQ_ALL_CHANNELS,	 0},			// Range: [-12..12]  [dB]
    {ZIRENE_PARAMETRICEQ_PARM_ID(3, ZIRENE_PARAMETRICEQ_QFACTORQ10_IN_NA),			ZIRENE_PEQ_ALL_CHANNELS,	 1024},			// Range: [512..4096]  [Q10]
    {ZIRENE_PARAMETRICEQ_PARM_ID(3, ZIRENE_PARAMETRICEQ_SECTION_ENABLE_IN_ONOFF),	ZIRENE_PEQ_ALL_CHANNELS,	 AM3D_TRUE},		// Range: AM3D_TRUE OR AM3D_FALSE [ON OR OFF]

    /* PARAMETRIC EQ, section #4[5TH]; type: peaking, cutoff freq: 500 Hz, gain: +3, Q: 1024 */
    {ZIRENE_PARAMETRICEQ_PARM_ID(4, ZIRENE_PARAMETRICEQ_SECTION_TYPE_IN_NA),		ZIRENE_PEQ_ALL_CHANNELS,	 ZIRENE_PARAMETRICEQ_SECTIONTYPE_PEAKING},
    {ZIRENE_PARAMETRICEQ_PARM_ID(4, ZIRENE_PARAMETRICEQ_FREQUENCY_IN_HZ),			ZIRENE_PEQ_ALL_CHANNELS,	 500},			// Range: [15..17000]  [Hz]
    {ZIRENE_PARAMETRICEQ_PARM_ID(4, ZIRENE_PARAMETRICEQ_GAIN_IN_DB),				ZIRENE_PEQ_ALL_CHANNELS,	 0},			// Range: [-12..12]  [dB]
    {ZIRENE_PARAMETRICEQ_PARM_ID(4, ZIRENE_PARAMETRICEQ_QFACTORQ10_IN_NA),			ZIRENE_PEQ_ALL_CHANNELS,	 1024},			// Range: [512..4096]  [Q10]
    {ZIRENE_PARAMETRICEQ_PARM_ID(4, ZIRENE_PARAMETRICEQ_SECTION_ENABLE_IN_ONOFF),	ZIRENE_PEQ_ALL_CHANNELS,	 AM3D_TRUE},		// Range: AM3D_TRUE OR AM3D_FALSE [ON OR OFF]

    /* PARAMETRIC EQ, section #5[6ST]; type: peaking, cutoff freq: 1000 Hz, gain: 2, Q: 512 */
    {ZIRENE_PARAMETRICEQ_PARM_ID(5, ZIRENE_PARAMETRICEQ_SECTION_TYPE_IN_NA),		ZIRENE_PEQ_ALL_CHANNELS,	 ZIRENE_PARAMETRICEQ_SECTIONTYPE_PEAKING},
    {ZIRENE_PARAMETRICEQ_PARM_ID(5, ZIRENE_PARAMETRICEQ_FREQUENCY_IN_HZ),			ZIRENE_PEQ_ALL_CHANNELS,	 1000},			// Range: [15..17000]  [Hz]
    {ZIRENE_PARAMETRICEQ_PARM_ID(5, ZIRENE_PARAMETRICEQ_GAIN_IN_DB),				ZIRENE_PEQ_ALL_CHANNELS,	 0},			// Range: [-12..12]  [dB]
    {ZIRENE_PARAMETRICEQ_PARM_ID(5, ZIRENE_PARAMETRICEQ_QFACTORQ10_IN_NA),			ZIRENE_PEQ_ALL_CHANNELS,	 512},			// Range: [512..4096]  [Q10]
    {ZIRENE_PARAMETRICEQ_PARM_ID(5, ZIRENE_PARAMETRICEQ_SECTION_ENABLE_IN_ONOFF),	ZIRENE_PEQ_ALL_CHANNELS,	 AM3D_TRUE},		// Range: AM3D_TRUE OR AM3D_FALSE [ON OR OFF]

    /* PARAMETRIC EQ, section #6[7TH]; type: peaking, cutoff freq: 1250 Hz, gain: -2, Q: 1500*/
    {ZIRENE_PARAMETRICEQ_PARM_ID(6, ZIRENE_PARAMETRICEQ_SECTION_TYPE_IN_NA),		ZIRENE_PEQ_ALL_CHANNELS,	 ZIRENE_PARAMETRICEQ_SECTIONTYPE_PEAKING},
    {ZIRENE_PARAMETRICEQ_PARM_ID(6, ZIRENE_PARAMETRICEQ_FREQUENCY_IN_HZ),			ZIRENE_PEQ_ALL_CHANNELS,	 1250},			// Range: [15..17000]  [Hz]
    {ZIRENE_PARAMETRICEQ_PARM_ID(6, ZIRENE_PARAMETRICEQ_GAIN_IN_DB),				ZIRENE_PEQ_ALL_CHANNELS,	 0},			// Range: [-12..12]  [dB]
    {ZIRENE_PARAMETRICEQ_PARM_ID(6, ZIRENE_PARAMETRICEQ_QFACTORQ10_IN_NA),			ZIRENE_PEQ_ALL_CHANNELS,	 1500},			// Range: [512..4096]  [Q10]
    {ZIRENE_PARAMETRICEQ_PARM_ID(6, ZIRENE_PARAMETRICEQ_SECTION_ENABLE_IN_ONOFF),	ZIRENE_PEQ_ALL_CHANNELS,	 AM3D_TRUE},		// Range: AM3D_TRUE OR AM3D_FALSE [ON OR OFF]

    /* PARAMETRIC EQ, section #7[8TH]; type: peaking, cutoff freq: 1625 Hz, gain: -4, Q: 1450 */
    {ZIRENE_PARAMETRICEQ_PARM_ID(7, ZIRENE_PARAMETRICEQ_SECTION_TYPE_IN_NA),		ZIRENE_PEQ_ALL_CHANNELS,	 ZIRENE_PARAMETRICEQ_SECTIONTYPE_PEAKING},
    {ZIRENE_PARAMETRICEQ_PARM_ID(7, ZIRENE_PARAMETRICEQ_FREQUENCY_IN_HZ),			ZIRENE_PEQ_ALL_CHANNELS,	 1625},			// Range: [15..17000]  [Hz]
    {ZIRENE_PARAMETRICEQ_PARM_ID(7, ZIRENE_PARAMETRICEQ_GAIN_IN_DB),				ZIRENE_PEQ_ALL_CHANNELS,	 0},			// Range: [-12..12]  [dB]
    {ZIRENE_PARAMETRICEQ_PARM_ID(7, ZIRENE_PARAMETRICEQ_QFACTORQ10_IN_NA),			ZIRENE_PEQ_ALL_CHANNELS,	 1450},			// Range: [512..4096]  [Q10]
    {ZIRENE_PARAMETRICEQ_PARM_ID(7, ZIRENE_PARAMETRICEQ_SECTION_ENABLE_IN_ONOFF),	ZIRENE_PEQ_ALL_CHANNELS,	 AM3D_TRUE},		// Range: AM3D_TRUE OR AM3D_FALSE [ON OR OFF]

    /* PARAMETRIC EQ, section #8[9TH]; type: peaking, cutoff freq: 500 Hz, gain: +3, Q: 1024 */
    {ZIRENE_PARAMETRICEQ_PARM_ID(8, ZIRENE_PARAMETRICEQ_SECTION_TYPE_IN_NA),		ZIRENE_PEQ_ALL_CHANNELS,	 ZIRENE_PARAMETRICEQ_SECTIONTYPE_PEAKING},
    {ZIRENE_PARAMETRICEQ_PARM_ID(8, ZIRENE_PARAMETRICEQ_FREQUENCY_IN_HZ),			ZIRENE_PEQ_ALL_CHANNELS,	 500},			// Range: [15..17000]  [Hz]
    {ZIRENE_PARAMETRICEQ_PARM_ID(8, ZIRENE_PARAMETRICEQ_GAIN_IN_DB),				ZIRENE_PEQ_ALL_CHANNELS,	 0},			// Range: [-12..12]  [dB]
    {ZIRENE_PARAMETRICEQ_PARM_ID(8, ZIRENE_PARAMETRICEQ_QFACTORQ10_IN_NA),			ZIRENE_PEQ_ALL_CHANNELS,	 1024},			// Range: [100..12288]  [Q10]
    {ZIRENE_PARAMETRICEQ_PARM_ID(8, ZIRENE_PARAMETRICEQ_SECTION_ENABLE_IN_ONOFF),	ZIRENE_PEQ_ALL_CHANNELS,	 AM3D_TRUE},		// Range: AM3D_TRUE OR AM3D_FALSE [ON OR OFF]

    /* PARAMETRIC EQ, section #9[10TH]; type: peaking, cutoff freq: 1250 Hz, gain: -2, Q: 1500*/
    {ZIRENE_PARAMETRICEQ_PARM_ID(9, ZIRENE_PARAMETRICEQ_SECTION_TYPE_IN_NA),		ZIRENE_PEQ_ALL_CHANNELS,	 ZIRENE_PARAMETRICEQ_SECTIONTYPE_PEAKING},
    {ZIRENE_PARAMETRICEQ_PARM_ID(9, ZIRENE_PARAMETRICEQ_FREQUENCY_IN_HZ),			ZIRENE_PEQ_ALL_CHANNELS,	 5000},			// Range: [15..17000]  [Hz]
    {ZIRENE_PARAMETRICEQ_PARM_ID(9, ZIRENE_PARAMETRICEQ_GAIN_IN_DB),				ZIRENE_PEQ_ALL_CHANNELS,	 0},			// Range: [-12..12]  [dB]
    {ZIRENE_PARAMETRICEQ_PARM_ID(9, ZIRENE_PARAMETRICEQ_QFACTORQ10_IN_NA),			ZIRENE_PEQ_ALL_CHANNELS,	 1024},			// Range: [100..12288]  [Q10]
    {ZIRENE_PARAMETRICEQ_PARM_ID(9, ZIRENE_PARAMETRICEQ_SECTION_ENABLE_IN_ONOFF),	ZIRENE_PEQ_ALL_CHANNELS,	 AM3D_TRUE},		// Range: AM3D_TRUE OR AM3D_FALSE [ON OR OFF]

    /* PARAMETRIC EQ, section #10[11TH]; type: peaking, cutoff freq: 2000 Hz, gain: +1, Q: 1024 */
    {ZIRENE_PARAMETRICEQ_PARM_ID(10, ZIRENE_PARAMETRICEQ_SECTION_TYPE_IN_NA),		ZIRENE_PEQ_ALL_CHANNELS,	 ZIRENE_PARAMETRICEQ_SECTIONTYPE_PEAKING},
    {ZIRENE_PARAMETRICEQ_PARM_ID(10, ZIRENE_PARAMETRICEQ_FREQUENCY_IN_HZ),			ZIRENE_PEQ_ALL_CHANNELS,	 9000},			// Range: [15..17000]  [Hz]
    {ZIRENE_PARAMETRICEQ_PARM_ID(10, ZIRENE_PARAMETRICEQ_GAIN_IN_DB),			    ZIRENE_PEQ_ALL_CHANNELS,	 0},			// Range: [-12..12]  [dB]
    {ZIRENE_PARAMETRICEQ_PARM_ID(10, ZIRENE_PARAMETRICEQ_QFACTORQ10_IN_NA),			ZIRENE_PEQ_ALL_CHANNELS,	 1600},			// Range: [100..12288]  [Q10]
    {ZIRENE_PARAMETRICEQ_PARM_ID(10, ZIRENE_PARAMETRICEQ_SECTION_ENABLE_IN_ONOFF),	ZIRENE_PEQ_ALL_CHANNELS,	 AM3D_TRUE},		// Range: AM3D_TRUE OR AM3D_FALSE [ON OR OFF]

    /* PARAMETRIC EQ, section #11[12TH]; type: peaking, cutoff freq: 3125 Hz, gain: +0, Q: 1024 */
    {ZIRENE_PARAMETRICEQ_PARM_ID(11, ZIRENE_PARAMETRICEQ_SECTION_TYPE_IN_NA),		ZIRENE_PEQ_ALL_CHANNELS,	 ZIRENE_PARAMETRICEQ_SECTIONTYPE_PEAKING},
    {ZIRENE_PARAMETRICEQ_PARM_ID(11, ZIRENE_PARAMETRICEQ_FREQUENCY_IN_HZ),			ZIRENE_PEQ_ALL_CHANNELS,	 2500},			// Range: [15..17000]  [Hz]
    {ZIRENE_PARAMETRICEQ_PARM_ID(11, ZIRENE_PARAMETRICEQ_GAIN_IN_DB),			    ZIRENE_PEQ_ALL_CHANNELS,	 0},			// Range: [-12..12]  [dB]
    {ZIRENE_PARAMETRICEQ_PARM_ID(11, ZIRENE_PARAMETRICEQ_QFACTORQ10_IN_NA),			ZIRENE_PEQ_ALL_CHANNELS,	 2500},			// Range: [100..12288]  [Q10]
    {ZIRENE_PARAMETRICEQ_PARM_ID(11, ZIRENE_PARAMETRICEQ_SECTION_ENABLE_IN_ONOFF),	ZIRENE_PEQ_ALL_CHANNELS,	 AM3D_TRUE},		// Range: AM3D_TRUE OR AM3D_FALSE [ON OR OFF]

    /* PARAMETRIC EQ, section #12[13TH]; type: peaking, cutoff freq: 5000 Hz, gain: +9, Q: 2500 */
    {ZIRENE_PARAMETRICEQ_PARM_ID(12, ZIRENE_PARAMETRICEQ_SECTION_TYPE_IN_NA),		ZIRENE_PEQ_ALL_CHANNELS,	 ZIRENE_PARAMETRICEQ_SECTIONTYPE_PEAKING},
    {ZIRENE_PARAMETRICEQ_PARM_ID(12, ZIRENE_PARAMETRICEQ_FREQUENCY_IN_HZ),			ZIRENE_PEQ_ALL_CHANNELS,	 13000},			// Range: [15..17000]  [Hz]
    {ZIRENE_PARAMETRICEQ_PARM_ID(12, ZIRENE_PARAMETRICEQ_GAIN_IN_DB),			    ZIRENE_PEQ_ALL_CHANNELS,	 0},			// Range: [-12..12]  [dB]
    {ZIRENE_PARAMETRICEQ_PARM_ID(12, ZIRENE_PARAMETRICEQ_QFACTORQ10_IN_NA),			ZIRENE_PEQ_ALL_CHANNELS,	 3072},			// Range: [100..12288]  [Q10]
    {ZIRENE_PARAMETRICEQ_PARM_ID(12, ZIRENE_PARAMETRICEQ_SECTION_ENABLE_IN_ONOFF),	ZIRENE_PEQ_ALL_CHANNELS,	 AM3D_TRUE},		// Range: AM3D_TRUE OR AM3D_FALSE [ON OR OFF]

    /* PARAMETRIC EQ, section #13[14TH]; type: LF Shelving, cutoff freq:  800 Hz, gain: +4 , Q: 1000 */
    {ZIRENE_PARAMETRICEQ_PARM_ID(13, ZIRENE_PARAMETRICEQ_SECTION_TYPE_IN_NA),		ZIRENE_PEQ_ALL_CHANNELS,	 ZIRENE_PARAMETRICEQ_SECTIONTYPE_LFSHELVING},
    {ZIRENE_PARAMETRICEQ_PARM_ID(13, ZIRENE_PARAMETRICEQ_FREQUENCY_IN_HZ),			ZIRENE_PEQ_ALL_CHANNELS,	 800},			// Range: [15..17000]  [Hz]	
    {ZIRENE_PARAMETRICEQ_PARM_ID(13, ZIRENE_PARAMETRICEQ_GAIN_IN_DB),			    ZIRENE_PEQ_ALL_CHANNELS,	 0},			// Range: [-12..12]  [dB]
    {ZIRENE_PARAMETRICEQ_PARM_ID(13, ZIRENE_PARAMETRICEQ_QFACTORQ10_IN_NA),	 		ZIRENE_PEQ_ALL_CHANNELS,	 1000},			// Range: [100..12288]  [Q10]
    {ZIRENE_PARAMETRICEQ_PARM_ID(13, ZIRENE_PARAMETRICEQ_SECTION_ENABLE_IN_ONOFF),	ZIRENE_PEQ_ALL_CHANNELS,	 AM3D_TRUE},		// Range: AM3D_TRUE OR AM3D_FALSE [ON OR OFF]

    /* PARAMETRIC EQ, section #14[15TH]; type: FF Shelving, cutoff freq: 2100 Hz, gain: +3, Q: 1300 */
    {ZIRENE_PARAMETRICEQ_PARM_ID(14, ZIRENE_PARAMETRICEQ_SECTION_TYPE_IN_NA),		ZIRENE_PEQ_ALL_CHANNELS,	 ZIRENE_PARAMETRICEQ_SECTIONTYPE_HFSHELVING},
    {ZIRENE_PARAMETRICEQ_PARM_ID(14, ZIRENE_PARAMETRICEQ_FREQUENCY_IN_HZ),			ZIRENE_PEQ_ALL_CHANNELS,	 2100},			// Range: [15..17000]  [Hz]
    {ZIRENE_PARAMETRICEQ_PARM_ID(14, ZIRENE_PARAMETRICEQ_GAIN_IN_DB),			    ZIRENE_PEQ_ALL_CHANNELS,	 0},			// Range: [-12..12]  [dB]
    {ZIRENE_PARAMETRICEQ_PARM_ID(14, ZIRENE_PARAMETRICEQ_QFACTORQ10_IN_NA),			ZIRENE_PEQ_ALL_CHANNELS,	 1300},			// Range: [100..12288]  [Q10]
    {ZIRENE_PARAMETRICEQ_PARM_ID(14, ZIRENE_PARAMETRICEQ_SECTION_ENABLE_IN_ONOFF),	ZIRENE_PEQ_ALL_CHANNELS,	 AM3D_TRUE}		// Range: AM3D_TRUE OR AM3D_FALSE [ON OR OFF]
};
EXPORT_SYMBOL(g_am3d_parametric_eq_data);

struct am3d_effect_data g_am3d_loud_parametric_eq_data[AM3D_LOUD_PARAMETRIC_EQ_PARAMS_NUM] = {
    /* parameter									    channel mask 		         value    */
    {ZIRENE_PEQLOUDSPEAKER_ENABLE_IN_ONOFF, 			ZIRENE_PEQLS_ALL_CHANNELS,	 AM3D_TRUE},
    {ZIRENE_PEQLOUDSPEAKER_HEADROOM_GAIN_IN_DB,			ZIRENE_PEQLS_ALL_CHANNELS,	 -2},        // Range: [-12..0]  [dB]

    /* PARAMETRIC EQ, section #0[1ST]; type: peaking, cutoff freq: 50 Hz, gain: 2, Q: 512 */
    {ZIRENE_PEQLOUDSPEAKER_PARM_ID(0, ZIRENE_PEQLOUDSPEAKER_SECTION_TYPE_IN_NA),		ZIRENE_PEQLS_ALL_CHANNELS,	 ZIRENE_PEQLOUDSPEAKER_SECTIONTYPE_PEAKING},
    {ZIRENE_PEQLOUDSPEAKER_PARM_ID(0, ZIRENE_PEQLOUDSPEAKER_FREQUENCY_IN_HZ),			ZIRENE_PEQLS_ALL_CHANNELS,	 100},			// Range: [15..17000]  [Hz]
    {ZIRENE_PEQLOUDSPEAKER_PARM_ID(0, ZIRENE_PEQLOUDSPEAKER_GAIN_IN_DB),				ZIRENE_PEQLS_ALL_CHANNELS,	 0},			// Range: [-12..12]  [dB]
    {ZIRENE_PEQLOUDSPEAKER_PARM_ID(0, ZIRENE_PEQLOUDSPEAKER_QFACTORQ10_IN_NA),			ZIRENE_PEQLS_ALL_CHANNELS,	 512},			// Range: [100..12288]  [Q10]
    {ZIRENE_PEQLOUDSPEAKER_PARM_ID(0, ZIRENE_PEQLOUDSPEAKER_SECTION_ENABLE_IN_ONOFF),	ZIRENE_PEQLS_ALL_CHANNELS,	 AM3D_TRUE},		// Range: AM3D_TRUE OR AM3D_FALSE [ON OR OFF]

    /* PARAMETRIC EQ, section #1[2ND]; type: peaking, cutoff freq: 80 Hz, gain: -4, Q: 1450 */
    {ZIRENE_PEQLOUDSPEAKER_PARM_ID(1, ZIRENE_PEQLOUDSPEAKER_SECTION_TYPE_IN_NA),		ZIRENE_PEQLS_ALL_CHANNELS,	 ZIRENE_PEQLOUDSPEAKER_SECTIONTYPE_PEAKING},
    {ZIRENE_PEQLOUDSPEAKER_PARM_ID(1, ZIRENE_PEQLOUDSPEAKER_FREQUENCY_IN_HZ),			ZIRENE_PEQLS_ALL_CHANNELS,	 300},			// Range: [15..17000]  [Hz]
    {ZIRENE_PEQLOUDSPEAKER_PARM_ID(1, ZIRENE_PEQLOUDSPEAKER_GAIN_IN_DB),				ZIRENE_PEQLS_ALL_CHANNELS,	 0},			// Range: [-12..12]  [dB]
    {ZIRENE_PEQLOUDSPEAKER_PARM_ID(1, ZIRENE_PEQLOUDSPEAKER_QFACTORQ10_IN_NA),			ZIRENE_PEQLS_ALL_CHANNELS,	 1200},			// Range: [100..12288]  [Q10]
    {ZIRENE_PEQLOUDSPEAKER_PARM_ID(1, ZIRENE_PEQLOUDSPEAKER_SECTION_ENABLE_IN_ONOFF),	ZIRENE_PEQLS_ALL_CHANNELS,	 AM3D_TRUE},		// Range: AM3D_TRUE OR AM3D_FALSE [ON OR OFF]

    /* PARAMETRIC EQ, section #2[3RD]; type: peaking, cutoff freq: 4700 Hz, gain: -4, Q: 1600 */
    {ZIRENE_PEQLOUDSPEAKER_PARM_ID(2, ZIRENE_PEQLOUDSPEAKER_SECTION_TYPE_IN_NA),		ZIRENE_PEQLS_ALL_CHANNELS,	 ZIRENE_PEQLOUDSPEAKER_SECTIONTYPE_PEAKING},
    {ZIRENE_PEQLOUDSPEAKER_PARM_ID(2, ZIRENE_PEQLOUDSPEAKER_FREQUENCY_IN_HZ),			ZIRENE_PEQLS_ALL_CHANNELS,	 500},			// Range: [15..17000]  [Hz]
    {ZIRENE_PEQLOUDSPEAKER_PARM_ID(2, ZIRENE_PEQLOUDSPEAKER_GAIN_IN_DB),				ZIRENE_PEQLS_ALL_CHANNELS,	 0},			// Range: [-12..12]  [dB]
    {ZIRENE_PEQLOUDSPEAKER_PARM_ID(2, ZIRENE_PEQLOUDSPEAKER_QFACTORQ10_IN_NA),			ZIRENE_PEQLS_ALL_CHANNELS,	 2048},			// Range: [100..12288]  [Q10]
    {ZIRENE_PEQLOUDSPEAKER_PARM_ID(2, ZIRENE_PEQLOUDSPEAKER_SECTION_ENABLE_IN_ONOFF),	ZIRENE_PEQLS_ALL_CHANNELS,	 AM3D_TRUE},		// Range: AM3D_TRUE OR AM3D_FALSE [ON OR OFF]

    /* PARAMETRIC EQ, section #3[4TH]; type: peaking, cutoff freq: 7100 Hz, gain: +3, Q: 3072 */
    {ZIRENE_PEQLOUDSPEAKER_PARM_ID(3, ZIRENE_PEQLOUDSPEAKER_SECTION_TYPE_IN_NA),		ZIRENE_PEQLS_ALL_CHANNELS,	 ZIRENE_PEQLOUDSPEAKER_SECTIONTYPE_PEAKING},
    {ZIRENE_PEQLOUDSPEAKER_PARM_ID(3, ZIRENE_PEQLOUDSPEAKER_FREQUENCY_IN_HZ),			ZIRENE_PEQLS_ALL_CHANNELS,	 700},			// Range: [15..17000]  [Hz]
    {ZIRENE_PEQLOUDSPEAKER_PARM_ID(3, ZIRENE_PEQLOUDSPEAKER_GAIN_IN_DB),				ZIRENE_PEQLS_ALL_CHANNELS,	 0},			// Range: [-12..12]  [dB]
    {ZIRENE_PEQLOUDSPEAKER_PARM_ID(3, ZIRENE_PEQLOUDSPEAKER_QFACTORQ10_IN_NA),			ZIRENE_PEQLS_ALL_CHANNELS,	 1000},			// Range: [100..12288]  [Q10]
    {ZIRENE_PEQLOUDSPEAKER_PARM_ID(3, ZIRENE_PEQLOUDSPEAKER_SECTION_ENABLE_IN_ONOFF),	ZIRENE_PEQLS_ALL_CHANNELS,	 AM3D_TRUE},		// Range: AM3D_TRUE OR AM3D_FALSE [ON OR OFF]

    /* PARAMETRIC EQ, section #4[5TH]; type: peaking, cutoff freq: 80 Hz, gain: +3, Q: 1024 */
    {ZIRENE_PEQLOUDSPEAKER_PARM_ID(4, ZIRENE_PEQLOUDSPEAKER_SECTION_TYPE_IN_NA),		ZIRENE_PEQLS_ALL_CHANNELS,	 ZIRENE_PEQLOUDSPEAKER_SECTIONTYPE_PEAKING},
    {ZIRENE_PEQLOUDSPEAKER_PARM_ID(4, ZIRENE_PEQLOUDSPEAKER_FREQUENCY_IN_HZ),			ZIRENE_PEQLS_ALL_CHANNELS,	 900},			// Range: [15..17000]  [Hz]
    {ZIRENE_PEQLOUDSPEAKER_PARM_ID(4, ZIRENE_PEQLOUDSPEAKER_GAIN_IN_DB),				ZIRENE_PEQLS_ALL_CHANNELS,	 0},			// Range: [-12..12]  [dB]
    {ZIRENE_PEQLOUDSPEAKER_PARM_ID(4, ZIRENE_PEQLOUDSPEAKER_QFACTORQ10_IN_NA),			ZIRENE_PEQLS_ALL_CHANNELS,	 1024},			// Range: [100..12288]  [Q10]
    {ZIRENE_PEQLOUDSPEAKER_PARM_ID(4, ZIRENE_PEQLOUDSPEAKER_SECTION_ENABLE_IN_ONOFF),	ZIRENE_PEQLS_ALL_CHANNELS,	 AM3D_TRUE},		// Range: AM3D_TRUE OR AM3D_FALSE [ON OR OFF]

    /* PARAMETRIC EQ, section #5[6TH]; type: peaking, cutoff freq: 125 Hz, gain: +4, Q: 1024 */
    {ZIRENE_PEQLOUDSPEAKER_PARM_ID(5, ZIRENE_PEQLOUDSPEAKER_SECTION_TYPE_IN_NA),		ZIRENE_PEQLS_ALL_CHANNELS,	 ZIRENE_PEQLOUDSPEAKER_SECTIONTYPE_PEAKING},
    {ZIRENE_PEQLOUDSPEAKER_PARM_ID(5, ZIRENE_PEQLOUDSPEAKER_FREQUENCY_IN_HZ),			ZIRENE_PEQLS_ALL_CHANNELS,	 1000},			// Range: [15..17000]  [Hz]
    {ZIRENE_PEQLOUDSPEAKER_PARM_ID(5, ZIRENE_PEQLOUDSPEAKER_GAIN_IN_DB),				ZIRENE_PEQLS_ALL_CHANNELS,	 0},			// Range: [-12..12]  [dB]
    {ZIRENE_PEQLOUDSPEAKER_PARM_ID(5, ZIRENE_PEQLOUDSPEAKER_QFACTORQ10_IN_NA),			ZIRENE_PEQLS_ALL_CHANNELS,	 1024},			// Range: [100..12288]  [Q10]
    {ZIRENE_PEQLOUDSPEAKER_PARM_ID(5, ZIRENE_PEQLOUDSPEAKER_SECTION_ENABLE_IN_ONOFF),	ZIRENE_PEQLS_ALL_CHANNELS,	 AM3D_TRUE},		// Range: AM3D_TRUE OR AM3D_FALSE [ON OR OFF]

    /* PARAMETRIC EQ, section #6[7TH]; type: peaking, cutoff freq: 200 Hz, gain: +1, Q: 1024 */
    {ZIRENE_PEQLOUDSPEAKER_PARM_ID(6, ZIRENE_PEQLOUDSPEAKER_SECTION_TYPE_IN_NA),		ZIRENE_PEQLS_ALL_CHANNELS,	 ZIRENE_PEQLOUDSPEAKER_SECTIONTYPE_PEAKING},
    {ZIRENE_PEQLOUDSPEAKER_PARM_ID(6, ZIRENE_PEQLOUDSPEAKER_FREQUENCY_IN_HZ),			ZIRENE_PEQLS_ALL_CHANNELS,	 3000},			// Range: [15..17000]  [Hz]
    {ZIRENE_PEQLOUDSPEAKER_PARM_ID(6, ZIRENE_PEQLOUDSPEAKER_GAIN_IN_DB),				ZIRENE_PEQLS_ALL_CHANNELS,	 0},			// Range: [-12..12]  [dB]
    {ZIRENE_PEQLOUDSPEAKER_PARM_ID(6, ZIRENE_PEQLOUDSPEAKER_QFACTORQ10_IN_NA),			ZIRENE_PEQLS_ALL_CHANNELS,	 1024},			// Range: [100..12288]  [Q10]
    {ZIRENE_PEQLOUDSPEAKER_PARM_ID(6, ZIRENE_PEQLOUDSPEAKER_SECTION_ENABLE_IN_ONOFF),	ZIRENE_PEQLS_ALL_CHANNELS,	 AM3D_TRUE},		// Range: AM3D_TRUE OR AM3D_FALSE [ON OR OFF]

    /* PARAMETRIC EQ, section #7[8TH]; type: peaking, cutoff freq: 315 Hz, gain: +3, Q: 1024 */
    {ZIRENE_PEQLOUDSPEAKER_PARM_ID(7, ZIRENE_PEQLOUDSPEAKER_SECTION_TYPE_IN_NA),		ZIRENE_PEQLS_ALL_CHANNELS,	 ZIRENE_PEQLOUDSPEAKER_SECTIONTYPE_PEAKING},
    {ZIRENE_PEQLOUDSPEAKER_PARM_ID(7, ZIRENE_PEQLOUDSPEAKER_FREQUENCY_IN_HZ),			ZIRENE_PEQLS_ALL_CHANNELS,	 5000},			// Range: [15..17000]  [Hz]
    {ZIRENE_PEQLOUDSPEAKER_PARM_ID(7, ZIRENE_PEQLOUDSPEAKER_GAIN_IN_DB),				ZIRENE_PEQLS_ALL_CHANNELS,	 0},			// Range: [-12..12]  [dB]
    {ZIRENE_PEQLOUDSPEAKER_PARM_ID(7, ZIRENE_PEQLOUDSPEAKER_QFACTORQ10_IN_NA),			ZIRENE_PEQLS_ALL_CHANNELS,	 1024},			// Range: [100..12288]  [Q10]
    {ZIRENE_PEQLOUDSPEAKER_PARM_ID(7, ZIRENE_PEQLOUDSPEAKER_SECTION_ENABLE_IN_ONOFF),	ZIRENE_PEQLS_ALL_CHANNELS,	 AM3D_TRUE},		// Range: AM3D_TRUE OR AM3D_FALSE [ON OR OFF]

    /* PARAMETRIC EQ, section #8[9TH]; type: peaking, cutoff freq: 500 Hz, gain: +3, Q: 1024 */
    {ZIRENE_PEQLOUDSPEAKER_PARM_ID(8, ZIRENE_PEQLOUDSPEAKER_SECTION_TYPE_IN_NA),		ZIRENE_PEQLS_ALL_CHANNELS,	 ZIRENE_PEQLOUDSPEAKER_SECTIONTYPE_PEAKING},
    {ZIRENE_PEQLOUDSPEAKER_PARM_ID(8, ZIRENE_PEQLOUDSPEAKER_FREQUENCY_IN_HZ),			ZIRENE_PEQLS_ALL_CHANNELS,	 7000},			// Range: [15..17000]  [Hz]
    {ZIRENE_PEQLOUDSPEAKER_PARM_ID(8, ZIRENE_PEQLOUDSPEAKER_GAIN_IN_DB),				ZIRENE_PEQLS_ALL_CHANNELS,	 0},			// Range: [-12..12]  [dB]
    {ZIRENE_PEQLOUDSPEAKER_PARM_ID(8, ZIRENE_PEQLOUDSPEAKER_QFACTORQ10_IN_NA),			ZIRENE_PEQLS_ALL_CHANNELS,	 1024},			// Range: [100..12288]  [Q10]
    {ZIRENE_PEQLOUDSPEAKER_PARM_ID(8, ZIRENE_PEQLOUDSPEAKER_SECTION_ENABLE_IN_ONOFF),	ZIRENE_PEQLS_ALL_CHANNELS,	 AM3D_TRUE},		// Range: AM3D_TRUE OR AM3D_FALSE [ON OR OFF]

    /* PARAMETRIC EQ, section #9[10TH]; type: peaking, cutoff freq: 1250 Hz, gain: -2, Q: 1500*/
    {ZIRENE_PEQLOUDSPEAKER_PARM_ID(9, ZIRENE_PEQLOUDSPEAKER_SECTION_TYPE_IN_NA),		ZIRENE_PEQLS_ALL_CHANNELS,	 ZIRENE_PEQLOUDSPEAKER_SECTIONTYPE_PEAKING},
    {ZIRENE_PEQLOUDSPEAKER_PARM_ID(9, ZIRENE_PEQLOUDSPEAKER_FREQUENCY_IN_HZ),			ZIRENE_PEQLS_ALL_CHANNELS,	 9000},			// Range: [15..17000]  [Hz]
    {ZIRENE_PEQLOUDSPEAKER_PARM_ID(9, ZIRENE_PEQLOUDSPEAKER_GAIN_IN_DB),				ZIRENE_PEQLS_ALL_CHANNELS,	 0},			// Range: [-12..12]  [dB]
    {ZIRENE_PEQLOUDSPEAKER_PARM_ID(9, ZIRENE_PEQLOUDSPEAKER_QFACTORQ10_IN_NA),			ZIRENE_PEQLS_ALL_CHANNELS,	 1024},			// Range: [100..12288]  [Q10]
    {ZIRENE_PEQLOUDSPEAKER_PARM_ID(9, ZIRENE_PEQLOUDSPEAKER_SECTION_ENABLE_IN_ONOFF),	ZIRENE_PEQLS_ALL_CHANNELS,	 AM3D_TRUE},		// Range: AM3D_TRUE OR AM3D_FALSE [ON OR OFF]

    /* PARAMETRIC EQ, section #10[11TH]; type: peaking, cutoff freq: 2000 Hz, gain: +1, Q: 1024 */
    {ZIRENE_PEQLOUDSPEAKER_PARM_ID(10, ZIRENE_PEQLOUDSPEAKER_SECTION_TYPE_IN_NA),		ZIRENE_PEQLS_ALL_CHANNELS,	 ZIRENE_PEQLOUDSPEAKER_SECTIONTYPE_PEAKING},
    {ZIRENE_PEQLOUDSPEAKER_PARM_ID(10, ZIRENE_PEQLOUDSPEAKER_FREQUENCY_IN_HZ),			ZIRENE_PEQLS_ALL_CHANNELS,	 10000},			// Range: [15..17000]  [Hz]
    {ZIRENE_PEQLOUDSPEAKER_PARM_ID(10, ZIRENE_PEQLOUDSPEAKER_GAIN_IN_DB),			    ZIRENE_PEQLS_ALL_CHANNELS,	 0},			// Range: [-12..12]  [dB]
    {ZIRENE_PEQLOUDSPEAKER_PARM_ID(10, ZIRENE_PEQLOUDSPEAKER_QFACTORQ10_IN_NA),			ZIRENE_PEQLS_ALL_CHANNELS,	 1024},			// Range: [100..12288]  [Q10]
    {ZIRENE_PEQLOUDSPEAKER_PARM_ID(10, ZIRENE_PEQLOUDSPEAKER_SECTION_ENABLE_IN_ONOFF),	ZIRENE_PEQLS_ALL_CHANNELS,	 AM3D_TRUE},		// Range: AM3D_TRUE OR AM3D_FALSE [ON OR OFF]

    /* PARAMETRIC EQ, section #11[12TH]; type: peaking, cutoff freq: 3125 Hz, gain: +0, Q: 1024 */
    {ZIRENE_PEQLOUDSPEAKER_PARM_ID(11, ZIRENE_PEQLOUDSPEAKER_SECTION_TYPE_IN_NA),		ZIRENE_PEQLS_ALL_CHANNELS,	 ZIRENE_PEQLOUDSPEAKER_SECTIONTYPE_PEAKING},
    {ZIRENE_PEQLOUDSPEAKER_PARM_ID(11, ZIRENE_PEQLOUDSPEAKER_FREQUENCY_IN_HZ),			ZIRENE_PEQLS_ALL_CHANNELS,	 12000},			// Range: [15..17000]  [Hz]
    {ZIRENE_PEQLOUDSPEAKER_PARM_ID(11, ZIRENE_PEQLOUDSPEAKER_GAIN_IN_DB),			    ZIRENE_PEQLS_ALL_CHANNELS,	 0},			// Range: [-12..12]  [dB]
    {ZIRENE_PEQLOUDSPEAKER_PARM_ID(11, ZIRENE_PEQLOUDSPEAKER_QFACTORQ10_IN_NA),			ZIRENE_PEQLS_ALL_CHANNELS,	 1024},			// Range: [100..12288]  [Q10]
    {ZIRENE_PEQLOUDSPEAKER_PARM_ID(11, ZIRENE_PEQLOUDSPEAKER_SECTION_ENABLE_IN_ONOFF),	ZIRENE_PEQLS_ALL_CHANNELS,	 AM3D_TRUE},		// Range: AM3D_TRUE OR AM3D_FALSE [ON OR OFF]

    /* PARAMETRIC EQ, section #12[13TH]; type: peaking, cutoff freq: 5000 Hz, gain: +9, Q: 2500 */
    {ZIRENE_PEQLOUDSPEAKER_PARM_ID(12, ZIRENE_PEQLOUDSPEAKER_SECTION_TYPE_IN_NA),		ZIRENE_PEQLS_ALL_CHANNELS,	 ZIRENE_PEQLOUDSPEAKER_SECTIONTYPE_PEAKING},
    {ZIRENE_PEQLOUDSPEAKER_PARM_ID(12, ZIRENE_PEQLOUDSPEAKER_FREQUENCY_IN_HZ),			ZIRENE_PEQLS_ALL_CHANNELS,	 13000},			// Range: [15..17000]  [Hz]
    {ZIRENE_PEQLOUDSPEAKER_PARM_ID(12, ZIRENE_PEQLOUDSPEAKER_GAIN_IN_DB),			    ZIRENE_PEQLS_ALL_CHANNELS,	 0},			// Range: [-12..12]  [dB]
    {ZIRENE_PEQLOUDSPEAKER_PARM_ID(12, ZIRENE_PEQLOUDSPEAKER_QFACTORQ10_IN_NA),			ZIRENE_PEQLS_ALL_CHANNELS,	 2500},			// Range: [100..12288]  [Q10]
    {ZIRENE_PEQLOUDSPEAKER_PARM_ID(12, ZIRENE_PEQLOUDSPEAKER_SECTION_ENABLE_IN_ONOFF),	ZIRENE_PEQLS_ALL_CHANNELS,	 AM3D_TRUE},		// Range: AM3D_TRUE OR AM3D_FALSE [ON OR OFF]

    /* PARAMETRIC EQ, section #13[14TH]; type: LF Shelving, cutoff freq:  800 Hz, gain: +4 , Q: 1000 */
    {ZIRENE_PEQLOUDSPEAKER_PARM_ID(13, ZIRENE_PEQLOUDSPEAKER_SECTION_TYPE_IN_NA),		ZIRENE_PEQLS_ALL_CHANNELS,	 ZIRENE_PEQLOUDSPEAKER_SECTIONTYPE_LFSHELVING},
    {ZIRENE_PEQLOUDSPEAKER_PARM_ID(13, ZIRENE_PEQLOUDSPEAKER_FREQUENCY_IN_HZ),			ZIRENE_PEQLS_ALL_CHANNELS,	 400},			
    {ZIRENE_PEQLOUDSPEAKER_PARM_ID(13, ZIRENE_PEQLOUDSPEAKER_GAIN_IN_DB),			    ZIRENE_PEQLS_ALL_CHANNELS,	 0},			// Range: [-12..12]  [dB]
    {ZIRENE_PEQLOUDSPEAKER_PARM_ID(13, ZIRENE_PEQLOUDSPEAKER_QFACTORQ10_IN_NA),	 		ZIRENE_PEQLS_ALL_CHANNELS,	 1000},			// Range: [100..12288]  [Q10]
    {ZIRENE_PEQLOUDSPEAKER_PARM_ID(13, ZIRENE_PEQLOUDSPEAKER_SECTION_ENABLE_IN_ONOFF),	ZIRENE_PEQLS_ALL_CHANNELS,	 AM3D_TRUE},		// Range: AM3D_TRUE OR AM3D_FALSE [ON OR OFF]

    /* PARAMETRIC EQ, section #14[15TH]; type: FF Shelving, cutoff freq: 2100 Hz, gain: +3, Q: 1300 */
    {ZIRENE_PEQLOUDSPEAKER_PARM_ID(14, ZIRENE_PEQLOUDSPEAKER_SECTION_TYPE_IN_NA),		ZIRENE_PEQLS_ALL_CHANNELS,	 ZIRENE_PEQLOUDSPEAKER_SECTIONTYPE_HFSHELVING},
    {ZIRENE_PEQLOUDSPEAKER_PARM_ID(14, ZIRENE_PEQLOUDSPEAKER_FREQUENCY_IN_HZ),			ZIRENE_PEQLS_ALL_CHANNELS,	 12000},			
    {ZIRENE_PEQLOUDSPEAKER_PARM_ID(14, ZIRENE_PEQLOUDSPEAKER_GAIN_IN_DB),			    ZIRENE_PEQLS_ALL_CHANNELS,	 0},			// Range: [-12..12]  [dB]
    {ZIRENE_PEQLOUDSPEAKER_PARM_ID(14, ZIRENE_PEQLOUDSPEAKER_QFACTORQ10_IN_NA),			ZIRENE_PEQLS_ALL_CHANNELS,	 1024},			// Range: [100..12288]  [Q10]
    {ZIRENE_PEQLOUDSPEAKER_PARM_ID(14, ZIRENE_PEQLOUDSPEAKER_SECTION_ENABLE_IN_ONOFF),	ZIRENE_PEQLS_ALL_CHANNELS,	 AM3D_TRUE}		// Range: AM3D_TRUE OR AM3D_FALSE [ON OR OFF]
};
EXPORT_SYMBOL(g_am3d_loud_parametric_eq_data);

struct am3d_effect_data g_am3d_limiter_data[AM3D_LIMITER_PARAMS_NUM] = {
	/* parameter									        channel mask 		        value    */
	/* parameters for front */
	{ZIRENE_LIMITER_ENABLE_IN_ONOFF,			ZIRENE_LIM_FRONT_LEFT_RIGHT,    AM3D_TRUE},
	{ZIRENE_LIMITER_GAIN_IN_DB,					ZIRENE_LIM_FRONT_LEFT_RIGHT,	0},	        // Range: [-15..0]  [dB]

	/* parameters for rear */
	{ZIRENE_LIMITER_ENABLE_IN_ONOFF,			ZIRENE_LIM_BACK_LEFT_RIGHT,     AM3D_TRUE},
	{ZIRENE_LIMITER_GAIN_IN_DB,					ZIRENE_LIM_BACK_LEFT_RIGHT,	    0},	        // Range: [-15..0]  [dB]

	/* parameters for center */
	{ZIRENE_LIMITER_ENABLE_IN_ONOFF,			ZIRENE_LIM_FRONT_CENTER,        AM3D_TRUE},
	{ZIRENE_LIMITER_GAIN_IN_DB,					ZIRENE_LIM_FRONT_CENTER,	    0},	        // Range: [-15..0]  [dB]
};
EXPORT_SYMBOL(g_am3d_limiter_data);

struct am3d_effect_data g_am3d_input_module_data[AM3D_INPUT_MODULE_PARAMS_NUM] = {
	/* parameter									                    channel mask 		        value    */
	{ZIRENE_INPUTMODULE_ENABLE_IN_ONOFF,								ZIRENE_INP_ALL_CHANNELS,	AM3D_TRUE},

	// Section 1 : (For Common process)
	{ZIRENE_INPUTMODULE_LOWER_CUTOFF_FREQUENCY_IN_HZ,					ZIRENE_INP_ALL_CHANNELS,	15},				// Range: [15..1500]  [Hz]
	{ZIRENE_INPUTMODULE_LOWER_CUTOFF_FREQUENCY_ENABLE_IN_ONOFF,			ZIRENE_INP_ALL_CHANNELS,	AM3D_FALSE},		// Range: AM3D_TRUE OR AM3D_FALSE [ON OR OFF]
	{ZIRENE_INPUTMODULE_HIGHER_CUTOFF_FREQUENCY_IN_HZ,					ZIRENE_INP_ALL_CHANNELS,	10000},			// Range: [40..15000]  [Hz]
	{ZIRENE_INPUTMODULE_HIGHER_CUTOFF_FREQUENCY_ENABLE_IN_ONOFF,		ZIRENE_INP_ALL_CHANNELS,	AM3D_FALSE},		// Range: AM3D_TRUE OR AM3D_FALSE [ON OR OFF]
	{ZIRENE_INPUTMODULE_GAIN_IN_DB,										ZIRENE_INP_ALL_CHANNELS,	0},				// Range: [-6..0]

	// Section 2 : (For Sub Woofer process)
    /** 
    * For the LF channel the following default values are applied
    * It is not possible to disable the highpass and lowpass filter for the LF channel
    */
	{ZIRENE_INPUTMODULE_LOWER_CUTOFF_FREQUENCY_IN_HZ,					ZIRENE_INP_LF_CHANNEL,		15},			// Range: [15..1500]  [Hz]
	{ZIRENE_INPUTMODULE_HIGHER_CUTOFF_FREQUENCY_IN_HZ,					ZIRENE_INP_LF_CHANNEL,		10000},			// Range: [40..15000]  [Hz]
	{ZIRENE_INPUTMODULE_GAIN_IN_DB,										ZIRENE_INP_LF_CHANNEL,		0}		        // Range: [-6..0]
};
EXPORT_SYMBOL(g_am3d_input_module_data);

struct am3d_effect_data g_am3d_balance_fade_data[AM3D_BALANCE_FADE_PARAMS_NUM] = {
    /* parameter								channel mask 		        value    */
	{ZIRENE_BALANCEFADE_ENABLE_IN_ONOFF,		ZIRENE_BAL_ALL_CHANNELS,	AM3D_TRUE},

	// Section one : (For Common process)
	{ZIRENE_BALANCEFADE_BALANCE_IN_PERCENT,	    ZIRENE_BAL_ALL_CHANNELS,	0},		// Range: [-100..100]  [%]
	{ZIRENE_BALANCEFADE_FADE_IN_PERCENT,		ZIRENE_BAL_ALL_CHANNELS,	0},		// Range: [-100..100]  [%]
};
EXPORT_SYMBOL(g_am3d_balance_fade_data);
