/*
 * arch/arm/mach-tegra/board-colibri_t20-pinmux.c
 *
 * Copyright (C) 2011 Toradex, Inc.
 *
 * This software is licensed under the terms of the GNU General Public
 * License version 2, as published by the Free Software Foundation, and
 * may be copied, distributed, and modified under those terms.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 */

#include <linux/gpio.h>
#include <linux/init.h>
#include <linux/kernel.h>

#include <mach/pinmux.h>

#include "board-colibri_t20.h"
#include "gpio-names.h"

#define DEFAULT_DRIVE(_name)					\
	{							\
		.pingroup = TEGRA_DRIVE_PINGROUP_##_name,	\
		.hsm = TEGRA_HSM_DISABLE,			\
		.schmitt = TEGRA_SCHMITT_ENABLE,		\
		.drive = TEGRA_DRIVE_DIV_1,			\
		.pull_down = TEGRA_PULL_31,			\
		.pull_up = TEGRA_PULL_31,			\
		.slew_rising = TEGRA_SLEW_SLOWEST,		\
		.slew_falling = TEGRA_SLEW_SLOWEST,		\
	}

#define SET_DRIVE(_name, _hsm, _schmitt, _drive, _pulldn_drive, _pullup_drive, _pulldn_slew, _pullup_slew) \
	{                                               \
		.pingroup = TEGRA_DRIVE_PINGROUP_##_name,   \
		.hsm = TEGRA_HSM_##_hsm,                    \
		.schmitt = TEGRA_SCHMITT_##_schmitt,        \
		.drive = TEGRA_DRIVE_##_drive,              \
		.pull_down = TEGRA_PULL_##_pulldn_drive,    \
		.pull_up = TEGRA_PULL_##_pullup_drive,		\
		.slew_rising = TEGRA_SLEW_##_pulldn_slew,   \
		.slew_falling = TEGRA_SLEW_##_pullup_slew,	\
	}

static __initdata struct tegra_drive_pingroup_config colibri_t20_drive_pinmux[] = {
	DEFAULT_DRIVE(SDIO1),
	DEFAULT_DRIVE(VI1),

	SET_DRIVE(AO1,		DISABLE, ENABLE, DIV_1, 31, 31, FASTEST, FASTEST),
	SET_DRIVE(AT1,		DISABLE, ENABLE, DIV_1, 31, 31, FASTEST, FASTEST),
	SET_DRIVE(DBG,		DISABLE, ENABLE, DIV_1, 31, 31, FASTEST, FASTEST),
	SET_DRIVE(DDC,		DISABLE, ENABLE, DIV_1, 31, 31, FASTEST, FASTEST),
	SET_DRIVE(VI2,		DISABLE, ENABLE, DIV_1, 31, 31, FASTEST, FASTEST),
};

static __initdata struct tegra_pingroup_config colibri_t20_pinmux[] = {
/*	tegra_pingroup		tegra_mux_func		tegra_pullupdown	tegra_tristate */
	/* nRESET_OUT, GPIO I3, I4 and I6 */
	{TEGRA_PINGROUP_ATA,	TEGRA_MUX_GMI,		TEGRA_PUPD_PULL_UP,	TEGRA_TRI_NORMAL},
	{TEGRA_PINGROUP_ATB,	TEGRA_MUX_SDIO4,	TEGRA_PUPD_NORMAL,	TEGRA_TRI_NORMAL},
	/* nCSx, AD0, AD1, AD2, AD3, AD4, AD5, AD6 and AD7, nWR, nOE, GPIO K0, K1, K2, K3 and K4 */
	{TEGRA_PINGROUP_ATC,	TEGRA_MUX_GMI,		TEGRA_PUPD_NORMAL,	TEGRA_TRI_NORMAL},
	/* AD8, AD9, AD10 and AD11 */
	{TEGRA_PINGROUP_ATD,	TEGRA_MUX_GMI,		TEGRA_PUPD_NORMAL,	TEGRA_TRI_NORMAL},
	/* AD12, AD13, AD14 and AD15 */
	{TEGRA_PINGROUP_ATE,	TEGRA_MUX_GMI,		TEGRA_PUPD_NORMAL,	TEGRA_TRI_NORMAL},
	/* WM9715L XTL_IN */
//audio sync clk could be either AC97 or PLLA_OUT0
//SYNC_CLK_DOUBLER_ENB: Enable audio sync clk doubler.
//	{TEGRA_PINGROUP_CDEV1,	TEGRA_MUX_AUDIO_SYNC,	TEGRA_PUPD_NORMAL,	TEGRA_TRI_NORMAL},
	{TEGRA_PINGROUP_CDEV1,	TEGRA_MUX_PLLA_OUT,	TEGRA_PUPD_NORMAL,	TEGRA_TRI_NORMAL},
	/* USB3340 REFCLK */
	{TEGRA_PINGROUP_CDEV2,	TEGRA_MUX_PLLP_OUT4,	TEGRA_PUPD_NORMAL,	TEGRA_TRI_NORMAL},
	{TEGRA_PINGROUP_CK32,	TEGRA_MUX_NONE,		TEGRA_PUPD_NORMAL,	TEGRA_TRI_NORMAL},
	{TEGRA_PINGROUP_CRTP,	TEGRA_MUX_CRT,		TEGRA_PUPD_NORMAL,	TEGRA_TRI_NORMAL},
	{TEGRA_PINGROUP_CSUS,	TEGRA_MUX_VI_SENSOR_CLK,TEGRA_PUPD_PULL_DOWN,	TEGRA_TRI_NORMAL},
	/* GPIO N0, N1, N2, N3 and USBC_DET */
	{TEGRA_PINGROUP_DAP1,	TEGRA_MUX_RSVD,		TEGRA_PUPD_NORMAL,	TEGRA_TRI_NORMAL},
	/* GPIO A2 and A3 */
	{TEGRA_PINGROUP_DAP2,	TEGRA_MUX_RSVD,		TEGRA_PUPD_NORMAL,	TEGRA_TRI_NORMAL},
	{TEGRA_PINGROUP_DAP3,	TEGRA_MUX_DAP3,		TEGRA_PUPD_NORMAL,	TEGRA_TRI_NORMAL},
	/* A13, A14, A15 and A16, GPIO P4, P5, P6 and P7 */
	{TEGRA_PINGROUP_DAP4,	TEGRA_MUX_GMI,		TEGRA_PUPD_NORMAL,	TEGRA_TRI_NORMAL},
	{TEGRA_PINGROUP_DDC,	TEGRA_MUX_I2C2,		TEGRA_PUPD_PULL_UP,	TEGRA_TRI_NORMAL},
	{TEGRA_PINGROUP_DDRC,	TEGRA_MUX_NONE,		TEGRA_PUPD_NORMAL,	TEGRA_TRI_NORMAL},
	/* GPIO D5 */
	{TEGRA_PINGROUP_DTA,	TEGRA_MUX_VI,		TEGRA_PUPD_PULL_DOWN,	TEGRA_TRI_NORMAL},
	/* GPIO T2 and T3 */
	{TEGRA_PINGROUP_DTB,	TEGRA_MUX_VI,		TEGRA_PUPD_PULL_DOWN,	TEGRA_TRI_NORMAL},
	{TEGRA_PINGROUP_DTC,	TEGRA_MUX_VI,		TEGRA_PUPD_PULL_DOWN,	TEGRA_TRI_NORMAL},
	/* GPIO L0, L1, L2, L3, L6 and L7 */
	{TEGRA_PINGROUP_DTD,	TEGRA_MUX_VI,		TEGRA_PUPD_PULL_DOWN,	TEGRA_TRI_NORMAL},
	/* AX88772B V_BUS, WM9715L PENDOWN, GPIO A0 and BB4 */
//	{TEGRA_PINGROUP_DTE,	TEGRA_MUX_RSVD,		TEGRA_PUPD_NORMAL,	TEGRA_TRI_NORMAL},
	{TEGRA_PINGROUP_DTE,	TEGRA_MUX_VI,		TEGRA_PUPD_NORMAL,	TEGRA_TRI_NORMAL},
	/* GPIO BB2 and BB3 */
	{TEGRA_PINGROUP_DTF,	TEGRA_MUX_I2C3,		TEGRA_PUPD_NORMAL,	TEGRA_TRI_NORMAL},
	{TEGRA_PINGROUP_GMA,	TEGRA_MUX_SDIO4,	TEGRA_PUPD_NORMAL,	TEGRA_TRI_NORMAL},
	/* MM_CD */
	{TEGRA_PINGROUP_GMB,	TEGRA_MUX_GMI_INT,	TEGRA_PUPD_NORMAL,	TEGRA_TRI_NORMAL},
	/* BT_TXD, BT_RXD, BT_CTS and BT_RTS, GPIO K7 */
	{TEGRA_PINGROUP_GMC,	TEGRA_MUX_UARTD,	TEGRA_PUPD_NORMAL,	TEGRA_TRI_NORMAL},
	{TEGRA_PINGROUP_GMD,	TEGRA_MUX_RSVD,		TEGRA_PUPD_PULL_UP,	TEGRA_TRI_NORMAL},
	/* GPIO AA4, AA5, AA6 and AA7 */
#ifndef SDHCI_8BIT
	{TEGRA_PINGROUP_GME,	TEGRA_MUX_RSVD,		TEGRA_PUPD_NORMAL,	TEGRA_TRI_NORMAL},
#else
	{TEGRA_PINGROUP_GME,	TEGRA_MUX_SDIO4,	TEGRA_PUPD_NORMAL,	TEGRA_TRI_NORMAL},
#endif
	/* A6, A7, A8, A9, A10, A11 and A12, GPIO U6 */
	{TEGRA_PINGROUP_GPU,	TEGRA_MUX_GMI,		TEGRA_PUPD_NORMAL,	TEGRA_TRI_NORMAL},
	{TEGRA_PINGROUP_GPU7,	TEGRA_MUX_RSVD,		TEGRA_PUPD_NORMAL,	TEGRA_TRI_TRISTATE},
	/* AX88772B RESET_N and EXTWAKEUP_N */
	{TEGRA_PINGROUP_GPV,	TEGRA_MUX_RSVD,		TEGRA_PUPD_NORMAL,	TEGRA_TRI_NORMAL},
	/* HDMI HOTPLUG_DETECT */
	{TEGRA_PINGROUP_HDINT,	TEGRA_MUX_HDMI,		TEGRA_PUPD_NORMAL,	TEGRA_TRI_NORMAL},
	{TEGRA_PINGROUP_I2CP,	TEGRA_MUX_I2C,		TEGRA_PUPD_NORMAL,	TEGRA_TRI_NORMAL},
	/* A0 */
	{TEGRA_PINGROUP_IRRX,	TEGRA_MUX_GMI,		TEGRA_PUPD_NORMAL,	TEGRA_TRI_NORMAL},
	/* A1 */
	{TEGRA_PINGROUP_IRTX,	TEGRA_MUX_GMI,		TEGRA_PUPD_NORMAL,	TEGRA_TRI_NORMAL},
	{TEGRA_PINGROUP_KBCA,	TEGRA_MUX_NAND,		TEGRA_PUPD_NORMAL,	TEGRA_TRI_NORMAL},
	{TEGRA_PINGROUP_KBCB,	TEGRA_MUX_NAND,		TEGRA_PUPD_NORMAL,	TEGRA_TRI_NORMAL},
	{TEGRA_PINGROUP_KBCC,	TEGRA_MUX_NAND,		TEGRA_PUPD_NORMAL,	TEGRA_TRI_NORMAL},
	{TEGRA_PINGROUP_KBCD,	TEGRA_MUX_NAND,		TEGRA_PUPD_NORMAL,	TEGRA_TRI_NORMAL},
	{TEGRA_PINGROUP_KBCE,	TEGRA_MUX_NAND,		TEGRA_PUPD_NORMAL,	TEGRA_TRI_NORMAL},
	{TEGRA_PINGROUP_KBCF,	TEGRA_MUX_NAND,		TEGRA_PUPD_NORMAL,	TEGRA_TRI_NORMAL},
	/* GPIO N4 */
	{TEGRA_PINGROUP_LCSN,	TEGRA_MUX_RSVD,		TEGRA_PUPD_NORMAL,	TEGRA_TRI_NORMAL},
	{TEGRA_PINGROUP_LD0,	TEGRA_MUX_DISPLAYA,	TEGRA_PUPD_NORMAL,	TEGRA_TRI_NORMAL},
	{TEGRA_PINGROUP_LD1,	TEGRA_MUX_DISPLAYA,	TEGRA_PUPD_NORMAL,	TEGRA_TRI_NORMAL},
	{TEGRA_PINGROUP_LD10,	TEGRA_MUX_DISPLAYA,	TEGRA_PUPD_NORMAL,	TEGRA_TRI_NORMAL},
	{TEGRA_PINGROUP_LD11,	TEGRA_MUX_DISPLAYA,	TEGRA_PUPD_NORMAL,	TEGRA_TRI_NORMAL},
	{TEGRA_PINGROUP_LD12,	TEGRA_MUX_DISPLAYA,	TEGRA_PUPD_NORMAL,	TEGRA_TRI_NORMAL},
	{TEGRA_PINGROUP_LD13,	TEGRA_MUX_DISPLAYA,	TEGRA_PUPD_NORMAL,	TEGRA_TRI_NORMAL},
	{TEGRA_PINGROUP_LD14,	TEGRA_MUX_DISPLAYA,	TEGRA_PUPD_NORMAL,	TEGRA_TRI_NORMAL},
	{TEGRA_PINGROUP_LD15,	TEGRA_MUX_DISPLAYA,	TEGRA_PUPD_NORMAL,	TEGRA_TRI_NORMAL},
	{TEGRA_PINGROUP_LD16,	TEGRA_MUX_DISPLAYA,	TEGRA_PUPD_NORMAL,	TEGRA_TRI_NORMAL},
	{TEGRA_PINGROUP_LD17,	TEGRA_MUX_DISPLAYA,	TEGRA_PUPD_NORMAL,	TEGRA_TRI_NORMAL},
	{TEGRA_PINGROUP_LD2,	TEGRA_MUX_DISPLAYA,	TEGRA_PUPD_NORMAL,	TEGRA_TRI_NORMAL},
	{TEGRA_PINGROUP_LD3,	TEGRA_MUX_DISPLAYA,	TEGRA_PUPD_NORMAL,	TEGRA_TRI_NORMAL},
	{TEGRA_PINGROUP_LD4,	TEGRA_MUX_DISPLAYA,	TEGRA_PUPD_NORMAL,	TEGRA_TRI_NORMAL},
	{TEGRA_PINGROUP_LD5,	TEGRA_MUX_DISPLAYA,	TEGRA_PUPD_NORMAL,	TEGRA_TRI_NORMAL},
	{TEGRA_PINGROUP_LD6,	TEGRA_MUX_DISPLAYA,	TEGRA_PUPD_NORMAL,	TEGRA_TRI_NORMAL},
	{TEGRA_PINGROUP_LD7,	TEGRA_MUX_DISPLAYA,	TEGRA_PUPD_NORMAL,	TEGRA_TRI_NORMAL},
	{TEGRA_PINGROUP_LD8,	TEGRA_MUX_DISPLAYA,	TEGRA_PUPD_NORMAL,	TEGRA_TRI_NORMAL},
	{TEGRA_PINGROUP_LD9,	TEGRA_MUX_DISPLAYA,	TEGRA_PUPD_NORMAL,	TEGRA_TRI_NORMAL},
	/* GPIO N6 */
	{TEGRA_PINGROUP_LDC,	TEGRA_MUX_RSVD,		TEGRA_PUPD_NORMAL,	TEGRA_TRI_NORMAL},
	{TEGRA_PINGROUP_LDI,	TEGRA_MUX_RSVD,		TEGRA_PUPD_NORMAL,	TEGRA_TRI_NORMAL},
	{TEGRA_PINGROUP_LHP0,	TEGRA_MUX_RSVD,		TEGRA_PUPD_NORMAL,	TEGRA_TRI_NORMAL},
	{TEGRA_PINGROUP_LHP1,	TEGRA_MUX_RSVD,		TEGRA_PUPD_NORMAL,	TEGRA_TRI_NORMAL},
	{TEGRA_PINGROUP_LHP2,	TEGRA_MUX_RSVD,		TEGRA_PUPD_NORMAL,	TEGRA_TRI_NORMAL},
	{TEGRA_PINGROUP_LHS,	TEGRA_MUX_DISPLAYA,	TEGRA_PUPD_NORMAL,	TEGRA_TRI_NORMAL},
	/* Multiplexed RDnWR */
	{TEGRA_PINGROUP_LM0,	TEGRA_MUX_RSVD,		TEGRA_PUPD_NORMAL,	TEGRA_TRI_TRISTATE},
	{TEGRA_PINGROUP_LM1,	TEGRA_MUX_RSVD,		TEGRA_PUPD_NORMAL,	TEGRA_TRI_TRISTATE},
	{TEGRA_PINGROUP_LPP,	TEGRA_MUX_RSVD,		TEGRA_PUPD_NORMAL,	TEGRA_TRI_NORMAL},
	/* GPIO B2 */
//	{TEGRA_PINGROUP_LPW0,	TEGRA_MUX_RSVD,		TEGRA_PUPD_NORMAL,	TEGRA_TRI_NORMAL},
	{TEGRA_PINGROUP_LPW0,	TEGRA_MUX_DISPLAYA,	TEGRA_PUPD_NORMAL,	TEGRA_TRI_NORMAL},
	{TEGRA_PINGROUP_LPW1,	TEGRA_MUX_RSVD,		TEGRA_PUPD_NORMAL,	TEGRA_TRI_TRISTATE},
//	{TEGRA_PINGROUP_LPW2,	TEGRA_MUX_RSVD,		TEGRA_PUPD_NORMAL,	TEGRA_TRI_TRISTATE},
	{TEGRA_PINGROUP_LPW2,	TEGRA_MUX_DISPLAYA,	TEGRA_PUPD_NORMAL,	TEGRA_TRI_TRISTATE},
	{TEGRA_PINGROUP_LSC0,	TEGRA_MUX_DISPLAYA,	TEGRA_PUPD_NORMAL,	TEGRA_TRI_NORMAL},
	/* Multiplexed nPWE */
//	{TEGRA_PINGROUP_LSC1,	TEGRA_MUX_RSVD,		TEGRA_PUPD_NORMAL,	TEGRA_TRI_TRISTATE},
	{TEGRA_PINGROUP_LSC1,	TEGRA_MUX_DISPLAYA,	TEGRA_PUPD_NORMAL,	TEGRA_TRI_TRISTATE},
	/* GPIO Z4 */
//	{TEGRA_PINGROUP_LSCK,	TEGRA_MUX_RSVD,		TEGRA_PUPD_NORMAL,	TEGRA_TRI_NORMAL},
	{TEGRA_PINGROUP_LSCK,	TEGRA_MUX_DISPLAYA,	TEGRA_PUPD_NORMAL,	TEGRA_TRI_NORMAL},
	/* GPIO N5 */
//	{TEGRA_PINGROUP_LSDA,	TEGRA_MUX_RSVD,		TEGRA_PUPD_NORMAL,	TEGRA_TRI_NORMAL},
	{TEGRA_PINGROUP_LSDA,	TEGRA_MUX_DISPLAYA,	TEGRA_PUPD_NORMAL,	TEGRA_TRI_NORMAL},
	/* GPIO Z2 */
	{TEGRA_PINGROUP_LSDI,	TEGRA_MUX_RSVD,		TEGRA_PUPD_NORMAL,	TEGRA_TRI_NORMAL},
	{TEGRA_PINGROUP_LSPI,	TEGRA_MUX_DISPLAYA,	TEGRA_PUPD_NORMAL,	TEGRA_TRI_NORMAL},
	{TEGRA_PINGROUP_LVP0,	TEGRA_MUX_RSVD,		TEGRA_PUPD_NORMAL,	TEGRA_TRI_TRISTATE},
	{TEGRA_PINGROUP_LVP1,	TEGRA_MUX_RSVD,		TEGRA_PUPD_NORMAL,	TEGRA_TRI_NORMAL},
	{TEGRA_PINGROUP_LVS,	TEGRA_MUX_DISPLAYA,	TEGRA_PUPD_NORMAL,	TEGRA_TRI_NORMAL},
	{TEGRA_PINGROUP_OWC,	TEGRA_MUX_OWR,		TEGRA_PUPD_PULL_UP,	TEGRA_TRI_NORMAL},
//Todo: Tri-state for now due to 5K/s spurious interrupts.
//	{TEGRA_PINGROUP_PMC,	TEGRA_MUX_PWR_ON,	TEGRA_PUPD_NORMAL,	TEGRA_TRI_NORMAL},
	{TEGRA_PINGROUP_PMC,	TEGRA_MUX_PWR_ON,	TEGRA_PUPD_NORMAL,	TEGRA_TRI_TRISTATE},
	{TEGRA_PINGROUP_PMCA,	TEGRA_MUX_NONE,		TEGRA_PUPD_NORMAL,	TEGRA_TRI_NORMAL},
	{TEGRA_PINGROUP_PMCB,	TEGRA_MUX_NONE,		TEGRA_PUPD_NORMAL,	TEGRA_TRI_NORMAL},
	{TEGRA_PINGROUP_PMCC,	TEGRA_MUX_NONE,		TEGRA_PUPD_NORMAL,	TEGRA_TRI_NORMAL},
	{TEGRA_PINGROUP_PMCD,	TEGRA_MUX_NONE,		TEGRA_PUPD_NORMAL,	TEGRA_TRI_NORMAL},
//Todo: What exactly is PMCE? Why would it need pull-up?
//	{TEGRA_PINGROUP_PMCE,	TEGRA_MUX_NONE,		TEGRA_PUPD_NORMAL,	TEGRA_TRI_NORMAL},
	{TEGRA_PINGROUP_PMCE,	TEGRA_MUX_NONE,		TEGRA_PUPD_PULL_UP,	TEGRA_TRI_NORMAL},
	/* Not tri-stating RDnWR, nPWE */
	{TEGRA_PINGROUP_PTA,	TEGRA_MUX_RSVD,		TEGRA_PUPD_PULL_DOWN,	TEGRA_TRI_NORMAL},
	{TEGRA_PINGROUP_RM,	TEGRA_MUX_I2C,		TEGRA_PUPD_NORMAL,	TEGRA_TRI_NORMAL},
	/* PWM3 */
#ifdef CAMERA_INTERFACE
	/* PWM<D> multiplexed with CIF_DD<6> */
	{TEGRA_PINGROUP_SDB,	TEGRA_MUX_PWM,		TEGRA_PUPD_NORMAL,	TEGRA_TRI_TRISTATE},
#else
	{TEGRA_PINGROUP_SDB,	TEGRA_MUX_PWM,		TEGRA_PUPD_NORMAL,	TEGRA_TRI_NORMAL},
#endif
	/* GPIO B6 and B7, PWM0 and PWM1 */
#ifdef CAMERA_INTERFACE
	/* PWM<A> multiplexed with CIF_DD<7> */
	{TEGRA_PINGROUP_SDC,	TEGRA_MUX_PWM,		TEGRA_PUPD_NORMAL,	TEGRA_TRI_TRISTATE},
#else
	{TEGRA_PINGROUP_SDC,	TEGRA_MUX_PWM,		TEGRA_PUPD_NORMAL,	TEGRA_TRI_NORMAL},
#endif
	/* PWM2 */
	{TEGRA_PINGROUP_SDD,	TEGRA_MUX_PWM,		TEGRA_PUPD_NORMAL,	TEGRA_TRI_NORMAL},
	{TEGRA_PINGROUP_SDIO1,	TEGRA_MUX_UARTA,	TEGRA_PUPD_PULL_UP,	TEGRA_TRI_NORMAL},

	/* SPI4 */
	{TEGRA_PINGROUP_SLXA,	TEGRA_MUX_SPI4,		TEGRA_PUPD_NORMAL,	TEGRA_TRI_NORMAL},
	{TEGRA_PINGROUP_SLXC,	TEGRA_MUX_SPI4,		TEGRA_PUPD_NORMAL,	TEGRA_TRI_NORMAL},
	{TEGRA_PINGROUP_SLXD,	TEGRA_MUX_SPI4,		TEGRA_PUPD_NORMAL,	TEGRA_TRI_NORMAL},
	{TEGRA_PINGROUP_SLXK,	TEGRA_MUX_SPI4,		TEGRA_PUPD_NORMAL,	TEGRA_TRI_NORMAL},

	/* GPIO K6 multiplexed ACC1_DETECT */
	{TEGRA_PINGROUP_SPDI,	TEGRA_MUX_RSVD,		TEGRA_PUPD_NORMAL,	TEGRA_TRI_TRISTATE},
	/* GPIO K5 multiplexed USB1_VBUS */
	{TEGRA_PINGROUP_SPDO,	TEGRA_MUX_RSVD,		TEGRA_PUPD_NORMAL,	TEGRA_TRI_TRISTATE},

	/* X0, X1, X2, X3, X4, X5, X6 and X7 */
//	{TEGRA_PINGROUP_SPIA,	TEGRA_MUX_RSVD,		TEGRA_PUPD_NORMAL,	TEGRA_TRI_NORMAL},
	{TEGRA_PINGROUP_SPIA,	TEGRA_MUX_GMI,		TEGRA_PUPD_NORMAL,	TEGRA_TRI_NORMAL},
//	{TEGRA_PINGROUP_SPIB,	TEGRA_MUX_RSVD,		TEGRA_PUPD_NORMAL,	TEGRA_TRI_NORMAL},
	{TEGRA_PINGROUP_SPIB,	TEGRA_MUX_GMI,		TEGRA_PUPD_NORMAL,	TEGRA_TRI_NORMAL},
//	{TEGRA_PINGROUP_SPIC,	TEGRA_MUX_RSVD,		TEGRA_PUPD_NORMAL,	TEGRA_TRI_NORMAL},
	{TEGRA_PINGROUP_SPIC,	TEGRA_MUX_GMI,		TEGRA_PUPD_NORMAL,	TEGRA_TRI_NORMAL},
//	{TEGRA_PINGROUP_SPID,	TEGRA_MUX_RSVD,		TEGRA_PUPD_NORMAL,	TEGRA_TRI_NORMAL},
	{TEGRA_PINGROUP_SPID,	TEGRA_MUX_SPI1,		TEGRA_PUPD_NORMAL,	TEGRA_TRI_NORMAL},
//	{TEGRA_PINGROUP_SPIE,	TEGRA_MUX_RSVD,		TEGRA_PUPD_NORMAL,	TEGRA_TRI_NORMAL},
	{TEGRA_PINGROUP_SPIE,	TEGRA_MUX_SPI1,		TEGRA_PUPD_NORMAL,	TEGRA_TRI_NORMAL},
	{TEGRA_PINGROUP_SPIF,	TEGRA_MUX_RSVD,		TEGRA_PUPD_NORMAL,	TEGRA_TRI_NORMAL},

	/* USBH_PEN */
//	{TEGRA_PINGROUP_SPIG,	TEGRA_MUX_RSVD,		TEGRA_PUPD_PULL_UP,	TEGRA_TRI_NORMAL},
	{TEGRA_PINGROUP_SPIG,	TEGRA_MUX_SPI2_ALT,	TEGRA_PUPD_NORMAL,	TEGRA_TRI_NORMAL},
	/* USBH_OC */
//	{TEGRA_PINGROUP_SPIH,	TEGRA_MUX_RSVD,		TEGRA_PUPD_PULL_UP,	TEGRA_TRI_NORMAL},
	{TEGRA_PINGROUP_SPIH,	TEGRA_MUX_SPI2_ALT,	TEGRA_PUPD_PULL_UP,	TEGRA_TRI_NORMAL},
	{TEGRA_PINGROUP_UAA,	TEGRA_MUX_ULPI,		TEGRA_PUPD_PULL_UP,	TEGRA_TRI_NORMAL},
	{TEGRA_PINGROUP_UAB,	TEGRA_MUX_ULPI,		TEGRA_PUPD_PULL_UP,	TEGRA_TRI_NORMAL},
	/* WM9715L RESET#, USB3340 RESETB, WM9715L GENIRQ and GPIO V3 */
	{TEGRA_PINGROUP_UAC,	TEGRA_MUX_RSVD,		TEGRA_PUPD_NORMAL,	TEGRA_TRI_NORMAL},
	/* STD_TXD and STD_RXD */
	{TEGRA_PINGROUP_UAD,	TEGRA_MUX_IRDA,		TEGRA_PUPD_NORMAL,	TEGRA_TRI_NORMAL},
	/* A2 and A3 */
	{TEGRA_PINGROUP_UCA,	TEGRA_MUX_GMI,		TEGRA_PUPD_NORMAL,	TEGRA_TRI_NORMAL},
	/* A4 and A5 */
	{TEGRA_PINGROUP_UCB,	TEGRA_MUX_GMI,		TEGRA_PUPD_NORMAL,	TEGRA_TRI_NORMAL},
	{TEGRA_PINGROUP_UDA,	TEGRA_MUX_ULPI,		TEGRA_PUPD_NORMAL,	TEGRA_TRI_NORMAL},
	{TEGRA_PINGROUP_XM2C,	TEGRA_MUX_NONE,		TEGRA_PUPD_NORMAL,	TEGRA_TRI_NORMAL},
	{TEGRA_PINGROUP_XM2D,	TEGRA_MUX_NONE,		TEGRA_PUPD_NORMAL,	TEGRA_TRI_NORMAL},
};

#if 0
/* 32-bit wide data and 28-bit wide address bus, more chip selects */
static __initdata struct tegra_pingroup_config colibri_t20_widebus_pinmux[] = {
	/* D28, D29, D30 and D31 */
	{TEGRA_PINGROUP_DAP1,	TEGRA_MUX_GMI, TEGRA_PUPD_NORMAL, TEGRA_TRI_NORMAL},
	/* AD20, AD21, AD22 and AD23 */
	{TEGRA_PINGROUP_GMA,	TEGRA_MUX_GMI, TEGRA_PUPD_NORMAL, TEGRA_TRI_NORMAL},
	/* AD16, AD17, AD18 and AD19 */
	{TEGRA_PINGROUP_GMC,	TEGRA_MUX_GMI, TEGRA_PUPD_NORMAL, TEGRA_TRI_NORMAL},
	/* nCS0 and nCS1 */
	{TEGRA_PINGROUP_GMD,	TEGRA_MUX_GMI, TEGRA_PUPD_NORMAL, TEGRA_TRI_NORMAL},
#ifndef SDHCI_8BIT
	/* AD24, AD25, AD26 and AD27 */
	{TEGRA_PINGROUP_GME,	TEGRA_MUX_GMI, TEGRA_PUPD_NORMAL, TEGRA_TRI_NORMAL},
#endif
};
#endif

int __init colibri_t20_pinmux_init(void)
{
	tegra_pinmux_config_table(colibri_t20_pinmux, ARRAY_SIZE(colibri_t20_pinmux));
	tegra_drive_pinmux_config_table(colibri_t20_drive_pinmux,
					ARRAY_SIZE(colibri_t20_drive_pinmux));

	return 0;
}
