# Makefile for TCCxxx HDIN driver

obj-$(CONFIG_VIDEO_TCCXX_HDMI_RX) += tcc_hdin_main.o tcc_hdin_video.o tcc_hdin_ctrl.o tcc_hdin_i2c.o
obj-$(CONFIG_VIDEO_HDMI_RX_MODULE_EP9553T) += module/

EXTRA_CFLAGS = -I$(src)/..
