/*
 * linux/include/video/tcc/vioc_ddicfg.h
 * Author:  <linux@telechips.com>
 * Created: June 10, 2008
 * Description: TCC VIOC h/w block 
 *
 * Copyright (C) 2008-2009 Telechips
 *
 * This program is free software; you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation; either version 2 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program; if not, see the file COPYING, or write
 * to the Free Software Foundation, Inc.,
 * 51 Franklin St, Fifth Floor, Boston, MA  02110-1301  USA
 */

#ifndef __VIOC_DDI_CONFIG_H__
#define	__VIOC_DDI_CONFIG_H__

#define LVDS_TX_DATA_MAX	(8)
#define LVDS_TX_DATA(x)		(((x) > LVDS_TX_DATA_MAX) ? (-x) : (x))

#ifdef CONFIG_VIOC_DOLBY_VISION_EDR
#define DDICFG_TYPE_NG		(5)
#define DDICFG_TYPE_DV		(8)
#endif

#define DDICFG_TYPE_LVDS		(3)
#define DDICFG_TYPE_MIPI		(4)
#define DDICFG_TYPE_HDMNI		(2)
#define DDICFG_TYPE_NTSCPAL		(1)
#define DDICFG_TYPE_VIOC		(0)

/*
 * Register offset
 */
#define DDI_PWDN		(0x00)
#define SWRESET		(0x04)
#define	CIFPORT0		(0x08)
#define CIFPORT1		(0x0C)
#define	HDMI_CTRL		(0x10)
#define	X2X_CFG_0		(0x80)
#define	X2X_CFG_1		(0x84)
#define	X2X_CFG_2		(0x88)
#define HDMI_PHY_EXTCLK_MASK		(0xD0)
#define	HDMI_BM_CFG			(0x8C)
#define MIPI_CFG		(0x100)
#define MIPI_DPHY_STATUS0		(0x104)
#define MIPI_DPHY_STATUS1		(0x108)
#define MIPI_DPHY_STATUS2		(0x10C)
#define MIPI_DPHY_STATUS3		(0x110)
#define MIPI_DPHY_STATUS4		(0x114)
#define DISP_DLY_0_00		(0x200)
#define DISP_DLY_0_01		(0x204)
#define DISP_DLY_0_02		(0x208)
#define DISP_DLY_0_03		(0x20C)
#define DISP_DLY_0_04		(0x210)
#define DISP_DLY_0_05		(0x214)
#define DISP_DLY_1_00		(0x220)
#define DISP_DLY_1_01		(0x224)
#define DISP_DLY_1_02		(0x228)
#define DISP_DLY_1_03		(0x22C)
#define DISP_DLY_1_04		(0x230)
#define DISP_DLY_1_05		(0x234)
#define DISP_DLY_2_00		(0x240)
#define DISP_DLY_2_01		(0x244)
#define DISP_DLY_2_02		(0x248)
#define DISP_DLY_2_03		(0x24C)
#define DISP_DLY_2_04		(0x250)
#define DISP_DLY_2_05		(0x254)
#define CAM_DLY_0_00		(0x280)
#define CAM_DLY_0_01		(0x284)
#define CAM_DLY_0_02		(0x288)
#define CAM_DLY_0_03		(0x28C)
#define CAM_DLY_0_04		(0x290)
#define CAM_DLY_0_05		(0x294)
#define CAM_DLY_1_00		(0x2A0)
#define CAM_DLY_1_01		(0x2A4)
#define CAM_DLY_1_02		(0x2A8)
#define CAM_DLY_1_03		(0x2AC)
#define CAM_DLY_1_04		(0x2B0)
#define CAM_DLY_1_05		(0x2B4)
#define CAM_DLY_2_00		(0x2C0)
#define CAM_DLY_2_01		(0x2C4)
#define CAM_DLY_2_02		(0x2C8)
#define CAM_DLY_2_03		(0x2CC)
#define CAM_DLY_2_04		(0x2D0)
#define CAM_DLY_2_05		(0x2D4)
#define CAM_DLY_3_00		(0x2E0)
#define CAM_DLY_3_01		(0x2E4)
#define CAM_DLY_3_02		(0x2E8)
#define CAM_DLY_3_03		(0x2EC)
#define CAM_DLY_3_04		(0x2F0)
#define CAM_DLY_3_05		(0x2F4)
#define CAM_DLY_4_00		(0x300)
#define CAM_DLY_4_01		(0x304)
#define CAM_DLY_4_02		(0x308)
#define CAM_DLY_4_03		(0x30C)
#define CAM_DLY_4_04		(0x310)
#define CAM_DLY_4_05		(0x314)

/*
 * Power down for DDIBUS
 */
#define PWDN_L2S_SHIFT			(18)
#define PWDN_L1S_SHIFT			(17)
#define PWDN_L0S_SHIFT			(16)
#define PWDN_LVDS_SHIFT			(5)
#define PWDN_MIPI_SHIFT			(4)
#define PWDN_HDMI_SHIFT			(2)
#define PWDN_VIOC_SHIFT			(0)

#define PWDN_L2S_MASK			(0x1 << PWDN_L2S_SHIFT)
#define PWDN_L1S_MASK			(0x1 << PWDN_L1S_SHIFT)
#define PWDN_L0S_MASK			(0x1 << PWDN_L0S_SHIFT)
#define PWDN_LVDS_MASK			(0x1 << PWDN_LVDS_SHIFT)
#define PWDN_MIPI_MASK			(0x1 << PWDN_MIPI_SHIFT)
#define PWDN_HDMI_MASK			(0x1 << PWDN_HDMI_SHIFT)
#define PWDN_VIOC_MASK			(0x1 << PWDN_VIOC_SHIFT)

/*
 * SWReset for DDIBUS
 */
#define SWRESET_LVDS_SHIFT		(5)
#define SWRESET_MIPI_SHIFT		(4)
#define SWRESET_HDMI_SHIFT		(2)
#define SWRESET_VIOC_SHIFT		(0)

#define SWRESET_LVDS_MASK		(0x1 << SWRESET_LVDS_SHIFT)
#define SWRESET_MIPI_MASK		(0x1 << SWRESET_MIPI_SHIFT)
#define SWRESET_HDMI_MASK		(0x1 << SWRESET_HDMI_SHIFT)
#define SWRESET_VIOC_MASK		(0x1 << SWRESET_VIOC_SHIFT)

/*
 * CIF Prot 0 Register
 */
#define CIFPORT0_CIF7_SHIFT			(28)
#define CIFPORT0_CIF6_SHIFT			(24)
#define CIFPORT0_CIF5_SHIFT			(20)
#define CIFPORT0_CIF4_SHIFT			(16)
#define CIFPORT0_CIF3_SHIFT			(12)
#define CIFPORT0_CIF2_SHIFT			(8)
#define CIFPORT0_CIF1_SHIFT			(4)
#define CIFPORT0_CIF0_SHIFT			(0)

#define CIFPORT0_CIF7_MASK			(0xF << CIFPORT0_CIF7_SHIFT)
#define CIFPORT0_CIF6_MASK			(0xF << CIFPORT0_CIF6_SHIFT)
#define CIFPORT0_CIF5_MASK			(0xF << CIFPORT0_CIF5_SHIFT)
#define CIFPORT0_CIF4_MASK			(0xF << CIFPORT0_CIF4_SHIFT)
#define CIFPORT0_CIF3_MASK			(0xF << CIFPORT0_CIF3_SHIFT)
#define CIFPORT0_CIF2_MASK			(0xF << CIFPORT0_CIF3_SHIFT)
#define CIFPORT0_CIF1_MASK			(0xF << CIFPORT0_CIF3_SHIFT)
#define CIFPORT0_CIF0_MASK			(0xF << CIFPORT0_CIF3_SHIFT)

/*
 * CIF Port Register
 */
#define CIFPORT_CIF_BITSEL_SHIFT	(12)
#define CIFPORT_DEMUX_SHIFT			(0)

#define CIFPORT_CIF_BITSEL_MASK		(0x3FFFF << CIFPORT_CIF_BITSEL_SHIFT)
#define CIFPORT_DEMUX_MASK			(0xF << CIFPORT_DEMUX_SHIFT)

/*
 * HDMI Control Register
 */
#define HDMI_CTRL_PHY_REFCLK_SHIFT		(25)
#define HDMI_CTRL_PHY_CLK_SHIFT			(24)
#define HDMI_CTRL_PHY_MON_CODE_SHIFT		(16)
#define HDMI_CTRL_EN_SHIFT			(15)
#define HDMI_CTRL_PRNG_SHIFT			(14)
#define HDMI_CTRL_REF_SHIFT			(11)
#define HDMI_CTRL_TB_SHIFT			(9)
#define HDMI_CTRL_PHY_ST_SHIFT			(6)
#define HDMI_CTRL_HPD_SEL_SHIFT			(4)
#define HDMI_CTRL_RESET_PHY_SHIFT		(1)
#define HDMI_CTRL_RESET_LINK_SHIFT		(0)
#define HDMI_CTRL_RESET_SHIFT			(0)

#define HDMI_CTRL_PHY_REFCLK_MASK		(0x1 << HDMI_CTRL_PHY_REFCLK_SHIFT)
#define HDMI_CTRL_PHYCLK_MASK			(0x1 << HDMI_CTRL_PHY_CLK_SHIFT)
#define HDMI_CTRL_PHY_MOD_CODE_MASK		(0x1F << HDMI_CTRL_PHY_MON_CODE_SHIFT)
#define HDMI_CTRL_EN_MASK			(0x1 << HDMI_CTRL_EN_SHIFT)
#define HDMI_CTRL_PRNG_MASK			(0x1 << HDMI_CTRL_PRNG_SHIFT)
#define HDMI_CTRL_REF_MASK			(0x7 << HDMI_CTRL_REF_SHIFT)
#define HDMI_CTRL_TB_MASK			(0x3 << HDMI_CTRL_TB_SHIFT)
#define HDMI_CTRL_PHY_ST_MASK		(0x7 << HDMI_CTRL_PHY_ST_SHIFT)
#define HDMI_CTRL_HPD_SEL_MASK		(0x1 << HDMI_CTRL_HPD_SEL_SHIFT)
#define HDMI_CTRL_RESET_PHY_MASK		(0x1 << HDMI_CTRL_RESET_PHY_SHIFT)
#define HDMI_CTRL_RESET_LINK_MASK		(0x1 << HDMI_CTRL_RESET_LINK_SHIFT)
#define HDMI_CTRL_RESET_MASK		(0xF << HDMI_CTRL_RESET_SHIFT)
#define HDMI_CTRL_TB_VAL                        (0x3 << HDMI_CTRL_TB_SHIFT)

/* 
 * HDMI Control Register - PLL_SEL
 */
#define HDMI_CTRL_SEL_PHY_READY         (0x1)
#define HDMI_CTRL_SEL_PHY_CLK_READY     (0x2)
#define HDMI_CTRL_SEL_PLL_LOCK          (0x4)

/*
 * X2X CFG 0, 1, 2 Register
 */
#define X2X_CFG_PWRA_SHIFT		(1)
#define X2X_CFG_PWRN_SHIFT		(0)

#define X2X_CFG_PWRA_MASK		(0x1 << X2X_CFG_PWRA_SHIFT)
#define X2X_CFG_PWRN_MASK		(0x1 << X2X_CFG_PWRN_SHIFT)

/* 
 * HDMI Control Register - REF
 */
#define HDMI_CTRL_REF_PHY_24M           (0x2 << HDMI_CTRL_REF_SHIFT)
//#define HDMI_CTRL_REF_HDMI_XIN          (0x1 << HDMI_CTRL_REF_SHIFT)
#define HDMI_CTRL_REF_PAD_XIN           (0x0 << HDMI_CTRL_REF_SHIFT)

/* 
 * HDMI Control Register - PLL_SEL
 */
#define HDMI_CTRL_ST_PHY_READY         (0x1 << HDMI_CTRL_PHY_ST_SHIFT)
#define HDMI_CTRL_ST_PHY_CLK_READY     (0x2 << HDMI_CTRL_PHY_ST_SHIFT)
#define HDMI_CTRL_ST_PLL_LOCK          (0x4 << HDMI_CTRL_PHY_ST_SHIFT)

/*
 * HDMI I2C Filter Register
 */
#define HDMI_I2C_FILTER_F1_DIV_SHIFT	(12)
#define HDMI_I2C_FILTER_F0_DIV_SHIFT	(8)
#define HDMI_I2C_FILTER_F1_EN_SHIFT		(1)
#define HDMI_I2C_FILTER_F0_EN_SHIFT		(0)

#define HDMI_I2C_FILTER_F1_DIV_MASK		(0xF << HDMI_I2C_FILTER_F1_DIV_SHIFT)
#define HDMI_I2C_FILTER_F0_DIV_MASK		(0xF << HDMI_I2C_FILTER_F0_DIV_SHIFT)
#define HDMI_I2C_FILTER_F1_EN_MASK		(0x1 << HDMI_I2C_FILTER_F1_EN_SHIFT)
#define HDMI_I2C_FILTER_F0_EN_MASK		(0x1 << HDMI_I2C_FILTER_F0_EN_SHIFT)


/*
 * MIPI Configuration Register
 */
#define MIPI_CFG_GEN_APB_RST_SHIFT		(31)
#define MIPI_CFG_GEN_PX_RST_SHIFT		(30)
#define MIPI_CFG_CSI_DATA_ALIGN_SHIFT		(16)
#define MIPI_CFG_LOOPBACK_EN_SHIFT		(9)
#define MIPI_CFG_S_RESETN_SHIFT		(8)
#define MIPI_CFG_M_RESETN_SHIFT		(7)
#define MIPI_CFG_S_FORCERXMODE3_SHIFT		(6)
#define MIPI_CFG_S_FORCERXMODE2_SHIFT		(5)
#define MIPI_CFG_S_FORCERXMODE1_SHIFT		(4)
#define MIPI_CFG_S_FORCERXMODE0_SHIFT		(3)
#define MIPI_CFG_S3_BIASEN_SHIFT		(2)
#define MIPI_CFG_S2_BIASEN_SHIFT		(1)
#define MIPI_CFG_S1_BIASEN_SHIFT		(0)

#define MIPI_CFG_GEN_APB_RST_MASK		(0x1 << MIPI_CFG_GEN_APB_RST_SHIFT)
#define MIPI_CFG_GEN_PX_RST_MASK		(0x1 << MIPI_CFG_GEN_PX_RST_SHIFT)
#define MIPI_CFG_CSI_DATA_ALIGN_MASK		(0x3 << MIPI_CFG_CSI_DATA_ALIGN_SHIFT)
#define MIPI_CFG_LOOPBACK_EN_MASK		(0x1 << MIPI_CFG_LOOPBACK_EN_SHIFT)
#define MIPI_CFG_S_RESETN_MASK		(0x1 << MIPI_CFG_S_RESETN_SHIFT)
#define MIPI_CFG_M_RESETN_MASK		(0x1 << MIPI_CFG_M_RESETN_SHIFT)
#define MIPI_CFG_S_FORCERXMODE3_MASK		(0x1 << MIPI_CFG_S_FORCERXMODE3_SHIFT)
#define MIPI_CFG_S_FORCERXMODE2_MASK		(0x1 << MIPI_CFG_S_FORCERXMODE2_SHIFT)
#define MIPI_CFG_S_FORCERXMODE1_MASK		(0x1 << MIPI_CFG_S_FORCERXMODE1_SHIFT)
#define MIPI_CFG_S_FORCERXMODE0_MASK		(0x1 << MIPI_CFG_S_FORCERXMODE0_SHIFT)
#define MIPI_CFG_S3_BIASEN_MASK		(0x1 << MIPI_CFG_S3_BIASEN_SHIFT)
#define MIPI_CFG_S2_BIASEN_MASK		(0x1 << MIPI_CFG_S2_BIASEN_SHIFT)
#define MIPI_CFG_S1_BIASEN_MASK		(0x1 << MIPI_CFG_S1_BIASEN_SHIFT)

/*
 * MIPI DPHY Status 0,1,2,3 Register
 */
#define MIPI_DPHY_STATUS_S_ATB_OUT_SHIFT		(0)

#define MIPI_DPHY_STATUS_S_ATB_OUT_MASK		(0xFFFFFFFF << MIPI_DPHY_STATUS_S_ATB_OUT_SHIFT)

/*
 * MIPI DPHY Status 4 Register
 */
#define MIPI_DPHY_STATUS4_S_ERR3_ESC_SHIFT		(8)
#define MIPI_DPHY_STATUS4_S_ERR2_ESC_SHIFT		(7)
#define MIPI_DPHY_STATUS4_S_ERR1_ESC_SHIFT		(6)
#define MIPI_DPHY_STATUS4_S_ERR0_ESC_SHIFT		(5)
#define MIPI_DPHY_STATUS4_S_ERR3CONTROL_SHIFT		(3)
#define MIPI_DPHY_STATUS4_S_ERR2CONTROL_SHIFT		(2)
#define MIPI_DPHY_STATUS4_S_ERR1CONTROL_SHIFT		(1)
#define MIPI_DPHY_STATUS4_S_ERR0CONTROL_SHIFT		(0)

#define MIPI_DPHY_STATUS4_S_ERR3_ESC_MASK		(0x1 << MIPI_DPHY_STATUS4_S_ERR3_ESC_SHIFT)
#define MIPI_DPHY_STATUS4_S_ERR2_ESC_MASK		(0x1 << MIPI_DPHY_STATUS4_S_ERR2_ESC_SHIFT)
#define MIPI_DPHY_STATUS4_S_ERR1_ESC_MASK		(0x1 << MIPI_DPHY_STATUS4_S_ERR1_ESC_SHIFT)
#define MIPI_DPHY_STATUS4_S_ERR0_ESC_MASK		(0x1 << MIPI_DPHY_STATUS4_S_ERR0_ESC_SHIFT)
#define MIPI_DPHY_STATUS4_S_ERR3CONTROL_MASK		(0x1 << MIPI_DPHY_STATUS4_S_ERR3CONTROL_SHIFT)
#define MIPI_DPHY_STATUS4_S_ERR2CONTROL_MASK		(0x1 << MIPI_DPHY_STATUS4_S_ERR2CONTROL_SHIFT)
#define MIPI_DPHY_STATUS4_S_ERR1CONTROL_MASK		(0x1 << MIPI_DPHY_STATUS4_S_ERR1CONTROL_SHIFT)
#define MIPI_DPHY_STATUS4_S_ERR0CONTROL_MASK		(0x1 << MIPI_DPHY_STATUS4_S_ERR0CONTROL_SHIFT)

/*
 * DISP Delay 00 Register
 */
#define DISP_DLY_00_LPXCLK_SHIFT		(0)

#define DISP_DLY_00_LPXCLK_MASK		(0x1F << DISP_DLY_00_LPXCLK_SHIFT)

/*
 * DISP Delay 01 Register
 */
#define DISP_DLY_01_LFIELD_SHIFT		(16)
#define DISP_DLY_01_LDE_SHIFT		(12)
#define DISP_DLY_01_LHSYNC_SHIFT		(8)
#define DISP_DLY_01_LVSYNC_SHIFT		(4)
#define DISP_DLY_01_EVSYNC_SHIFT		(0)

#define DISP_DLY_01_LFIELD_MASK		(0xF << DISP_DLY_01_LFIELD_SHIFT)
#define DISP_DLY_01_LDE_MASK		(0xF << DISP_DLY_01_LDE_SHIFT)
#define DISP_DLY_01_LHSYNC_MASK		(0xF << DISP_DLY_01_LHSYNC_SHIFT)
#define DISP_DLY_01_LVSYNC_MASK		(0xF << DISP_DLY_01_LVSYNC_SHIFT)
#define DISP_DLY_01_EVSYNC_MASK		(0xF << DISP_DLY_01_EVSYNC_SHIFT)

/*
 * DISP Delay 02 Register
 */
#define DISP_DLY_02_LPXDATA_07_SHIFT		(28)
#define DISP_DLY_02_LPXDATA_06_SHIFT		(24)
#define DISP_DLY_02_LPXDATA_05_SHIFT		(20)
#define DISP_DLY_02_LPXDATA_04_SHIFT		(16)
#define DISP_DLY_02_LPXDATA_03_SHIFT		(12)
#define DISP_DLY_02_LPXDATA_02_SHIFT		(8)
#define DISP_DLY_02_LPXDATA_01_SHIFT		(4)
#define DISP_DLY_02_LPXDATA_00_SHIFT		(0)

#define DISP_DLY_02_LPXDATA_07_MASK		(0xF << DISP_DLY_02_LPXDATA_07_SHIFT)
#define DISP_DLY_02_LPXDATA_06_MASK		(0xF << DISP_DLY_02_LPXDATA_06_SHIFT)
#define DISP_DLY_02_LPXDATA_05_MASK		(0xF << DISP_DLY_02_LPXDATA_05_SHIFT)
#define DISP_DLY_02_LPXDATA_04_MASK		(0xF << DISP_DLY_02_LPXDATA_04_SHIFT)
#define DISP_DLY_02_LPXDATA_03_MASK		(0xF << DISP_DLY_02_LPXDATA_03_SHIFT)
#define DISP_DLY_02_LPXDATA_02_MASK		(0xF << DISP_DLY_02_LPXDATA_02_SHIFT)
#define DISP_DLY_02_LPXDATA_01_MASK		(0xF << DISP_DLY_02_LPXDATA_01_SHIFT)
#define DISP_DLY_02_LPXDATA_00_MASK		(0xF << DISP_DLY_02_LPXDATA_00_SHIFT)

/*
 * DISP Delay 03 Register
 */
#define DISP_DLY_03_LPXDATA_15_SHIFT		(28)
#define DISP_DLY_03_LPXDATA_14_SHIFT		(24)
#define DISP_DLY_03_LPXDATA_13_SHIFT		(20)
#define DISP_DLY_03_LPXDATA_12_SHIFT		(16)
#define DISP_DLY_03_LPXDATA_11_SHIFT		(12)
#define DISP_DLY_03_LPXDATA_10_SHIFT		(8)
#define DISP_DLY_03_LPXDATA_09_SHIFT		(4)
#define DISP_DLY_03_LPXDATA_08_SHIFT		(0)

#define DISP_DLY_03_LPXDATA_15_MASK		(0xF << DISP_DLY_03_LPXDATA_15_SHIFT)
#define DISP_DLY_03_LPXDATA_14_MASK		(0xF << DISP_DLY_03_LPXDATA_14_SHIFT)
#define DISP_DLY_03_LPXDATA_13_MASK		(0xF << DISP_DLY_03_LPXDATA_13_SHIFT)
#define DISP_DLY_03_LPXDATA_12_MASK		(0xF << DISP_DLY_03_LPXDATA_12_SHIFT)
#define DISP_DLY_03_LPXDATA_11_MASK		(0xF << DISP_DLY_03_LPXDATA_11_SHIFT)
#define DISP_DLY_03_LPXDATA_10_MASK		(0xF << DISP_DLY_03_LPXDATA_10_SHIFT)
#define DISP_DLY_03_LPXDATA_09_MASK		(0xF << DISP_DLY_03_LPXDATA_09_SHIFT)
#define DISP_DLY_03_LPXDATA_08_MASK		(0xF << DISP_DLY_03_LPXDATA_08_SHIFT)

/*
 * DISP Delay 04 Register
 */
#define DISP_DLY_04_LPXDATA_23_SHIFT		(28)
#define DISP_DLY_04_LPXDATA_22_SHIFT		(24)
#define DISP_DLY_04_LPXDATA_21_SHIFT		(20)
#define DISP_DLY_04_LPXDATA_20_SHIFT		(16)
#define DISP_DLY_04_LPXDATA_19_SHIFT		(12)
#define DISP_DLY_04_LPXDATA_18_SHIFT		(8)
#define DISP_DLY_04_LPXDATA_17_SHIFT		(4)
#define DISP_DLY_04_LPXDATA_16_SHIFT		(0)

#define DISP_DLY_04_LPXDATA_23_MASK		(0xF << DISP_DLY_04_LPXDATA_23_SHIFT)
#define DISP_DLY_04_LPXDATA_22_MASK		(0xF << DISP_DLY_04_LPXDATA_22_SHIFT)
#define DISP_DLY_04_LPXDATA_21_MASK		(0xF << DISP_DLY_04_LPXDATA_21_SHIFT)
#define DISP_DLY_04_LPXDATA_20_MASK		(0xF << DISP_DLY_04_LPXDATA_20_SHIFT)
#define DISP_DLY_04_LPXDATA_19_MASK		(0xF << DISP_DLY_04_LPXDATA_19_SHIFT)
#define DISP_DLY_04_LPXDATA_18_MASK		(0xF << DISP_DLY_04_LPXDATA_18_SHIFT)
#define DISP_DLY_04_LPXDATA_17_MASK		(0xF << DISP_DLY_04_LPXDATA_17_SHIFT)
#define DISP_DLY_04_LPXDATA_16_MASK		(0xF << DISP_DLY_04_LPXDATA_16_SHIFT)

/*
 * DISP Delay 05 Register
 */
#define DISP_DLY_05_LPXDATA_29_SHIFT		(20)
#define DISP_DLY_05_LPXDATA_28_SHIFT		(16)
#define DISP_DLY_05_LPXDATA_27_SHIFT		(12)
#define DISP_DLY_05_LPXDATA_26_SHIFT		(8)
#define DISP_DLY_05_LPXDATA_25_SHIFT		(4)
#define DISP_DLY_05_LPXDATA_24_SHIFT		(0)

#define DISP_DLY_05_LPXDATA_29_MASK		(0xF << DISP_DLY_05_LPXDATA_29_SHIFT)
#define DISP_DLY_05_LPXDATA_28_MASK		(0xF << DISP_DLY_05_LPXDATA_28_SHIFT)
#define DISP_DLY_05_LPXDATA_27_MASK		(0xF << DISP_DLY_05_LPXDATA_27_SHIFT)
#define DISP_DLY_05_LPXDATA_26_MASK		(0xF << DISP_DLY_05_LPXDATA_26_SHIFT)
#define DISP_DLY_05_LPXDATA_25_MASK		(0xF << DISP_DLY_05_LPXDATA_25_SHIFT)
#define DISP_DLY_05_LPXDATA_24_MASK		(0xF << DISP_DLY_05_LPXDATA_24_SHIFT)

/*
 * Camera Delay 00 Register
 */
#define CAM_DLY_00_CAM_PXCLK_SHIFT		(0)

#define CAM_DLY_00_CAM_PXCLK_MASK		(0x1F << CAM_DLY_00_CAM_PXCLK_SHIFT)

/*
 * Camera Delay 01 Register
 */
#define CAM_DLY_01_DE_SHIFT		(12)
#define CAM_DLY_01_FIELD_SHIFT		(8)
#define CAM_DLY_01_HSYNC_SHIFT		(4)
#define CAM_DLY_01_VSYNC_SHIFT		(0)

#define CAM_DLY_01_DE_MASK		(0xF << CAM_DLY_01_DE_SHIFT)
#define CAM_DLY_01_FIELD_MASK		(0xF << CAM_DLY_01_FIELD_SHIFT)
#define CAM_DLY_01_HSYNC_MASK		(0xF << CAM_DLY_01_HSYNC_SHIFT)
#define CAM_DLY_01_VSYNC_MASK		(0xF << CAM_DLY_01_VSYNC_SHIFT)

/*
 * Camera Delay 02 Register
 */
#define CAM_DLY_02_CAMDATA_07_SHIFT		(28)
#define CAM_DLY_02_CAMDATA_06_SHIFT		(24)
#define CAM_DLY_02_CAMDATA_05_SHIFT		(20)
#define CAM_DLY_02_CAMDATA_04_SHIFT		(16)
#define CAM_DLY_02_CAMDATA_03_SHIFT		(12)
#define CAM_DLY_02_CAMDATA_02_SHIFT		(8)
#define CAM_DLY_02_CAMDATA_01_SHIFT		(4)
#define CAM_DLY_02_CAMDATA_00_SHIFT		(0)

#define CAM_DLY_02_CAMDATA_07_MASK		(0xF << CAM_DLY_02_CAMDATA_07_SHIFT)
#define CAM_DLY_02_CAMDATA_06_MASK		(0xF << CAM_DLY_02_CAMDATA_06_SHIFT)
#define CAM_DLY_02_CAMDATA_05_MASK		(0xF << CAM_DLY_02_CAMDATA_05_SHIFT)
#define CAM_DLY_02_CAMDATA_04_MASK		(0xF << CAM_DLY_02_CAMDATA_04_SHIFT)
#define CAM_DLY_02_CAMDATA_03_MASK		(0xF << CAM_DLY_02_CAMDATA_03_SHIFT)
#define CAM_DLY_02_CAMDATA_02_MASK		(0xF << CAM_DLY_02_CAMDATA_02_SHIFT)
#define CAM_DLY_02_CAMDATA_01_MASK		(0xF << CAM_DLY_02_CAMDATA_01_SHIFT)
#define CAM_DLY_02_CAMDATA_00_MASK		(0xF << CAM_DLY_02_CAMDATA_00_SHIFT)

/*
 * Camera Delay 03 Register
 */
#define CAM_DLY_03_CAMDATA_15_SHIFT		(28)
#define CAM_DLY_03_CAMDATA_14_SHIFT		(24)
#define CAM_DLY_03_CAMDATA_13_SHIFT		(20)
#define CAM_DLY_03_CAMDATA_12_SHIFT		(16)
#define CAM_DLY_03_CAMDATA_11_SHIFT		(12)
#define CAM_DLY_03_CAMDATA_10_SHIFT		(8)
#define CAM_DLY_03_CAMDATA_09_SHIFT		(4)
#define CAM_DLY_03_CAMDATA_08_SHIFT		(0)

#define CAM_DLY_03_CAMDATA_15_MASK		(0xF << CAM_DLY_03_CAMDATA_15_SHIFT)
#define CAM_DLY_03_CAMDATA_14_MASK		(0xF << CAM_DLY_03_CAMDATA_14_SHIFT)
#define CAM_DLY_03_CAMDATA_13_MASK		(0xF << CAM_DLY_03_CAMDATA_13_SHIFT)
#define CAM_DLY_03_CAMDATA_12_MASK		(0xF << CAM_DLY_03_CAMDATA_12_SHIFT)
#define CAM_DLY_03_CAMDATA_11_MASK		(0xF << CAM_DLY_03_CAMDATA_11_SHIFT)
#define CAM_DLY_03_CAMDATA_10_MASK		(0xF << CAM_DLY_03_CAMDATA_10_SHIFT)
#define CAM_DLY_03_CAMDATA_09_MASK		(0xF << CAM_DLY_03_CAMDATA_09_SHIFT)
#define CAM_DLY_03_CAMDATA_08_MASK		(0xF << CAM_DLY_03_CAMDATA_08_SHIFT)

/*
 * Camera Delay 04 Register
 */
#define CAM_DLY_04_CAMDATA_23_SHIFT		(28)
#define CAM_DLY_04_CAMDATA_22_SHIFT		(24)
#define CAM_DLY_04_CAMDATA_21_SHIFT		(20)
#define CAM_DLY_04_CAMDATA_20_SHIFT		(16)
#define CAM_DLY_04_CAMDATA_19_SHIFT		(12)
#define CAM_DLY_04_CAMDATA_18_SHIFT		(8)
#define CAM_DLY_04_CAMDATA_17_SHIFT		(4)
#define CAM_DLY_04_CAMDATA_16_SHIFT		(0)

#define CAM_DLY_04_CAMDATA_23_MASK		(0xF << CAM_DLY_04_CAMDATA_23_SHIFT)
#define CAM_DLY_04_CAMDATA_22_MASK		(0xF << CAM_DLY_04_CAMDATA_22_SHIFT)
#define CAM_DLY_04_CAMDATA_21_MASK		(0xF << CAM_DLY_04_CAMDATA_21_SHIFT)
#define CAM_DLY_04_CAMDATA_20_MASK		(0xF << CAM_DLY_04_CAMDATA_20_SHIFT)
#define CAM_DLY_04_CAMDATA_19_MASK		(0xF << CAM_DLY_04_CAMDATA_19_SHIFT)
#define CAM_DLY_04_CAMDATA_18_MASK		(0xF << CAM_DLY_04_CAMDATA_18_SHIFT)
#define CAM_DLY_04_CAMDATA_17_MASK		(0xF << CAM_DLY_04_CAMDATA_17_SHIFT)
#define CAM_DLY_04_CAMDATA_16_MASK		(0xF << CAM_DLY_04_CAMDATA_16_SHIFT)

/*
 * Camera Delay 02 Register
 */
#define CAM_DLY_05_CAMDATA_29_SHIFT		(20)
#define CAM_DLY_05_CAMDATA_28_SHIFT		(16)
#define CAM_DLY_05_CAMDATA_27_SHIFT		(12)
#define CAM_DLY_05_CAMDATA_26_SHIFT		(8)
#define CAM_DLY_05_CAMDATA_25_SHIFT		(7)
#define CAM_DLY_05_CAMDATA_24_SHIFT		(0)

#define CAM_DLY_05_CAMDATA_29_MASK		(0xF << CAM_DLY_05_CAMDATA_29_SHIFT)
#define CAM_DLY_05_CAMDATA_28_MASK		(0xF << CAM_DLY_05_CAMDATA_28_SHIFT)
#define CAM_DLY_05_CAMDATA_27_MASK		(0xF << CAM_DLY_05_CAMDATA_27_SHIFT)
#define CAM_DLY_05_CAMDATA_26_MASK		(0xF << CAM_DLY_05_CAMDATA_26_SHIFT)
#define CAM_DLY_05_CAMDATA_25_MASK		(0xF << CAM_DLY_05_CAMDATA_25_SHIFT)
#define CAM_DLY_05_CAMDATA_24_MASK		(0xF << CAM_DLY_05_CAMDATA_24_SHIFT)

extern void VIOC_DDICONFIG_SetSWRESET(volatile void __iomem *reg, unsigned int type, unsigned int set);
extern void VIOC_DDICONFIG_SetPWDN(volatile void __iomem *reg, unsigned int type, unsigned int set);
extern void VIOC_DDICONFIG_SetPeriClock(volatile void __iomem *reg, unsigned int num, unsigned int set);
extern void VIOC_DDICONFIG_Set_hdmi_enable(volatile void __iomem *reg, unsigned int enable);
extern void VIOC_DDICONFIG_Set_prng(volatile void __iomem *reg, unsigned int enable);
extern void VIOC_DDICONFIG_Set_refclock(volatile void __iomem *reg, unsigned int ref_clock);
extern int VIOC_DDICONFIG_get_phy_status(volatile void __iomem *reg, unsigned int phy_mode);
extern void VIOC_DDICONFIG_Set_tmds_bit_order(volatile void __iomem *reg, unsigned int phy_mode);
extern void VIOC_DDICONFIG_reset_hdmi_phy(volatile void __iomem *reg, unsigned int reset_enable);
extern void VIOC_DDICONFIG_reset_hdmi_link(volatile void __iomem *reg, unsigned int reset_enable);
extern void VIOC_DDICONFIG_NTSCPAL_SetEnable(volatile void __iomem *reg, unsigned int enable, unsigned int lcdc_num);
extern void VIOC_DDICONFIG_MIPI_Reset_DPHY(volatile void __iomem *reg, unsigned int reset);
extern void VIOC_DDICONFIG_MIPI_Reset_GEN(volatile void __iomem *reg, unsigned int reset);
extern void VIOC_DDICONFIG_DUMP(void);
extern volatile void __iomem* VIOC_DDICONFIG_GetAddress(void);
#endif
