#
# Telechips SOC drivers
#

obj-y	+= timer.o
#obj-y	+= suspend.o

obj-$(CONFIG_PMAP)		+= pmap.o
#obj-$(CONFIG_ARCH_TCC802X)	+= pm-tcc802x.o
#obj-$(CONFIG_ARCH_TCC898X)	+= pm-tcc898x.o
#obj-$(CONFIG_ARCH_TCC899X)	+= pm-tcc899x.o
#obj-$(CONFIG_ARCH_TCC803X)	+= pm-tcc803x.o
#obj-$(CONFIG_TCC_MICOM)		+= micom_devices.o

#obj-$(CONFIG_ARCH_TCC899X)	+= chip_info.o
