#
# Makefile for Telechips VOUT drivers.
#
EXTRA_CFLAGS = -I$(src)/.. -Idrivers/video/fbdev/tcc-fb

obj-$(CONFIG_VIDEO_TCC_VOUT) += tcc_vout_v4l2.o \
								tcc_vout_core.o \
								tcc_vout_attr.o \
								tcc_vout_dbg.o

