// SPDX-License-Identifier: (GPL-2.0+ OR MIT)
/*
 * Copyright (C) 2020 Telechips Inc.
 */
#ifndef DT_BINDINGS_PMAP_TCC803X_LINUX_IVI_SUBCORE_A7S_H
#define DT_BINDINGS_PMAP_TCC803X_LINUX_IVI_SUBCORE_A7S_H

#include <dt-bindings/pmap/tcc803x/pmap-tcc803x-linux-ivi-subcore-a7s-display.h>

#define RESERVED_MEM_BASE		( 0x90000000 )
#define RESERVED_MEM_SIZE		( 0x10000000  - PMAP_SIZE_CAMERAS - PMAP_SIZE_ION_CARVEOUT_CAM )

#define CAMERA_MEM_BASE			( RESERVED_MEM_BASE + RESERVED_MEM_SIZE )
#define CAMERA_MEM_SIZE			( PMAP_SIZE_CAMERAS )

#define ION_CARVEOUT_CAM_MEM_BASE	( CAMERA_MEM_BASE + CAMERA_MEM_SIZE )
#define ION_CARVEOUT_CAM_MEM_SIZE	( PMAP_SIZE_ION_CARVEOUT_CAM )

#endif//DT_BINDINGS_PMAP_TCC803X_LINUX_IVI_SUBCORE_A7S_H
