obj-$(CONFIG_ISDBT_DEMUX) := tcc-demux-drv.o

tcc-demux-drv-objs := tcc_dxb_kernel.o \
                    tcc_fe.o \
                    tcc_tsif_interface.o \
		    tcc_hwdemux_tsif.o \
                    tcc_dmx.o

EXTRA_CFLAGS := -Idrivers/media/dvb-core
