# drivers/media/platform/tcc-isp/Makefile
#
# Copyright (c) 2010 Telechips Co., Ltd.
#	http://www.telechips.com/
#
# Licensed under GPL

obj-y	+= tcc-isp.o

# only for TCC805X ES(TCS CV8050C-618)
obj-$(CONFIG_TCC_ISP_USE_IOMMU) 	+= tcc-isp-iommu.o

