// SPDX-License-Identifier: GPL-2.0-or-later
/*
 * Copyright (C) Telechips Inc.
 */

#ifndef __TCC_MIPI_CFG_REG_H__
#define __TCC_MIPI_CFG_REG_H__

/*
 * MIPI CFG BASE
 */
#define CSI0_CFG		(0X000)
#define CSI1_CFG		(0X004)
#define CSI0_DPHY_STATUS0	(0X008)
#define CSI0_DPHY_STATUS1	(0X00C)
#define CSI0_DPHY_STATUS2	(0X010)
#define CSI0_DPHY_STATUS3	(0X014)
#define CSI0_DPHY_STATUS4	(0X018)
#define CSI1_DPHY_STATUS0	(0X01C)
#define CSI1_DPHY_STATUS1	(0X020)
#define CSI1_DPHY_STATUS2	(0X024)
#define CSI1_DPHY_STATUS3	(0X028)
#define CSI1_DPHY_STATUS4	(0X02C)
#define ISP_CLK_MASK		(0X200)
#define ISP_SWRST		(0X204)
#define ISP_PX1X_DIV		(0X208)
#define ISP_BYPASS		(0X20C)
#define ISP_X2X_CFG		(0X210)
#define ISP_FMT_CFG		(0X214)
#define ISP_APBADDR_CFG0	(0X218)
#define ISP_APBADDR_CFG1	(0X21C)

/*
 * CSI_CFG
 */
#define CSI_CFG_GEN_APB_RST_SHIFT	(31)
#define CSI_CFG_GEN_PX_RST_SHIFT	(30)
#define CSI_CFG_MIPI_SWRST_SHIFT	(29)
#define CSI_CFG_MIPI_CKMASK_SHIFT	(28)
#define CSI_CFG_MIPI_CHMUX_3_SHIFT	(27)
#define CSI_CFG_MIPI_CHMUX_2_SHIFT	(26)
#define CSI_CFG_MIPI_CHMUX_1_SHIFT	(25)
#define CSI_CFG_MIPI_CHMUX_0_SHIFT	(24)
#define CSI_CFG_VSYNC_INV3_SHIFT	(23)
#define CSI_CFG_VSYNC_INV2_SHIFT	(22)
#define CSI_CFG_VSYNC_INV1_SHIFT	(21)
#define CSI_CFG_VSYNC_INV0_SHIFT	(20)
#define CSI_CFG_CSI_DATA_ALIGN_SHIFT	(16)
#define CSI_CFG_HSYNC_INV3_SHIFT	(15)
#define CSI_CFG_HSYNC_INV2_SHIFT	(14)
#define CSI_CFG_HSYNC_INV1_SHIFT	(13)
#define CSI_CFG_HSYNC_INV0_SHIFT	(12)
#define CSI_CFG_LOOPBACK_EN_SHIFT	(9)
#define CSI_CFG_S_RESETN_SHIFT		(8)
#define CSI_CFG_M_RESETN_SHIFT		(7)
#define CSI_CFG_S_FORCERXMODE3_SHIFT	(6)
#define CSI_CFG_S_FORCERXMODE2_SHIFT	(5)
#define CSI_CFG_S_FORCERXMODE1_SHIFT	(4)
#define CSI_CFG_S_FORCERXMODE0_SHIFT	(3)
#define CSI_CFG_S3_BIASEN_SHIFT		(2)
#define CSI_CFG_S2_BIASEN_SHIFT		(1)
#define CSI_CFG_S1_BIASEN_SHIFT		(0)

#define CSI_CFG_GEN_APB_RST_MASK	((0X1) << CSI_CFG_GEN_APB_RST_SHIFT)
#define CSI_CFG_GEN_PX_RST_MASK		((0X1) << CSI_CFG_GEN_PX_RST_SHIFT)
#define CSI_CFG_MIPI_SWRST_MASK		((0X1) << CSI_CFG_MIPI_SWRST_SHIFT)
#define CSI_CFG_MIPI_CKMASK_MASK	((0X1) << CSI_CFG_MIPI_CKMASK_SHIFT)
#define CSI_CFG_MIPI_CHMUX_3_MASK	((0X1) << CSI_CFG_MIPI_CHMUX_3_SHIFT)
#define CSI_CFG_MIPI_CHMUX_2_MASK	((0X1) << CSI_CFG_MIPI_CHMUX_2_SHIFT)
#define CSI_CFG_MIPI_CHMUX_1_MASK	((0X1) << CSI_CFG_MIPI_CHMUX_1_SHIFT)
#define CSI_CFG_MIPI_CHMUX_0_MASK	((0X1) << CSI_CFG_MIPI_CHMUX_0_SHIFT)
#define CSI_CFG_VSYNC_INV3_MASK		((0X1) << CSI_CFG_VSYNC_INV3_SHIFT)
#define CSI_CFG_VSYNC_INV2_MASK		((0X1) << CSI_CFG_VSYNC_INV2_SHIFT)
#define CSI_CFG_VSYNC_INV1_MASK		((0X1) << CSI_CFG_VSYNC_INV1_SHIFT)
#define CSI_CFG_VSYNC_INV0_MASK		((0X1) << CSI_CFG_VSYNC_INV0_SHIFT)
#define CSI_CFG_CSI_DATA_ALIGN_MASK	((0X3) << CSI_CFG_CSI_DATA_ALIGN_SHIFT)
#define CSI_CFG_HSYNC_INV3_MASK		((0X1) << CSI_CFG_HSYNC_INV3_SHIFT)
#define CSI_CFG_HSYNC_INV2_MASK		((0X1) << CSI_CFG_HSYNC_INV2_SHIFT)
#define CSI_CFG_HSYNC_INV1_MASK		((0X1) << CSI_CFG_HSYNC_INV1_SHIFT)
#define CSI_CFG_HSYNC_INV0_MASK		((0X1) << CSI_CFG_HSYNC_INV0_SHIFT)
#define CSI_CFG_LOOPBACK_EN_MASK	((0X1) << CSI_CFG_LOOPBACK_EN_SHIFT)
#define CSI_CFG_S_RESETN_MASK		((0X1) << CSI_CFG_S_RESETN_SHIFT)
#define CSI_CFG_M_RESETN_MASK		((0X1) << CSI_CFG_M_RESETN_SHIFT)
#define CSI_CFG_S_FORCERXMODE3_MASK	((0X1) << CSI_CFG_S_FORCERXMODE3_SHIFT)
#define CSI_CFG_S_FORCERXMODE2_MASK	((0X1) << CSI_CFG_S_FORCERXMODE2_SHIFT)
#define CSI_CFG_S_FORCERXMODE1_MASK	((0X1) << CSI_CFG_S_FORCERXMODE1_SHIFT)
#define CSI_CFG_S_FORCERXMODE0_MASK	((0X1) << CSI_CFG_S_FORCERXMODE0_SHIFT)
#define CSI_CFG_S3_BIASEN_MASK		((0X1) << CSI_CFG_S3_BIASEN_SHIFT)
#define CSI_CFG_S2_BIASEN_MASK		((0X1) << CSI_CFG_S2_BIASEN_SHIFT)
#define CSI_CFG_S1_BIASEN_MASK		((0X1) << CSI_CFG_S1_BIASEN_SHIFT)

#define CSI_CFG_MIPI_CHMUX_MAX		(8)

#define CSI_CFG_ISP_BYPASS_MAX		(4)

#define CSI_DATA_ALIGN_RGB8_YUV8	(0X0)
#define CSI_DATA_ALIGN_RGB666		(0X1)
#define CSI_DATA_ALIGN_RGB565		(0X2)
#define CSI_DATA_ALIGN_YUV10		(0X3)

/*
 * CSI0 DPHY STATUS0~3
 */
#define CSI0_DPHY_STATUS_S_ATB_OUT_SHIFT	(0)

#define CSI0_DPHY_STATUS_S_ATB_OUT_MASK		\
		((0xFFFFFFFF) << CSI0_DPHY_STATUS_S_ATB_OUT_SHIFT)

/*
 * CSI0 DPHY STATUS4
 */
#define CSI0_DPHY_STATUS_S_ERR3_ESC_SHIFT	(8)
#define CSI0_DPHY_STATUS_S_ERR2_ESC_SHIFT	(7)
#define CSI0_DPHY_STATUS_S_ERR1_ESC_SHIFT	(6)
#define CSI0_DPHY_STATUS_S_ERR0_ESC_SHIFT	(5)
#define CSI0_DPHY_STATUS_S_ERR3CONTROL_SHIFT	(3)
#define CSI0_DPHY_STATUS_S_ERR2CONTROL_SHIFT	(2)
#define CSI0_DPHY_STATUS_S_ERR1CONTROL_SHIFT	(1)
#define CSI0_DPHY_STATUS_S_ERR0CONTROL_SHIFT	(0)

#define CSI0_DPHY_STATUS_S_ERR3_ESC_MASK	\
		((0X1) << CSI0_DPHY_STATUS_S_ERR3_ESC_SHIFT)
#define CSI0_DPHY_STATUS_S_ERR2_ESC_MASK	\
		((0X1) << CSI0_DPHY_STATUS_S_ERR2_ESC_SHIFT)
#define CSI0_DPHY_STATUS_S_ERR1_ESC_MASK	\
		((0X1) << CSI0_DPHY_STATUS_S_ERR1_ESC_SHIFT)
#define CSI0_DPHY_STATUS_S_ERR0_ESC_MASK	\
		((0X1) << CSI0_DPHY_STATUS_S_ERR0_ESC_SHIFT)
#define CSI0_DPHY_STATUS_S_ERR3CONTROL_MASK	\
		((0X1) << CSI0_DPHY_STATUS_S_ERR3CONTROL_SHIFT)
#define CSI0_DPHY_STATUS_S_ERR2CONTROL_MASK	\
		((0X1) << CSI0_DPHY_STATUS_S_ERR2CONTROL_SHIFT)
#define CSI0_DPHY_STATUS_S_ERR1CONTROL_MASK	\
		((0X1) << CSI0_DPHY_STATUS_S_ERR1CONTROL_SHIFT)
#define CSI0_DPHY_STATUS_S_ERR0CONTROL_MASK	\
		((0X1) << CSI0_DPHY_STATUS_S_ERR0CONTROL_SHIFT)

/*
 * ISP_CLK_MASK
 */
#define ISP_CLK_MASK_PX2X_M3_SHIFT	(11)
#define ISP_CLK_MASK_PX2X_M2_SHIFT	(10)
#define ISP_CLK_MASK_PX2X_M1_SHIFT	(9)
#define ISP_CLK_MASK_PX2X_M0_SHIFT	(8)
#define ISP_CLK_MASK_PX1X_M3_SHIFT	(7)
#define ISP_CLK_MASK_PX1X_M2_SHIFT	(6)
#define ISP_CLK_MASK_PX1X_M1_SHIFT	(5)
#define ISP_CLK_MASK_PX1X_M0_SHIFT	(4)
#define ISP_CLK_MASK_BCLK_M_SHIFT	(0)

#define ISP_CLK_MASK_PX2X_M3_MASK	((0X1) << ISP_CLK_MASK_PX2X_M3_SHIFT)
#define ISP_CLK_MASK_PX2X_M2_MASK	((0X1) << ISP_CLK_MASK_PX2X_M2_SHIFT)
#define ISP_CLK_MASK_PX2X_M1_MASK	((0X1) << ISP_CLK_MASK_PX2X_M1_SHIFT)
#define ISP_CLK_MASK_PX2X_M0_MASK	((0X1) << ISP_CLK_MASK_PX2X_M0_SHIFT)
#define ISP_CLK_MASK_PX1X_M3_MASK	((0X1) << ISP_CLK_MASK_PX1X_M3_SHIFT)
#define ISP_CLK_MASK_PX1X_M2_MASK	((0X1) << ISP_CLK_MASK_PX1X_M2_SHIFT)
#define ISP_CLK_MASK_PX1X_M1_MASK	((0X1) << ISP_CLK_MASK_PX1X_M1_SHIFT)
#define ISP_CLK_MASK_PX1X_M0_MASK	((0X1) << ISP_CLK_MASK_PX1X_M0_SHIFT)
#define ISP_CLK_MASK_BCLK_M_MASK	((0X1) << ISP_CLK_MASK_BCLK_M_SHIFT)

/*
 * ISP_SWRST
 */
#define ISP_SWRST_PX2X_SWRST_SHIFT	(20)
#define ISP_SWRST_PX1X_SWRST_SHIFT	(16)
#define ISP_SWRST_DDIIF_SWRST_SHIFT	(12)
#define ISP_SWRST_X2X_SWRST_SHIFT	(8)
#define ISP_SWRST_AXI_SWRST_SHIFT	(4)
#define ISP_SWRST_APB_SWRST_SHIFT	(0)

#define ISP_SWRST_PX2X_SWRST_MASK	((0X1) << ISP_SWRST_PX2X_SWRST_SHIFT)
#define ISP_SWRST_PX1X_SWRST_MASK	((0X1) << ISP_SWRST_PX1X_SWRST_SHIFT)
#define ISP_SWRST_DDIIF_SWRST_MASK	((0X1) << ISP_SWRST_DDIIF_SWRST_SHIFT)
#define ISP_SWRST_X2X_SWRST_MASK	((0X1) << ISP_SWRST_X2X_SWRST_SHIFT)
#define ISP_SWRST_AXI_SWRST_MASK	((0X1) << ISP_SWRST_AXI_SWRST_SHIFT)
#define ISP_SWRST_APB_SWRST_MASK	((0X1) << ISP_SWRST_APB_SWRST_SHIFT)

/*
 * ISP_PX1X_DIV
 */
#define ISP_PX1X_DIV_PX1X_DIV3_SHIFT	(3)
#define ISP_PX1X_DIV_PX1X_DIV2_SHIFT	(2)
#define ISP_PX1X_DIV_PX1X_DIV1_SHIFT	(1)
#define ISP_PX1X_DIV_PX1X_DIV0_SHIFT	(0)

#define ISP_PX1X_DIV_PX1X_DIV3_MASK	((0X1) << ISP_PX1X_DIV_PX1X_DIV3_SHIFT)
#define ISP_PX1X_DIV_PX1X_DIV2_MASK	((0X1) << ISP_PX1X_DIV_PX1X_DIV2_SHIFT)
#define ISP_PX1X_DIV_PX1X_DIV1_MASK	((0X1) << ISP_PX1X_DIV_PX1X_DIV1_SHIFT)
#define ISP_PX1X_DIV_PX1X_DIV0_MASK	((0X1) << ISP_PX1X_DIV_PX1X_DIV0_SHIFT)

/*
 * ISP_BYPASS
 */
#define ISP_BYPASS_RVC_SEL_SHIFT	(4)
#define ISP_BYPASS_ISP3_BYP_SHIFT	(3)
#define ISP_BYPASS_ISP2_BYP_SHIFT	(2)
#define ISP_BYPASS_ISP1_BYP_SHIFT	(1)
#define ISP_BYPASS_ISP0_BYP_SHIFT	(0)

#define ISP_BYPASS_RVC_SEL_MASK		((0X1) << ISP_BYPASS_RVC_SEL_SHIFT)
#define ISP_BYPASS_ISP3_BYP_MASK	((0X1) << ISP_BYPASS_ISP3_BYP_SHIFT)
#define ISP_BYPASS_ISP2_BYP_MASK	((0X1) << ISP_BYPASS_ISP2_BYP_SHIFT)
#define ISP_BYPASS_ISP1_BYP_MASK	((0X1) << ISP_BYPASS_ISP1_BYP_SHIFT)
#define ISP_BYPASS_ISP0_BYP_MASK	((0X1) << ISP_BYPASS_ISP0_BYP_SHIFT)

/*
 * ISP_X2X_CFG
 */
#define ISP_X2X_CFG_PWRA_SHIFT		(9)
#define ISP_X2X_CFG_CACT_SHIFT		(8)
#define ISP_X2X_CFG_PWRN_SHIFT		(4)
#define ISP_X2X_CFG_ISP_SLEEP_SHIFT	(0)

#define ISP_X2X_CFG_PWRA_MASK		((0X1) << ISP_X2X_CFG_PWRA_SHIFT)
#define ISP_X2X_CFG_CACT_MASK		((0X1) << ISP_X2X_CFG_CACT_SHIFT)
#define ISP_X2X_CFG_PWRN_MASK		((0X1) << ISP_X2X_CFG_PWRN_SHIFT)
#define ISP_X2X_CFG_ISP_SLEEP_MASK	((0X1) << ISP_X2X_CFG_ISP_SLEEP_SHIFT)

/*
 * ISP_FMT_CFG
 */
#define ISP_FMT_CFG_ISP3_FMT_SHIFT	(12)
#define ISP_FMT_CFG_ISP2_FMT_SHIFT	(8)
#define ISP_FMT_CFG_ISP1_FMT_SHIFT	(4)
#define ISP_FMT_CFG_ISP0_FMT_SHIFT	(0)

#define ISP_FMT_CFG_ISP3_FMT_MASK	((0X7) << ISP_FMT_CFG_ISP3_FMT_SHIFT)
#define ISP_FMT_CFG_ISP2_FMT_MASK	((0X7) << ISP_FMT_CFG_ISP2_FMT_SHIFT)
#define ISP_FMT_CFG_ISP1_FMT_MASK	((0X7) << ISP_FMT_CFG_ISP1_FMT_SHIFT)
#define ISP_FMT_CFG_ISP0_FMT_MASK	((0X7) << ISP_FMT_CFG_ISP0_FMT_SHIFT)

#define ISP_FMT_RAW_RGB_8_TO_10_USING_UPPER_2BIT	(0)
#define ISP_FMT_RAW_RGB_8_TO_10_USING_ZERO		(1)
#define ISP_FMT_RAW_RGB_10_OR_MORE			(2)

#endif
