// SPDX-License-Identifier: GPL-2.0-or-later
/*
 * Copyright (C) Telechips Inc.
 */

#ifndef __TCC_MIPI_CKC_REG_H__
#define __TCC_MIPI_CKC_REG_H__

/*
 * MIPI CKC REG BASE
 */
#define CLKCTRL0	(0x00)
#define CLKCTRL1	(0x04)
#define PLLPMS		(0x08)
#define PLLCON		(0x0C)
#define PLLMON		(0x10)
#define CLKDIVC		(0x14)

/*
 * CLKCTRL
 */
#define CLKCTRL_CHGRQ_SHIFT	(31)
#define CLKCTRL_SEL_SHIFT	(0)

#define CLKCTRL_CHGRQ_MASK	((0x1) << CLKCTRL_CHGRQ_SHIFT)
#define CLKCTRL_SEL_MASK	((0x3) << CLKCTRL_SEL_SHIFT)

#define CLKCTRL_SEL_XIN		(0)
#define CLKCTRL_SEL_PLL_DIRECT	(1)
#define CLKCTRL_SEL_PLL_DIVIDER	(2)
#define CLKCTRL_SEL_RESERVED	(3)

/*
 * PLLPMS
 */
#define PLLPMS_RESETB_SHIFT	(31)
#define PLLPMS_RSEL_SHIFT	(27)
#define PLLPMS_LOCK_EN_SHIFT	(26)
#define PLLPMS_ICP_SHIFT	(24)
#define PLLPMS_LOCK_SHIFT	(23)
#define PLLPMS_BYPASS_SHIFT	(21)
#define PLLPMS_S_SHIFT		(16)
#define PLLPMS_M_SHIFT		(6)
#define PLLPMS_P_SHIFT		(0)

#define PLLPMS_RESETB_MASK	((0x1) << PLLPMS_RESETB_SHIFT)
#define PLLPMS_RSEL_MASK	((0xF) << PLLPMS_RSEL_SHIFT)
#define PLLPMS_LOCK_EN_MASK	((0x1) << PLLPMS_LOCK_EN_SHIFT)
#define PLLPMS_ICP_MASK	        ((0x3) << PLLPMS_ICP_SHIFT)
#define PLLPMS_LOCK_MASK	((0x1) << PLLPMS_LOCK_SHIFT)
#define PLLPMS_BYPASS_MASK	((0x1) << PLLPMS_BYPASS_SHIFT)
#define PLLPMS_S_MASK		((0x7) << PLLPMS_S_SHIFT)
#define PLLPMS_M_MASK		((0x3FF) << PLLPMS_M_SHIFT)
#define PLLPMS_P_MASK		((0x3F) << PLLPMS_P_SHIFT)

/*
 * PLLCON
 */
#define PLLCON_LOCK_CON_REV_SHIFT	(12)
#define PLLCON_LOCK_CON_DLY_SHIFT	(10)
#define PLLCON_LOCK_CON_OUT_SHIFT	(8)
#define PLLCON_LOCK_CON_IN_SHIFT	(6)
#define PLLCON_EXTAFC_SHIFT		(1)
#define PLLCON_AFC_ENB_SHIFT		(0)

#define PLLCON_LOCK_CON_REV_MASK	((0x3) << PLLCON_LOCK_CON_REV_SHIFT)
#define PLLCON_LOCK_CON_DLY_MASK	((0x3) << PLLCON_LOCK_CON_DLY_SHIFT)
#define PLLCON_LOCK_CON_OUT_MASK	((0x3) << PLLCON_LOCK_CON_OUT_SHIFT)
#define PLLCON_LOCK_CON_IN_MASK		((0x3) << PLLCON_LOCK_CON_IN_SHIFT)
#define PLLCON_EXTAFC_MASK		((0x1F) << PLLCON_EXTAFC_SHIFT)
#define PLLCON_AFC_ENB_MASK		((0x1) << PLLCON_AFC_ENB_SHIFT)

/*
 * PLLMON
 */
#define PLLMON_AFCINIT_SEL_SHIFT	(15)
#define PLLMON_FOUT_MASK_SHIFT		(14)
#define PLLMON_FEED_EN_SHIFT		(13)
#define PLLMON_FSEL_SHIFT		(12)
#define PLLMON_LRD_EN_SHIFT		(11)
#define PLLMON_VCO_BOOST_SHIFT		(10)
#define PLLMON_PBIAS_CTRL_EN_SHIFT	(9)
#define PLLMON_PBIAS_CTRL__SHIFT	(8)
#define PLLMON_AFC_CODE_SHIFT		(0)

#define PLLMON_AFCINIT_SEL_MASK		((0x1) << PLLMON_AFCINIT_SEL_SHIFT)
#define PLLMON_FOUT_MASK_MASK		((0x1) << PLLMON_FOUT_MASK_SHIFT)
#define PLLMON_FEED_EN_MASK		((0x1) << PLLMON_FEED_EN_SHIFT)
#define PLLMON_FSEL_MASK		((0x1) << PLLMON_FSEL_SHIFT)
#define PLLMON_LRD_EN_MASK		((0x1) << PLLMON_LRD_EN_SHIFT)
#define PLLMON_VCO_BOOST_MASK		((0x1) << PLLMON_VCO_BOOST_SHIFT)
#define PLLMON_PBIAS_CTRL_EN_MASK	((0x1) << PLLMON_PBIAS_CTRL_EN_SHIFT)
#define PLLMON_PBIAS_CTRL__MASK		((0x1) << PLLMON_PBIAS_CTRL__SHIFT)
#define PLLMON_AFC_CODE_MASK		(((0x1F) << PLLMON_AFC_CODE_SHIFT))

/*
 * CLKDIVC
 */
#define CLKDIVC_PE_SHIFT		(7)
#define CLKDIVC_PDIV_SHIFT		(0)

#define CLKDIVC_PE_MASK			((0x1) << CLKDIVC_PE_SHIFT)
#define CLKDIVC_PDIV_MASK		((0x3F) << CLKDIVC_PDIV_SHIFT)

#endif
