obj-$(CONFIG_SND_SOC_TCC) += tcc_adma_pcm.o tcc_i2s.o tcc_spdif.o tcc_cdif.o
obj-$(CONFIG_SND_SOC_TCC_AUDIO_CHMUX) += tcc_audio_chmux.o

obj-y		+= asrc/

obj-$(CONFIG_SND_SOC_TCC_CARD) += tcc-snd-card.o
