# Faraday Platform Support
snd-soc-mvf-objs := mvf-sai.o
snd-soc-mvf-twr-objs := mvf-pcm-dma-twr.o

obj-$(CONFIG_SND_MVF_AC97) += mvf-sai-ac97.o

obj-$(CONFIG_SND_MVF_SOC) += snd-soc-mvf.o
obj-$(CONFIG_SND_MVF_SOC_TWR) += snd-soc-mvf-twr.o

# Faraday Machine Support
snd-soc-mvf-sgtl5000-objs := mvf-sgtl5000.o

obj-$(CONFIG_SND_SOC_MVF_SGTL5000) += snd-soc-mvf-sgtl5000.o
