# drivers/media/platform/videosource/Makefile
#
# Copyright (c) 2010 Telechips Co., Ltd.
#	http://www.telechips.com/
# Jay <B150095@telechips.com>
#
# Licensed under GPL

obj-y += videosource_common.o
obj-y += videosource_i2c.o
obj-y += videosource_if.o
obj-y += videodecoder/
obj-y += deserializer/
obj-y += mipi-csi2/

